### PR TITLE
Fixes #2653, No Validation for sketch file rename

### LINKED ISSUE #2653: No `Validation` for sketch file `rename`
### Increasing Access

Currently we don't have any limit set for sketch file rename, plus it will also make the sketch table look messed up when user renames the file with lots of characters

sketch rename

### Feature enhancement details

We should provide max char limit to sketch file rename

### PR DESCRIPTION
**Pull request by gauravsingh94**
Fixes #2653 

Changes:
Fixed  validation for sketch file rename now it take only 100 characters as input.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by lindapaiste — CHANGES_REQUESTED** [review]
Thanks for working on this.  We would want 128 characters instead of 100 because that is what we use in other places.

I’ve discussed some other considerations in a comment on the issue: https://github.com/processing/p5.js-web-editor/issues/2653#issuecomment-1833875300

**Comment by gauravsingh94** [comment]
Output

[Screencast from 2023-12-01 14-30-41.webm](https://github.com/processing/p5.js-web-editor/assets/99260988/b9911a07-6954-44f6-a8d0-1b5980a2cf1f)

**Comment by gauravsingh94** [comment]
@lindapaiste I've incorporated the modifications you recommended and introduced some additional CSS to maintain the integrity of the website design. 
Could you please share your feedback on these changes?

**Review by raclim — APPROVED** [review]
Thanks for your work on this! I personally found adding in the `maxLength` and the `overflow-wrap` to be visually okay for now and updated this PR with these changes. However, if it seems like it might need a few more changes I think that can be added later on as well.

**Pull request merged**
