### PR TITLE
Issue#298 fix vertical alignment

### PR DESCRIPTION
**Pull request by Katy310**

### CODE REVIEW

**Comment by catarak** [comment]
just tested this, and to me it seems like the alignment is still off.
screen shot 2017-02-14 at 3 33 12 pm
I noticed that you added 10px padding to the top, but in #298 there is only an alignment issue of 2px. Maybe only 2px of padding should be added, or maybe the pencil icon is pushing down the title and causing the misalignment?

**Comment by Katy310** [comment]
2px Does not solve the problem. 
selection_045

**Comment by catarak** [comment]
okay, then I'm sure there's another way to fix it! if you need help figuring this out let me know 😄

**Comment by Katy310** [comment]
I will try and investigate whether the pencil icon is creating a problem.

**Pull request closed without merging**
