### PR TITLE
Extract translation keys for Console, Sidebar, FileNode

### PR DESCRIPTION
**Pull request by andrewn**
This extracts the UI text for Console, Sidebar and FileNode components in English, ready for Spanish translations.

I extracted `Common.DeleteConfirmation` as I know that the same language is used in many places in the app.

There's some duplication with the  "add file/folder" entries in Sidebar/FileNode. If we want them to share a translation entry in future then they should use a shared component. For now, this is fine.

@oruburos Can you review this please?

--

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)

### CODE REVIEW

**Comment by oruburos** [comment]
I think that the check is failing because the FileNode.test have a problem. It is related to #1537 and how to mock the t function in the tests.

**Comment by andrewn** [comment]
@oruburos I've fixed the failing tests by mocking `react-i18next` in all the client-side tests. This provides a mock `t` function that will perform a look-up on the real English translations.

We'll probably want to re-visit this in future and use i18next directly, but I think this is good enough for now as it unblocks the translation work.

**Comment by oruburos** [comment]
Yes, this works!

**Comment by andrewn** [comment]
> Yes, this works!

Great! Can you approve this PR and I'll merge it.

**Comment by andrewn** [comment]
This PR is about extracting the English text and getting it ready for Spanish translations. If you approve it, I can then merge it and you can do a follow-up PR with the Spanish translations.

**Comment by andrewn** [comment]
FYI: `ToggleFileOptionsARIA` is not translated in your comment above.

**Review by oruburos — APPROVED** [review]

**Pull request merged**
