### PR TITLE
refactor console reducers and actions using redux toolkit

### PR DESCRIPTION
**Pull request by PiyushChandra17**
Associated issue: #2042 

Changes:
+ First things first removed all the associated `constants`
+ Used `createSlice` to rewrite the console reducer
+ Exported the automatically generated action creator functions from actions/console.js
+ Deleted the existing action creator function

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by raclim** [comment]
Thanks for your work on this! I'm skimming over this at the moment so I'm sorry that my feedback isn't very specific, but while running this branch I noticed that a few errors pop up when I try to run my sketch.

**Comment by PiyushChandra17** [comment]
> Thanks for your work on this! I'm skimming over this at the moment so I'm sorry that my feedback isn't very specific, but while running this branch I noticed that a few errors pop up when I try to run my sketch.

Sure, I'll take a look at this one, and try fixing that few errors, probably push the new changes to this branch super soon!

**Comment by PiyushChandra17** [comment]
@raclim I think i have fixed the errors being popped up while running the sketch, can you please check?

**Review by raclim — APPROVED** [review]
I think this looks good for now, thanks for your work on this!

**Pull request merged**
