### PR TITLE
Fixes:Inconsistent Behaviour of play-sketch button

### LINKED ISSUE #2642: Inconsistent Behavior of Play-Sketch Button Between PC and Mobile Modes
### p5.js version

v2.9.3

### What is your operating system?

Windows

### Web browser and version

Chrome

### Actual Behavior

The "Play-Sketch" button exhibits inconsistent behavior when transitioning between PC and mobile modes. When the button is activated in PC mode and then the mode is switched to mobile, the button appears to be in the "on" state, but the sketch does not run. Similarly, when activating the "Play-Sketch" button in mobile mode and switching back to PC mode, the button visually indicates that it's on, but the sketch does not execute.

https://github.com/processing/p5.js-web-editor/assets/127239756/639fa0a7-ea0b-4d2c-b959-f15d3b4ba50f

### Expected Behavior

The "Play-Sketch" button should seamlessly adapt to changes in screen size and consistently execute the sketch when activated. Regardless of whether the application is viewed in PC mode or mobile mode, the button should accurately reflect its functional state, and the sketch should run as expected. The user experience should remain smooth and responsive.

### Steps:
1. Open the application in PC mode.
2. Click the "Play-Sketch" button.
3. Switch to mobile mode.
4. Observe the behavior of the "Play-Sketch" button.

### PR DESCRIPTION
**Pull request by Mubashirshariq**
Fixes #2642 

Changes:

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by lindapaiste — COMMENTED** [review]
Can you explain how this solves the problem?  I don't understand.

**Comment by Mubashirshariq** [comment]
I added a ref called previewFrameRef to store the PreviewFrame instance. Then, I passed this ref to the PreviewFrame component using the ref prop. This ensures that the same PreviewFrame instance is maintained across different views or modes, preserving the state and functionality of the iframe

**Comment by lindapaiste** [comment]
> I added a ref called previewFrameRef to store the PreviewFrame instance. Then, I passed this ref to the PreviewFrame component using the ref prop. This ensures that the same PreviewFrame instance is maintained across different views or modes, preserving the state and functionality of the iframe

But don't we have two different places in the code with `<PreviewFrame>`?  The other one is at line 196.

**Comment by Mubashirshariq** [comment]
@lindapaiste  sorry  i actually forgot to commit that

**Comment by raclim** [comment]
Thanks for working on this! Due to the amount of time that's passed I'm going to close this PR for now. Please feel free to reopen this or check out our other issues!

**Pull request closed without merging**
