### PR TITLE
Sketch collections

### PR DESCRIPTION
**Pull request by andrewn**
Implementing features in #1115.

## Editor API for Collections

|                Route                 |               Purpose               |            Restrictions            |
| ------------------------------------ | ----------------------------------- | ---------------------------------- |
| `GET /collections`                   | Fetch current user's collections    | Logged in user                     |
| `GET /:username/collections`         | Fetch a specific user's collections |                                    |
| `POST /collections`                  | Create a new collection             | Logged in user                     |
| `PATCH /collections/:id`             | Update collection metadata          | Logged in user must own collection |
| `DELETE /collections/:id`            | Delete collection                   | Logged in user must own collection |
| `POST /collections/:id/:projectId`   | Add a project to a collection       | Logged in user must own collection |
| `DELETE /collections/:id/:projectId` | Remove a project from a collection  | Logged in user must own collection |

## Features

- [x] Editor API to CRUD collections
- [x] Lists of your own and other user's collections (`/:username/collections`)
- [x] View any user's collection (`/:username/collections/:collectionId`)
- [x] Create your own collections (`/:username/collections/create`)
- [x] Edit your collection's name and description (Click name and description on collection page)
- [x] Easily get a shareable URL for the collection ("Share" link on collection page)
- [ ] See and edit the collection slug
- [x] Delete your own collections (via dropdown on collection list)
- [x] Add any sketch to one of your collections (via File → Add to collection)
- [x] Add your own sketches to one of your collections (`/:username/collections/:collectionId` →
"Add more sketches")

## Checks

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by andrewn** [comment]
@catarak As discussed, this branch is "feature-complete" so I'd really love your feedback on the UI flow. Does it makes sense? Are any flows missing.

I'm going to work on tidying up the code as there are prop-types to be added and some components to refactor.

I'll also work on finessing the UI details once you're happy with the overall shape of the UI.

**Comment by catarak** [comment]
I had a chance to review this, and here's a list of notes so far:
- Rather than being full screen, I think the "Create Collection" view should just be a popover. It feels like overkill to have it be full screen.
- The header for a collection is a little awkward. I'll think about possible design ideas. 
- "My Collections" overflows in dropdown:
Screen Shot 2019-09-25 at 1 28 00 PM
- It feels superfluous to have "My Collections", "My Sketches", and "My Assets" in the dropdown, when they're all basically on the same page. Maybe it would make sense to collapse it into "Dashboard" or "My Stuff" or something like that, and maybe the url could just be "/<username>", and double as a profile page? It could render differently if it's the user's account. 
- Is there any reason the DasboardView isn't using React Tabs?

I'll keep adding notes as I test it more.

**Comment by catarak** [comment]
More notes: 
- I think in the Sketch List, one of the options should be "Add to collection". Then, this opens a popover with the user's list of collections, with a view button. It's kind of similar to Glitch.com flow, except I don't like how tiny the dropdown is. Eventually the Searchbar could be made generic for collections or sketches and added here. 
Screen Shot 2019-09-25 at 1 58 40 PM

- I'm not sure how I feel about the "+" and "-" buttons. I get the reasoning, that it makes it easy to add a few sketches at a time to a collection, but it feels a little awkward to me. I think it would be cool, on the Collection List page, to have an option that's "Add Sketch", which opens the sketch list popover, which functions and looks basically the same as the "Add Collection" popover. 
- On the Collection View page, rather than "Add Sketches" at the bottom, I think there should be a button on the upper right, similar to the "New Sketch" or "New Collection" button on the Sketch List or Collection List view. I'll think about how to fit this in with a different design for a Collection header.

**Comment by catarak** [comment]
also i'm happy to help with any of these updates!!!

**Comment by catarak** [comment]
Okay, I worked on the header a bit and came up with this:
collection_header1
collection_header2
I wasn't sure where to put the "Share" button, or if it needs to be as big/have the same styling. Maybe the "Add Sketch" button could be pink so it's more of a CTA? I figured a user could click on it and then the "Copied to Clickboard" thing could come up.

**Comment by andrewn** [comment]
Pushed some changes to address the following:

> Rather than being full screen, I think the "Create Collection" view should just be a popover. It feels like overkill to have it be full screen.

Agreed, it's now a modal over the collections list view.

> "My Collections" overflows in dropdown:

I can't reproduce this behaviour on Mac Safari 13.0.1, Mac Chrome 77.0.3865.90, Mac Firefox 69.0.1. What are you using?

> It feels superfluous to have "My Collections", "My Sketches", and "My Assets" in the dropdown, when they're all basically on the same page. Maybe it would make sense to collapse it into "Dashboard" or "My Stuff" or something like that, and maybe the url could just be "/", and double as a profile page? It could render differently if it's the user's account.

I think it's more obvious to have individual menu items for Sketches, Collections and Assets. It's also one click less to get to everything. I'd also vote to have a menu item for "My Profile" when we come to that 😄 . But I'll defer to you on this one. Is this something to do in a future PR?

> Is there any reason the DasboardView isn't using React Tabs?

I think it was because I wanted the tabs to be links, and it felt like a lot of ceremony to manage the link behaviour and state of the selected tab via React Tabs instead of URLs.

> Obviously now the Searchbar component is overlapping with the CTA button "Add Sketch". I guess the search bar should be to the left of it?

I moved this to the left of the "Add Sketch" button. I'll do a PR for adding collection and asset search later!

> On the Collection View page, rather than "Add Sketches" at the bottom, I think there should be a button on the upper right, similar to the "New Sketch" or "New Collection" button on the Sketch List or Collection List view. I'll think about how to fit this in with a different design for a Collection header.

This is much better, I've moved it.

**Comment by catarak** [comment]
> I can't reproduce this behaviour on Mac Safari 13.0.1, Mac Chrome 77.0.3865.90, Mac Firefox 69.0.1. What are you using?

I'm using Chrome 77.0.3865.90 also! Super weird. 

> I think it was because I wanted the tabs to be links, and it felt like a lot of ceremony to manage the link behaviour and state of the selected tab via React Tabs instead of URLs.

Got it! Just wondering if it would help with the styling to use React Tabs. Would it be possible for the styling to match closer to the account view/settings view tabs? The font sizing, the spacing, and the underline styles are a little different. Also, the line at the bottom of the tabs doesn't extend the fill width of the page.

**Comment by andrewn** [comment]
Made some more UI changes:
- You can now delete your own collections (via drop-down menu item on collection list)
- Updated Dashboard switcher tab styles (Sketches, Collections, Assets) to match the ReactTabs. I had styled them bigger previously as I thought they looked better as headings.

- *Sketch List* now has "Add to collection" dropdown item. I was exploring making it look a bit like the Glitch one (see screenshot). What do you think? Is it better if it's a modal like the others?

Screenshot 2019-10-21 01 23 15

- *Add to collection from Sketch view:* The +/- are now gone on the _Add to Collection modal_. Clicking anywhere on the row adds/removes. The tick icon needs to be replaced with a proper one.

Screenshot 2019-10-21 01 23 43

**Comment by catarak** [comment]
Progress on this is looking great! I have some time tomorrow to dive in and give feedback.

**Comment by catarak** [comment]
I think overall the flow is a lot smoother! 

Looking at all of this, and sitting and thinking about it, I think there's an open UI/UX question which is, "what goes under the down triangle arrow, which contains all actions, and when does it need to be brought up a level to its own icon/button?" There's some nice consistency with the dropdown arrow, as throughout the app it contains "actions for the file/sketch/collection/etc." But if something only has one section, does it make sense to put it in a dropdown? Are there certain actions that are too important to never be in a dropdown?

So, when adding sketches to a collection, there's three actions, right? "View" (the sketch or collection), "Add", and "Remove". There's also a state we want to capture, which is whether or not a sketch is in a collection (which could apply to a sketch or a collection). Whatever UI/UX we decide for this, I think it should just be consistent. 

Another thing to think about, is that currently, in the list of sketches, clicking on a sketch opens it. So maybe it's confusing to change that action to add or remove a sketch from a collection?

Phew, okay, now that I have that all written down, hopefully it will help make a decision about how to refine this!

**Comment by catarak** [comment]
One other thing, the tab switcher is looking good,; however, I think it being adjustable width is feeling awkward. Some possible solutions are:
1. Place the items inline with the tabs (I guess by positioning them absolutely?)
2. Put the search box/new sketch/new collection buttons below the tabs:
Screen Shot 2019-10-24 at 3 39 07 PM
I think we need some design to demarcate a block of items, which, whatever that ends up being, could also be used for the single collection heading.

**Comment by andrewn** [comment]
> Looking at all of this, and sitting and thinking about it, I think there's an open UI/UX question which is, "what goes under the down triangle arrow, which contains all actions, and when does it need to be brought up a level to its own icon/button?" There's some nice consistency with the dropdown arrow, as throughout the app it contains "actions for the file/sketch/collection/etc." But if something only has one section, does it make sense to put it in a dropdown? Are there certain actions that are too important to never be in a dropdown?
> 
> So, when adding sketches to a collection, there's three actions, right? "View" (the sketch or collection), "Add", and "Remove". There's also a state we want to capture, which is whether or not a sketch is in a collection (which could apply to a sketch or a collection). Whatever UI/UX we decide for this, I think it should just be consistent.

There are three possible actions, but only two will ever be shown. "View" and then either "Add" or "Remove". Because a sketch is either in a collection or not.

> Another thing to think about, is that currently, in the list of sketches, clicking on a sketch opens it. So maybe it's confusing to change that action to add or remove a sketch from a collection?

If I'm understanding correctly, there are a few things here:
1. _In a list view, should some "primary" or important actions be pulled out of the dropdown menu and displayed as action buttons in the row?_ Can we identify a primary action for all the places we have a dropdown menu? Unless we use icons, I think we only have enough space for one button? If so, then I think having primary actions make sense.
2. _If a dropdown menu only contains 1 item, should it still be a dropdown? Or should it be a single button._ 
I think if there's only one item and it's a primary action, then it should be a button. But sometimes it makes sense that it's a dropdown because in future we plan to add more actions. e.g. the `CollectionList` only has "Delete" as an option, but I think in future you should be able to rename the collection and possibly add a sketch?
3. _Is an icon on the left of the row enough to display whether a sketch is in a collection?_ 
4. _When adding a sketch to a collection, should the behaviour of clicking on a row change to add/remove the sketch from the collection?_
I think these are connected. I wonder whether the issue is that we're overloading the "list modal" design for two different things? It feels like adding/removing sketches from a collection is more of a quick action, that you want to perform and then close again. I don't think in this state you should be able to perform any other actions, except for "view". But because it's the same list view layout,  there's an expectation that you can perform other actions? Should it have a different design to differentiate that it's a different thing?

**Comment by catarak** [comment]
1. This concept of a primary action makes sense to me!
2. I agree that if there's only one action, it doesn't need to be in a dropdown. Maybe it's okay if it isn't a primary action? If later on, more actions need to be added to a list item, it can be moved from a button/icon to the dropdown, and the primary action is therefore changed.
3. I think an icon is enough to show whether a sketch belongs to a collection or not. One think I don't like about it being on the left is that everything gets pushed over to the right, but maybe it can be in a fixed width column so that it doesn't shirt over the sketch/collection title. 
4. That's a great point about the overloaded design, and maybe it does need to be visually different!

**Comment by catarak** [comment]
I'm going to try to write out what I _think_ the primary actions are:
- Sketch List: View Sketch
- Collection List: View Collection
- Sketch List within Collection View: View Sketch
- Asset List: View Asset (in a new window?) (i think this means the "view" column should be changed)
- "Add Sketch to Collection" List of Collections: Add or Remove Sketch to Collection
-  "Add Sketch to Collection" List of Sketches: Add or Remove Sketch to Collection

**Comment by catarak** [comment]
An alternate design for the "Add to Collection" dropdown:
Screen Shot 2019-10-24 at 4 26 04 PM

**Comment by catarak** [comment]
I had a moment of inspiration about how to separate the collection header/search box/action buttons. What if it's not that they need to be in a box, but the list of sketches/collections/assets need to be in a box? Here are some design ideas:

Screen Shot 2019-11-07 at 4 05 58 PM
Screen Shot 2019-11-07 at 3 35 08 PM
Screen Shot 2019-11-07 at 3 34 43 PM

I also made the inner content a little less wide (I put it at 1012px to be exact, which is a number i pulled from the GitHub website design).

**Comment by andrewn** [comment]
Just pushed some more changes:

- Slimmed-down "quick add" modal with icons showing whether a sketch is in a collection. The "+" and "x" icons appear on hover showing what action will happen when the row is clicked.

Screenshot 2019-11-10 22 02 21

- Added collection list filtering Searchbar

- Put border around the lists, as you suggested. I think it works really well!

- Instead of adding a "delete" icon, I implemented the "Rename collection" menu item in the Collection List view. I think it makes sense since this is possible in the sketch list view.

**Comment by andrewn** [comment]
> I had a moment of inspiration about how to separate the collection header/search box/action buttons. What if it's not that they need to be in a box, but the list of sketches/collections/assets need to be in a box?

💥  Genius!

**Comment by catarak** [comment]
Stuff I'm noticing on this review, that we can talk through tomorrow:
- a few icons/things not changing with the themes
- when you refresh the theme disappears
- on an individual collection, the share button & popup could be improved
- from an individual collection, i find myself wanting to go back to the dashboard page/list of collections
- maybe on collection list page, one item is add sketch?
- still not sure what to do about just "delete from collection" in the list of sketches that belong to a collection
- on the add sketch/add collection overlay, the "view" buttons don't work 
- on the add sketch/add collection overlay, should this have a fixed height?

**Comment by andrewn** [comment]
Turning your feedback into a checklist so we can track progress:

### Bugs

- [ ] a few icons/things not changing with the themes
- [ ] when you refresh the theme disappears
- [x] on the add sketch/add collection overlay, the "view" buttons don't work 

### Design issues

- [ ] on an individual collection, the share button & popup could be improved
- [ ] from an individual collection, i find myself wanting to go back to the dashboard page/list of collections
- [ ] maybe on collection list page, one item is add sketch?
- [ ] still not sure what to do about just "delete from collection" in the list of sketches that belong to a collection
- [ ] on the add sketch/add collection overlay, should this have a fixed height?

**Comment by catarak** [comment]
just pushed a potential option for the collection sharing, see 001a30f14050a8682ab7bccbd1b5499e289deb4c

**Comment by andrewn** [comment]
I've been working on some nav-bar ideas so that it's easier to get back to the Collection List from an individual Collection page.

### A. Always show _Sketches_ and _Collections_ links  on Dashboard and Collection page?

Option 1: Show the owner of the collection's username is in the link text as you're on their dashboard page...

Screenshot 2019-12-11 14 37 11

Option 2. No owner in the link name, but in both instances you get these awkward situations where the links appear twice...

Screenshot 2019-12-11 14 39 01

### B. Show "< Collections" as a link on the individual collection?

On the dashboard, the p5 logo takes you to the editor:

Screenshot 2019-12-11 14 42 22

On the collection page, you see a back to collections link:

Screenshot 2019-12-11 14 42 27

**Comment by andrewn** [comment]
> On the add sketch/add collection overlay, should this overlay have a fixed height?

Done

**Comment by andrewn** [comment]
> On collection list page, maybe the item dropdown should include "add sketch"?

Done

**Comment by andrewn** [comment]
@catarak I think I've addressed all the changes, apart from the Nav/Getting back to collections issue... see [comment above](https://github.com/processing/p5.js-web-editor/pull/1164#issuecomment-564551408).

**Comment by catarak** [comment]
Only small stuff left:
- [ ] Description should be inactive color if a collection doesn't have one
- [ ] Description pencil is misaligned
- [ ] username should link to that user's sketches (maybe?)
Screen Shot 2020-01-13 at 2 32 57 PM
- [ ] i think the contrast between the inactive check and active check is pretty subtle—there's not really another color in the theme and maybe one should be added, i'm thinking the blue that's in the code syntax or a green
Screen Shot 2020-01-13 at 2 42 35 PM
- [ ] On the collection list view, the dropdown says "add sketches". On the single collection view, there's a button that says "add sketch". The overlay that appears says "add sketches." The copy should all match, probably, right?
- [ ] Navigating from single collection back to tabbed dashboard view - I think having "Back to Editor" is more important than "Back to Collections", esp since people are going to be used to navigating from the Editor view.

**Comment by andrewn** [comment]
@catarak I've made all the changes in the list, apart from the nav bar which we can chat about later.

Here are the new icon contrasts:

Screenshot 2020-01-15 12 19 17
Screenshot 2020-01-15 12 21 04
Screenshot 2020-01-15 12 22 03

**Comment by andrewn** [comment]
Reverted the top-level nav to "Back to Editor"

@catarak All done!

**Comment by catarak** [comment]
🎉 🎉 🎉 i'm going to doing a bunch of testing on staging!!

**Pull request merged**
