### PR TITLE
Adding basic meta tags.

### PR DESCRIPTION
**Pull request by himanshuc3**
- [x] MIME type
- [x] keywords
- [x] Description

### CODE REVIEW

**Comment by catarak** [comment]
awesome! in the future, could you open an issue first so that the pull request can reference an issue? also this brings up a good question as to what we want these meta tags to be. thoughts @lmccart & @shiffman?

**Comment by shiffman** [comment]
This is great! I might suggest avoiding the word "playground", I like the spirit of that very much, but it might be confusing as there is @yining1023's project which is actually called p5 playground! http://1023.io/p5-inspector/

I think for now: "p5.js", "p5.js web editor", "web editor" are good?

**Comment by lmccart** [comment]
I would also add "processing", "code editor"

**Comment by catarak** [comment]
could you change the description from "A web editor for sketching using p5.js library." to "A web editor for p5.js, a JavaScript library with the goal of making coding accessible to artists, designers, educators, and beginners."

**Comment by himanshuc3** [comment]
:zap:

**Comment by catarak** [comment]
could you also add these meta tags to `server/views/404page.js`? also `server/views/mailLayout.js`? emails also have meta tags, right?

**Comment by himanshuc3** [comment]
Do you want me add the same or have a discussion about what their description should contain.

**Comment by catarak** [comment]
i think they should be the same, thanks!

**Comment by himanshuc3** [comment]
@catarak I added meta tags to 404error page. MailLayout page is made using mjml library and I could not find any existing meta tag support, though basic tags such as IE-edge support, content type are added by default. Adding meta tags to mailLayout could be made using another PR as a custom component could be made for it.

**Comment by catarak** [comment]
okay! i can open an issue about it. maybe emails don't need meta tags, but we can investigate it!

**Pull request merged**
