### PR TITLE
Fixed Folder bug (#963)

### PR DESCRIPTION
**Pull request by siddhant1**
I have verified that this pull request:

* [ x] has no linting errors (`npm run lint`)
* [x ] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by siddhant1** [comment]
Ref #963

**Comment by catarak** [comment]
i don't think this is the right way to fix this issue. the add file/folder overlay needs a local state (as in, the state is in React and not Redux), which is the parent folder that the file/folder is being added to.

**Comment by siddhant1** [comment]
Not sure if I understand that completely , I will try a different implementation (as you suggested) but I am not able to catch the problems with the current one.

**Comment by catarak** [comment]
i'm not saying that this implementation doesn't work, i'm saying that i don't think it is the right approach.

**Comment by siddhant1** [comment]
@catarak can you guide me in the right direction?

**Comment by catarak** [comment]
@siddhant1 sure! rather than dispatching an action that changes the selected file, the add file/add folder modal should contain within its state the parent folder (by passing that id from the file that a user clicked the down arrow on to the modal), and then creating the file/folder within that file.

**Pull request closed without merging**
