### PR TITLE
Add new keyboard shortcut entry for Add Cursor at Next Match

### PR DESCRIPTION
**Pull request by tirtawr**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by andrewn** [comment]
Thanks for opening this PR!

I can't find an issue discussing this change. We already have "Find Next Text Match" ({metaKeyName} + G) in the shortcuts help list. Could you explain what the difference is between that and  "Add Cursor at Next Text Match" ({metaKeyName} + D)?

I don't think we should add shortcuts if they do similar things. Thanks!

**Comment by tirtawr** [comment]
@andrewn I probably should have added an issue prior to this, my bad. "Find Next Text Match" is just a normal text search. "Add Cursor at Next Text Match" on the other hand, adds a cursor at the next text match, it's a feature of codemirror. Great for renaming variables or texts.

**Comment by catarak** [comment]
Thanks for opening this PR! The web editor has Sublime Text keyboard shortcuts built in and maybe it makes more sense to just say something like "Text editing keyboard shortcuts are like Sublime Text" and link to sublime text keyboard shortcuts?

**Comment by catarak** [comment]
(This seems like a pretty nice list: https://shortcuts.design/toolspage-sublimetext.html)

**Comment by tirtawr** [comment]
seems like I messed up this branch, I'm moving this to https://github.com/processing/p5.js-web-editor/pull/1438

**Pull request closed without merging**
