### PR TITLE
Make background color take up full viewport height in dark mode

### LINKED ISSUE #1662: Text in Sign Up page fades into background in dark mode
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome (86.0.4240.111)
- Operating System: Windows 10
- Steps to reproduce this bug:

While in dark mode, the "Already have an account?.." portion at the bottom fades into the background.

p5 js Web Editor _ Signup - Google Chrome 01-11-2020 01_25_07

It should ideally look something like this:

p5 js Web Editor _ Signup - Google Chrome 01-11-2020 01_25_44

@catarak I'd be glad to change this if it would be handy.

### PR DESCRIPTION
**Pull request by Swapnil-2001**
Fixes #1662 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

@catarak kindly let me know if the change is appropriate.

### CODE REVIEW

**Comment by catarak** [comment]
I'm confused about this PR—the changes you made don't affect the sign up page at all? And also, could you remove the changes to `package-lock.json` as there shouldn't be any, since you're only changing styles?

**Comment by Swapnil-2001** [comment]
p5 js Web Editor _ Signup - Google Chrome 01-11-2020 01_25_07

What I intended to fix was the background color not covering the entirety of the page and making the text at the bottom difficult to read. I believe that has now been fixed.

And I'm not quite sure why, but the package-lock.json also got changed. I'll remove those changes.

**Comment by catarak** [comment]
> What I intended to fix was the background color not covering the entirety of the page and making the text at the bottom difficult to read. I believe that has now been fixed.

I hear that! I'm just saying that the styles that you changed aren't present on the Sign Up page so I'm not sure why it fixes it. 

Also... I think the commit history is messed up here 😢

**Comment by Swapnil-2001** [comment]
**_user.scss**
```
.user {
	display: flex;
  flex-direction: column;
  height: 100%;
  flex-wrap: wrap;
  @include themify() {
    color: getThemifyVariable('primary-text-color');
    background-color: getThemifyVariable('background-color');
  }
}

.login,
.signup,
.reset-password-container,
.new-password-container,
.email-verification {
  height: 100%;
  @include themify() {
    color: getThemifyVariable('primary-text-color');
    background-color: getThemifyVariable('background-color');
  }
}
```

Sorry if I'm being a bit of a bother, but I'm afraid I still don't understand. The changes I applied were to the 'signup' class which takes care of the background of the signup page. It's where I found the height specified, so I felt this was the right place to make changes.

And my apologies for messing up the commit history, I thought I needed to rebase my branch before making any new changes on the branch.😥 Perhaps this pull request could be closed, and I'll give it a fresh try?

**Comment by catarak** [comment]
> Sorry if I'm being a bit of a bother, but I'm afraid I still don't understand. Are you saying that no changes have been applied by the pull request? As in, the changes I intended to make haven't been applied and the Sign Up page is exactly the same as it already was?

I'm saying I'm confused as to why the changes you made work. For me, I'm actually not able to reproduce the original issue (on Chrome/Mac), and then the styles you applied are for classes that aren't present on the Sign Up page.

> And my apologies for messing up the commit history, I thought I needed to rebase my branch before making any new changes on the branch.😥 Perhaps this pull request could be closed, and I'll give it a fresh try?

I think making a new branch is probably easiest!

**Comment by Swapnil-2001** [comment]
But the 'signup' class is present on the Sign Up page, isn't it? I modified that class.

And yes, I'll make a new branch.

**Comment by catarak** [comment]
> But the 'signup' class is present on the Sign Up page, isn't it? I modified that class.

Ahh I'm so sorry the selector was cut off in the diff! You are correct.

**Comment by Swapnil-2001** [comment]
Thank you for having patience with me, appreciate it a lot!😅

I think the issue comes up when the viewport is relatively small (I mean laptop screens, not mobile) and you have to scroll down to see the entire page. So would I make a new branch with the changes? Asking since you said you couldn't reproduce it.

**Comment by catarak** [comment]
> So would I make a new branch with the changes?

Yes!

**Pull request closed without merging**
