### PR TITLE
Update createDefaultFiles.js to reflect p5.js version 1.7.0

### PR DESCRIPTION
**Pull request by SableRaf**
~~Fixes #issue-number~~

Changes: Updates the p5.js version to 1.7.0

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by raclim — APPROVED** [review]
Thanks so much for working on this! Going to loop @Qianqianye here as well :)

**Comment by SableRaf** [comment]
No problem! I made the changes live on Twitch so it provided educational value too 😄

Thanks @lindapaiste for consolidating all the files so only `defaultHTML` in `createDefaultFiles.js` needs to be updated!

**Comment by Qianqianye** [comment]
Thanks @SableRaf and @raclim. I just double checked the version at [web editor page](https://editor.p5js.org/), and it seems like that the version is not updated yet.

**Comment by raclim** [comment]
I haven't deployed these updates to production yet, since I'm still testing [the mirror I replaced the missing `console-feed` package](https://github.com/processing/p5.js-web-editor/pull/2287) with. I'll keep you all posted when it's live, which should definitely be sometime this week!

**Comment by raclim** [comment]
@Qianqianye Just deployed the editor, which should reflect the new p5.js version!! I'll probably update the p5.js version for the Examples too by next week!

**Pull request merged**
