### PR TITLE
Vendor hash support in prod config  - Fixes #493

### LINKED ISSUE #493: vendor.js not being assigned a unique hashed filename
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

If you view the source of the main index page served from a production deployment, you'll observe that the vendor.js file did not get assigned a unique hashed filename like app.js and app.css. This can potentially cause issues if a newer index file fetches an older version of vendor.js served up from a cache.

### PR DESCRIPTION
**Pull request by dhruvdutt**
Add support for vendor hashing in [webpack.config.prod.js](https://github.com/processing/p5.js-web-editor/pull/571/files#diff-b83f3305d04bb1c8d674be30b5f9e1efR92)

image

```diff
new webpack.optimize.CommonsChunkPlugin({
   name: 'vendor',
   minChunks: Infinity,
-  filename: 'vendor.js',
+  filename: '[name].[chunkhash].js',
}),
```

* [x] there are no linting errors -- `npm run lint`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master. If you're asked to make more changes make sure you rebase onto master then too!
* [x] pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

Fixes #493

### CODE REVIEW

**Comment by dhruvdutt** [comment]
@catarak Please review.

**Comment by catarak** [comment]
this is great but this re-adds a submodule that was deleted. can you remove it?

**Comment by dhruvdutt** [comment]
@catarak Sorry, I forgot to clean this up. Done now. :100:

**Comment by catarak** [comment]
all good, thanks!

**Pull request merged**
