### PR TITLE
fixes-#3235:userName_dup_check added some delay to call API

### LINKED ISSUE #3235: Enhance SignupForm with Debounced Validation
### Increasing Access

Unsure

### Feature enhancement details

**Current Behavior**

Screenshot 2024-09-21 at 10 01 59 PM

The SignupForm component currently validates the username and email fields on every keystroke, potentially causing excessive API calls and affecting performance.

**Proposed Enhancement**
Implement debouncing for the username and email field validations to reduce the number of API calls and improve overall form performance.

**Expected Behavior After Enhancement**
->Validation for username and email fields should only occur after the user has stopped typing for a short period (e.g., 300ms).
->This should significantly reduce the number of API calls made during form completion.
->The user experience should be smoother, with less apparent lag during typing.

### PR DESCRIPTION
**Pull request by PratyushSawan**
Fixes #3235 

Changes:

This Fix ensures that the `asyncValidate` function only runs after 500ms of inactivity. It decreased the API Call significantly.
All the previous functionality working as it is.

Here is the Test Video:

https://github.com/user-attachments/assets/a0d15d90-6184-4616-a7df-7861cc0ea093

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by lindapaiste** [comment]
It looks like you are on the right track with this approach.  I suspect that we want separate `timeoutId` variables for the username and email checks (ie. `usernameTimeoutId` and `emailTimeoutId`).  Otherwise editing one field will cancel the timeout on the other.

**Comment by PratyushSawan** [comment]
Hi @lindapaiste Thanks for your input, I added the desired changes as per you suggestion.

Thank you.

**Comment by raclim** [comment]
Thanks so much again for your work on this! 

While this is functional, I don't think this is a complete solution yet and might need some further work to get there. Since it's been a while since this PR was last active, I'm going to close this for now. 

I'm sorry that we couldn't get this in, but please feel free to reopen this PR with any updates or check out our other issues!

**Comment by satyanvm** [comment]
Can you suggest the further works to be done here, I can pick it up.
Thank you

**Pull request closed without merging**
