### PR TITLE
Add prototype of language selector design

### PR DESCRIPTION
**Pull request by catarak**
✨ Requesting feedback ✨ from @andrewn and @oruburos 

Yesterday, @ghalestrilo and I talked about integrating the translations with the mobile design (#1559). In trying to come up a design for how to select languages on mobile, I was messing around with the desktop design to see if that would generate ideas and I came up with this:

Screen Shot 2020-08-19 at 2 58 17 PM
Screen Shot 2020-08-19 at 2 58 12 PM
Screen Shot 2020-08-19 at 3 12 48 PM

I don't want to step on your toes so feel free to ignore this, change this, etc.—do what you think is best! I figured I would just put it out there 😄 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by andrewn** [comment]
Yeah, I think this looks good.

The two key ideas here are:
- aligning the menu to the right, next to the account selection
- displaying the current language in the menu instead of "language"

@oruburos What do you think?

**Comment by oruburos** [comment]
I like the idea. Clearly is cleaner, my "design" is just floating in the middle of nowhere. Also, displaying the actual language instead of some generic top-level label for the dropdown is a nice touch.

**Comment by catarak** [comment]
@oruburos okay awesome! I'll let you take the lead on this one and do what you would like with this PR—feel free to add on top of it or make your own.

**Comment by oruburos** [comment]
@catarak Yes, I tried that approach, but I think that also requires PR #1568, (at least, when I used a local branch with both changes everything went smooth, which was not the case without that patch) so once that we merged that PR #1568 I will create the PR.

**Comment by oruburos** [comment]
This change is the main component of PR #1582, I suggest to close this PR.

**Comment by andrewn** [comment]
Closing this PR in favour of #1582.

**Pull request closed without merging**
