### PR TITLE
Translates developer docs to brazilian portuguese

### PR DESCRIPTION
**Pull request by Phe0**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

Fixes [#1320 ](https://github.com/processing/p5.js-web-editor/issues/1320)

### CODE REVIEW

**Comment by catarak** [comment]
I made a large feature merge ~1 wk ago and some of the docs have been updated. Would it be possible to get these in sync? Thank you!

**Comment by Phe0** [comment]
sure @catarak , I'll work on it

**Comment by Phe0** [comment]
@catarak I've updated the README translation and added translations for public_api_proposed.md and public_api.md

**Comment by catarak** [comment]
Amazing! So cool. Thank you! 

There's something funky happening with your git history here. It says you're trying to merge in 250+ commits? Did you rebase to get to up to date with the tip of master?

**Comment by Phe0** [comment]
> Amazing! So cool. Thank you!
> 
> There's something funky happening with your git history here. It says you're trying to merge in 250+ commits? Did you rebase to get to up to date with the tip of master?

Yes @catarak, I've rebased from the upstream master to get it up to date.

**Review by raclim — APPROVED** [review]
Merging this in :)

**Pull request merged**
