### PR TITLE
fixed preview background #1852

### LINKED ISSUE #1852: Set default iframe background color to white
#### Nature of issue?

- Found a bug

#### Details about the bug: 

Hi @catarak I have run into this as well, here is a screenshot of how text looks in the Preview window in Dark mode, but in High Contrast mode it is similar, defaulting to black text on a very dark background:
image
Here's an example of a sketch that displays this issue: https://editor.p5js.org/ml5/sketches/XCFPKqIKrt

_Originally posted by @leemark in https://github.com/processing/p5.js-web-editor/issues/1400#issuecomment-803752647_

@catarak: I think the issue here is that the iframe should have a default background color of white, as is the norm for websites.

### PR DESCRIPTION
**Pull request by Suhasshenoy**
Fixes #1852 

Changes:
As suggested by @nsmarino in [this comment](https://github.com/processing/p5.js-web-editor/issues/1852#issuecomment-835465957) , I have made the necessary change. I am attaching the screenshots after the changes.

Screenshot (27)
Screenshot (26)

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by juninhokaponne — APPROVED** [review]
Done!

**Comment by Suhasshenoy** [comment]
Hi @juninhokaponne. This PR is still waiting to be merged. Is there anything that I should do from my side?

**Comment by juninhokaponne** [comment]
@Suhasshenoy  I think it's necessary for a maintainer to review your changes and merge them, from your side it's everything okay.

**Comment by Suhasshenoy** [comment]
Hi @raclim. Can you please review this PR in your free time?

**Comment by raclim** [comment]
Thanks for all of your work on this! Honestly I'm not sure if the suggestion would be the best solution for handling this design-wise, and might want to give what the workaround would be more thought so I'm going to close this for now. I'm sorry that there wasn't much clarity about this, but would be welcome to other types of solutions!

**Pull request closed without merging**
