### PR TITLE
Align console text Fixes #711

### LINKED ISSUE #711: Icon/text misaligned in console messages
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version:  69.0.3497.92 (Official Build) (64-bit)
- Operating System:  Mac OSX 10.13.4
- Steps to reproduce this:

screen shot 2018-10-03 at 2 37 19 pm
screen shot 2018-10-03 at 2 37 25 pm
When you print messages to the Web Editor console, the text is not in line with the icon. it actually appears that the icon is centered, but the text is not.

### PR DESCRIPTION
**Pull request by pwjablonski**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

Hey!

Excited to contribute to this project.

This PR address #711.

In `Console.jsx` I added the PADDING property to the CONSOLE_FEED_SIZES. Without this property, the default is padding on this element is `2px 22px 2px 0`. I just changed the top padding to 4px. The choice for 4px was somewhat arbitrary but happy to take a more scientific approach.  See [console-feed styles](https://github.com/samdenty/console-feed/blob/6f5737a5fb7ba09f8670288ca08cfc7cda7a76c0/src/definitions/Styles.d.ts) your reference.

```
const CONSOLE_FEED_SIZES = {
      PADDING: '4px 22px 2px 0',
      ...
  };
```

### CODE REVIEW

**Comment by catarak** [comment]
@pwjablonski thanks for working on this! i think it's still misaligned, and appears the text is closer to the top than the bottom:
screen shot 2019-02-20 at 3 50 00 pm

**Comment by pwjablonski** [comment]
Hey @catarak! I made some updates I think it looks a bit better now. Let me know what you think.

screen shot 2019-02-23 at 3 46 52 pm

**Comment by catarak** [comment]
what broswer/os are you using? for me, i'm using Mac/Chrome and it's showing up like this:
screen shot 2019-02-25 at 12 36 21 pm

**Comment by pwjablonski** [comment]
Interesting - i'm using Mac/Chrome as well. I can dig into this some more!

**Pull request closed without merging**
