### PR TITLE
Feature sidebar toggle shortcut

### LINKED ISSUE #1282: Sidebar Toggle Shortcut
#### Nature of issue?
- New feature request

#### New feature details:
Vscode has shortcut for toggling sidebar, I think it would be better if we have the same feature here also.

### PR DESCRIPTION
**Pull request by shakti97**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

Fixes #1282

### CODE REVIEW

**Comment by shakti97** [comment]
@andrewn please have a look and suggest changes if required:)

**Comment by catarak** [comment]
I'm unsure about Command + B (see #1282), but regardless, you'll need to add this keyboard shortcut to the Keyboard Shortcuts Overlay as well.

**Comment by shakti97** [comment]
Thanks @catarak for the review , will add this to keyboard shortcut overlay and then get back to you

**Comment by shakti97** [comment]
hi @catarak , added sidebar toggle keyboard shortcut to the keyboard shortcut overlay

**Comment by catarak** [comment]
Thanks! Looks good.

**Pull request merged**
