### PR TITLE
Bug fix 1698

### LINKED ISSUE #1698: Too many warnings while compiling the code on a local machine.
#### Details about the bug: 

This is not actually a bug but a lot of warnings can be seen while running the code on a local machine. There are a lot of imports that are not used in the code. For example:-

image

in the given image you can clearly see that there are many unnecessary imports due to which there are a lot of warnings.

### PR DESCRIPTION
**Pull request by Kaushal-Dhungel**
RE: #1698 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #1698 `

### CODE REVIEW

**Comment by catarak** [comment]
Thanks for working on this! When I run `npm run lint` I'm still seeing some warnings—do you think you could fix them in this PR or do you want to open a new PR?

**Comment by Kaushal-Dhungel** [comment]
I don't know how to fix those warnings in this PR. I think I will create a new PR.

**Comment by catarak** [comment]
Upon looking at this closely, I think a lot of the changes you made in 47d144abd34d0453d20832bb6718f3c0d1bb3381 make sense, but a lot of the changes you made in 12259e2da7b89832c639e496bb5eaaeab82fe2a0 are unrelated to the line length and aren't necessary. In fact, these changes make your PR difficult to review. Would it be possible for you to change stuff that's only coming up in the lint warnings? It seems like you're using another linting configuration to make changes that are unnecessary.

**Comment by Kaushal-Dhungel** [comment]
This is due to the eslint prettier vscode extension I guess. I will fix that again. Plus there are some " X is assigned a value but never used " warnings. Should I remove them as well?? or are they necessary?? You can see the warnings in the image below:- 

image

**Comment by catarak** [comment]
That makes sense! Maybe the thing to do here is to add a prettier configuration to the project, which would help out with some of these errors (I believe there's an open issue about this? #1242) I'm happy to help with that. 

I do think it makes sense to remove "X is assigned a value but never used"—usually they end up removing dead code.

**Comment by Kaushal-Dhungel** [comment]
What should I do now?? Should I reformat all the remaining files using prettier eslint and add a config file?? or should I undo my second commit and make changes again without using the prettier eslint extension??  Please guide me.

**Comment by catarak** [comment]
> What should I do now?? Should I reformat all the remaining files using prettier eslint and add a config file?? or should I undo my second commit and make changes again without using the prettier eslint extension?? Please guide me.

I think you should undo the second commit and leave the rest for now. I'm going to investigate setting up prettier with eslint for this project in the very near future since it's been coming up a lot!

**Comment by Kaushal-Dhungel** [comment]
I spend some hours on the internet but still couldn't find the best way to undo a git commit. I am confused between git reset --hard and git rebase drop.  Some suggested not to rewrite the history using git rebase and some suggested not to use git reset as I have to push forcefully.  Sorry if I am taking too much time for this simple issue but I am confused once again.

**Comment by hydrosquall** [comment]
@Kaushal-Dhungel :

- `git reset --hard` would move the branch's head to whatever commit you were resetting to, which means everything that happens after that commit would be lost.
- `git rebase drop` would remove the second commit from history, and then apply the commits that happened after (they will have new hashes since history is different, but the code change would be similar assuming they didn't modify the files in the ignored commit)

Both of these options would lead to rewriting history on your branch, and require force pushing. To get some visual intuition about what `reset` , `rebase`, and `revert` would be doing, you may find https://onlywei.github.io/explain-git-with-d3/#revert helpful.

One very safe option if you're still unsure about how to navigate this would be to make a new branch off the latest `develop`, and `cherry-pick` *just* the first commit from this branch onto it. Then you could open a PR from that branch instead.

**Comment by Kaushal-Dhungel** [comment]
@hydrosquall thank you

**Comment by catarak** [comment]
Thank you for working on this! Ended up fixing this via #1744 since there hadn't been any updates on here.

**Pull request closed without merging**
