### PR TITLE
add ability to toggle line numbers to accessibility settings.  Fixes #1138

### LINKED ISSUE #1138: add ability to toggle line numbers to accessibility settings
#### Nature of issue?

- New feature request

#### New feature details:

Suggested by @sinabahram, this feature would add a setting under "Accessibility Settings" to toggle line numbers within the code editor. When using a screen reader, sometimes the line numbers can be distracting and don't indicate position in the same way as they do for sighted users.

### PR DESCRIPTION
**Pull request by RickBr0wn**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by catarak** [comment]
this looks great! i think the only thing that's missing is that the user model (`server/models/user.js`) needs a default value for `lineNumbers`.

**Comment by RickBr0wn** [comment]
Thank you for that. This has been my first PR so I'm a little shaky on the work flow, but I intend to make many more 👍🏻

**Comment by catarak** [comment]
no worries at all! it would be great to have you contribute more 😄

**Comment by catarak** [comment]
just tested this and all looks good to me! i'm gonna merge this in 🎉

**Comment by RickBr0wn** [comment]
Wow.. Who would of thought. 3 years ago I'd just come out of hospital and I needed a career change. I then met (via youTube) @shiffman, and began to watch his amazing coding train videos. And now 3 years on, I'm about to start applying for my first tech job, and I am going to actively contribute to the p5 community.

Thank you so much Daniel..

**Comment by catarak** [comment]
that's so awesome!!!!

**Pull request merged**
