### PR TITLE
Progressive Web Application: for installable offline capabilities

### LINKED ISSUE #2060: Turn the p5.js editor in a Progressive Web App (PWA) so it can be installed and used offline
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to the p5.js Editor?

PWAs can be installed on supporting operating systems (Android via Chromium-browsers, iOS using the "add to homescreen" feature, desktop OSs using Chromium-browsers, etc.).

Installing a PWA locally means it becomes just like a "native" app, making it easier and more natural to use for many people.
More importantly, PWAs can function offline, with the right Service Worker, meaning that people with low, unstable, spotty, paid internet access can continue learning to code or expressing themselves without needing to be connected.

#### New feature details

The feature is about adding the necessary PWA building blocks to https://editor.p5js.org/ in order to turn it into a PWA.
This means adding a web app manifest to describe what the app is about and how it integrates in the OS, and adding a service worker so it can work offline too.

Once the website is detected by supporting browsers as a PWA, users will be able to install it locally and use it as any other OS-native apps they have installed.

PWAs also come with special super powers like:

* Service Workers so they can use cached resources and work offline.
* File handling which could be used to save sketches on disk and register the PWA as a native handler for these files.
* Share target which could be used to received shared sketches.
* Protocol handling, which could be used to share sketches with each other.
* And more ...

### PR DESCRIPTION
**Pull request by dewanshDT**
Fixes #2060 

Changes:
I've added service worker and manifest file and icons of different sizes.
`config.prod.js`
`client/utils/sw.js`
`client/utils/registerServiceWorker.js`
`public/manifest.json`
`public/icon-192.png`
`public/icon-512.png`
`index.js`
`client/index.jsx`

libraries installed:
`workbox-webpack-plugin`
`workbox-core`
`workbox-precaching`
`workbox-window`

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by dewanshDT** [comment]
@raclim can you test this on your system because I'm getting errors when testing in production build, need you review on this

**Comment by raclim** [comment]
@dewanshDT Thanks for your work so far, will try to check in on this by the end of the week!

**Comment by raclim** [comment]
I'm really sorry that I didn't end up getting to this! Since it's been a while I'm going to close this for now, but please feel free to reopen this or create a new PR regarding this in the future.

**Comment by lindapaiste** [comment]
> I'm really sorry that I didn't end up getting to this! Since it's been a while I'm going to close this for now, but please feel free to reopen this or create a new PR regarding this in the future.

@raclim Can you point out anything with this PR that is incorrect?  The `package-lock.json` file needs to regenerated because it's been sitting for so long but that's a simple fix.  I feel that it's unfair to contributors to close their PRs without actually reviewing it, especially when this is a feature that we are still wanting to implement.

**Comment by raclim** [comment]
@lindapaiste That's true, thanks for pointing this out! I didn't realize I closed both the issue and PR without an explanation. 

I think I closed the issue because despite the benefits that PWAs provide, I wasn't sure anymore if turning the editor into one would be completely beneficial and might add more complexity/maintenance than they might be worth. Although PWAs can run offline, I think their offline capabilities are currently limited ([for example, I don't think PWAs have been fully supported on Apple, though it seems like it's been changing incrementally](https://brainhub.eu/library/pwa-on-ios)). Since it's limited, I thought they might be better for simpler apps/interactions versus the p5 editor, which is more complex and has folks who do use the advanced mobile capabilities on it (like the accelerometer, bluetooth, etc). I also personally feel like there isn't a strong need to distribute the editor to different platforms/devices, and can be achieved through alternative solutions if needed. 

I closed this PR with the issue as well, but I can give it a more thorough review since I did say I would 😅 but in terms of reopening/merging it I'm not too sure yet due to the reasons above! I could also be misinterpreting PWAs overall and the point of implementing this. I'm wondering what your thoughts would be on this as well!

**Pull request closed without merging**
