### PR TITLE
Fixes file saving problem

### LINKED ISSUE #470: Changes aren't saving
#### Nature of issue?

- [ X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Version 61.0.3163.100 (Official Build) (64-bit)
- Operating System: Mac OS 10.12.6 (16G29)
- Steps to reproduce this:
1. make a change in code
2. use keyboard shortcut cmd-s to save ("project saved"dialog appears)
3. reload page and change has disappeared.

#### New feature details:

### PR DESCRIPTION
**Pull request by shinytang6**
Before your pull request is reviewed and merged, make sure you

* [x] there are no linting errors -- `npm run lint`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master. If you're asked to make more changes make sure you rebase onto master then too!
* [x] pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

Thank you! Fixes #470 #419 #437 ;

### CODE REVIEW

**Comment by shinytang6** [comment]
@catarak l think l find where the problem lies

The steps to reproduce that:

1. open two identical projects on browser
2. make changes to one projects and **quickly** save it using **ctrl+s** (but you can't do that **too quickly**)
3. then you will see the project you changed seem to be saved(with the unsavedchange dot disappered, if exists, it means you press too quickly), but actually it is not saved.

The problems occurs because when you press ctrl+s, it triggers the `saveProject` :
[https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/project.js#L73](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/project.js#L73)

But at that time the changes are not detected because of debounce, so what uploads to the server is the unchanged file, see : 
[https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/Editor.jsx#L114](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/Editor.jsx#L114)

the difference between `quickly` and `too quickly` is whether 
[https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/project.js#L84](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/project.js#L84)
happens before [https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/Editor.jsx#L115](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/Editor.jsx#L115)

Hope l explain clearly :)

**Comment by catarak** [comment]
i'm not sure the right solution is to remove the debounce. if a user has 'auto-refresh' enabled, then the debounce keeps the sketch from updating every time a character changes and therefore crashing all of the time. maybe a better solution would be when a user hits 'play', the file updates before generating the preview?

**Comment by shinytang6** [comment]
>maybe a better solution would be when a user hits 'play', the file updates before generating the preview

@catarak   lt may still cause problem in some cases...
e.g. If after this situation happens, a user still makes a lot of changes and save many times, hiting `play` will lose all the changes as you say..

Maybe we can call `state.files` again and compare it with the `response.data.files`  
before [https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/project.js#L86](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/project.js#L86)

If error happens, they are different.... what do you think?

**Comment by catarak** [comment]
that's a good idea! maybe `setProject` shouldn't even be called there. the source of truth here should be what's in the CodeMirror editor unless a user has just opened a sketch.

**Comment by shinytang6** [comment]
That’s true, l will work on it soon！btw, can l ask are there some other ways you know/use to test ssl？

**Comment by catarak** [comment]
the directions in the readme are all i know—in production i'm using let's encrypt for the ssl certs, but i recently learned that ssl is also free if you use aws cloudfront.

**Comment by shinytang6** [comment]
l work on a new laptop today:) it seems that l made something wrong with git...Sorry for that o(╥﹏╥)o, close this and refer to #546 :)

**Comment by catarak** [comment]
all good!

**Pull request closed without merging**
