### PR TITLE
Fixes #1546 capture and display rejected promises

### LINKED ISSUE #1546: Web Editor can't capture and display errors for p5.js >= 1.0.0
#### Nature of issue?

- [x] Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 83.0.4103.116 
- Operating System: Ubuntu 18.04
- Steps to reproduce this bug:

For sketches running on p5 versions 0.10.2 and older , the editor is able to capture an error, highlight the line and display the error in the editor console perfectly.
image
It cannot do the same for sketches running on newer versions of p5 ( >= 1.0.0 ) as seen here:
https://editor.p5js.org/akshay.padte/sketches/2yX5Q5CeV

This is likely because the initialization code for p5 was [changed a bit](https://github.com/processing/p5.js/pull/4233/commits/dd9d2c85e82a938c77778750cc385cb246d8a942) in processing/p5.js#4233 ( just before 1.0.0 ) and it now runs inside a promise. Which also means that errors now happen inside a promise and would now be caught by `unhandledrejection` listener instead of `onerror`.

Also, since p5 0.6.0, several components of the FES report the line number of the error in the message. However since the editor concatenates the user-code into `srcdoc`, the line number reported by the FES is something like `about:srcdoc:56:3`
image

I was wondering if it's possible to fix this somehow. Maybe this belongs in an issue of its own.

### PR DESCRIPTION
**Pull request by ridait**
Fixes #1546 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #1546`

### CODE REVIEW

**Comment by catarak** [comment]
This is working great for me :) thank you!

**Comment by catarak** [comment]
@ridait I was confused as to why this wasn't showing up on `develop`, and i realized you changed the base branch to `master`. I'm going to revert this PR—can you please open a new one with the base branch as develop? Thank you!

**Comment by ridait** [comment]
@catarak I am sorry for the inconvenience, a new PR is created based on `develop` branch.

**Comment by catarak** [comment]
@ridait no worries! It's confusing that I haven't deleted the `master` branch.

**Pull request merged**
