### PR TITLE
Changed color of sketch lines to theme color

### PR DESCRIPTION
**Pull request by Noorain464**
Fixes #issue-number
The color of sketch link in sketches table should be changed to theme color when hovered https://github.com/processing/p5.js-web-editor/issues/2943

Changes:

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by SableRaf** [comment]
Hi @Noorain464 and welcome to the p5.js-web-editor repository! 

Could you please add details about the issue you're fixing? This will help us understand your changes better.

**Comment by Noorain464** [comment]
I'm sorry, this is the issue I've solved
The color of sketch link in sketches table should be changed to theme color when hovered #2943
image

**Review by Noorain464 — COMMENTED** [review]
Okay Done.

**Review by raclim — APPROVED** [review]
Thanks for your work on this! I'm a little concerned about inconsistencies with how links should appear in the editor, but I think this is an improvement from what it currently looks like, I feel like this is good for now!

A few other points to note: 
- Although you included a screenshot, the image doesn't seem to reflect the specific changes. I added in a few images below of what it would ideally look like (i.e the changes in different themes). It would be great if you could add these types of details in future PRs!
Screenshot 2024-08-12 at 10 04 37 AM
Screenshot 2024-08-12 at 10 04 52 AM

- I removed some changes to the `previewServer.js` file, which I noticed is in another pull request you submitted. Ideally, we also would like to keep changes for issues separated in each pull request.

Thanks!

**Pull request merged**
