### PR TITLE
update default template p5.js to 1.0.1 (Fixes #1396)

### LINKED ISSUE #1396: Upgrade default template to p5.js 1.0.0
#### Nature of issue?
- New feature request

#### Feature enhancement details:
Upgrade default template to p5.js 1.0.0 (from 0.10.2)

Currently creating a new sketch points to p5.js 0.10.2.At present, the reference is out of sync with the editor. For example, that Vector.reflect is listed in the reference, but not available through the web editor. For an example support discussion, see:
https://discourse.processing.org/t/uncaught-typeerror-velocity-reflect-is-not-a-function/19402?u=jeremydouglass

### PR DESCRIPTION
**Pull request by jeremydouglass**
Changes the p5.js version used by the web editor to 1.0.1.

(Fixes #1396)

I have verified that this pull request:

* [x] has no linting errors
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by montoyamoraga** [comment]
hey @catarak can we merge this awesome commit?
one of my p5.js sketches was broken because of it loading the old 0.10.2 instead of 1.0.0
and 1.0.0 fixed it yay, go p5.js, thank you @jeremydouglass for spotting this, go team ~

**Comment by hellonearthis** [comment]
I was just looking to download the 1.0.0 locally and cloudflare is providing the wrong version.
image

So I looked in the https://github.com/processing/p5.js/tree/master/lib expecting it to be there.
image

I downloaded the p5 repo and searched for p5*js and p5.js and it's not there too

I'm guessing there is something buggy going on with the build system and post an issue

**Comment by jeremydouglass** [comment]
Thank you for the heads up. I think you can just link to / from this PR on your actual issue page -- here: https://github.com/processing/p5.js/issues/4485

Bad cloudflare confiig matters to this PR, but it isn't a web-editor issue.

**Comment by montoyamoraga** [comment]
oops, there is something weird on, the default p5.js library that i got from the web editor is this:
[https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js](https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js)
and then i tried to fix it manually to 
[https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/p5.js](https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/p5.js)

the first one says it's /*! p5.js v0.10.2 October 14, 2019 */
the second one says it's /*! p5.js v0.10.2 February 29, 2020 */

weird ~

**Comment by jeremydouglass** [comment]
Yeah, I'm getting v0.10.2 February 29 every time. But as I said, this isn't a web editor issue -- please discuss here: processing/p5.js#4485

**Comment by jeremydouglass** [comment]
This PR is temporarily blocked by #4336 / #4485 -- it will be updated to point to the correct 1.0.x once it is released.

In the meantime, the web editor is still out of sync with the public reference.

**Comment by catarak** [comment]
thanks for looking into this @jeremydouglass! i'll merge this in as soon as the cdnjs issue is fixed.

**Comment by jeremydouglass** [comment]
Thank you @catarak!

This PR will be unblocked on the next p5.js release -- 1.0.1(?). I am speculatively updating this PR now to point to 1.0.1 so that this can be merged immediately whenever that release happens.

If p5.js goes to 1.0.2 or 1.1 or something else instead then I can update this PR again before merging.

**Comment by joshuahhh** [comment]
I noticed that the CDN URLs are also listed in https://github.com/processing/p5.js-web-editor/blob/master/server/domain-objects/createDefaultFiles.js. Does that file also have to be updated? (Is it still in use?)

**Comment by jeremydouglass** [comment]
> I noticed that the CDN URLs are also listed in https://github.com/processing/p5.js-web-editor/blob/master/server/domain-objects/createDefaultFiles.js. Does that file also have to be updated? (Is it still in use?)

Good catch. I based the changes in this PR on the previous version bump, which did not touch that file:

03fde3f0b5

... not sure if the core team uses it, but it seems like it couldn't _hurt_ to bring it up to date.

**Comment by andrewn** [comment]
> > I noticed that the CDN URLs are also listed in https://github.com/processing/p5.js-web-editor/blob/master/server/domain-objects/createDefaultFiles.js. Does that file also have to be updated? (Is it still in use?)
> 
> Good catch. I based the changes in this PR on the previous version bump, which did not touch that file:
> 
> [03fde3f](https://github.com/processing/p5.js-web-editor/commit/03fde3f0b561c7a8364d18a13bf06b554da84865)
> 
> ... not sure if the core team uses it, but it seems like it couldn't _hurt_ to bring it up to date.

`createDefaultFiles.js` is used when a new sketch is created via the new public API. If the user doesn't specify an HTML or CSS file, then that template is used to create them. So thanks for updating it also!

I created  #1423 to track having the default template defined in one place to make future updates easier.

**Pull request merged**
