### PR TITLE
Feature :- Download Collection

### LINKED ISSUE #273: Download Collections as zip
Once #43 is implemented, it would be nice to be able to download a collection as a zip. Then, for example, a teacher could easily upload all of the files to Github.

### PR DESCRIPTION
**Pull request by MohdImran001**
Fixes #273 

Hi @catarak, I have completed this feature and I am eagerly waiting for your valuable feedback.

### CODE REVIEW

**Comment by MohdImran001** [comment]
Hi @catarak, please review this PR. I am eagerly waiting for your valuable feedback.

**Comment by jht1493-gmail** [comment]
Hi @MohdImran001 and @catarak,
What can be done to help move this feature along?
I have finished teach a course ([NYU-ITP ICM](https://github.com/ITPNYU/ICM-2020-Media/wiki/Homework-John-Henry)) and would  like to download all my sketches/collections.
Can I run this feature in a dev build?
I've forked the repo and setup a local build, setup a GitHub client id for .env, but don't see the login option in web editor.

**Comment by catarak** [comment]
@jht1493 sorry that I haven't had a chance to review this! You could run this locally, but you wouldn't have access to the production database. Before it's reviewed/merged in, I could run this for you if you need this—you can email me at my NYU email to coordinate!

**Comment by MohdImran001** [comment]
Hey @catarak, it would be great if you could, quickly look at the code and leave some feedback about it.

**Comment by jht1493-gmail** [comment]
Hi Cassie,

I can’t find your nyu email
My nyu email is on this page:
https://github.com/ITPNYU/ICM-2020-Code/blob/master/sections/01_JohnHenry.md

My collections I would down load:
https://editor.p5js.org/jht1493/collections

Would prefer access to my sketches in dev mode, would like to explore more fluid working back and forth  between web editor and personal github repo.

-john-henry

**Comment by catarak** [comment]
I'm currently trying to close pull requests, and I think this one is close! It's working great for me. One thing is that rather than adding the library `request`, I would like to use one that's already in the project, `axios`.

**Comment by raclim** [comment]
Thank you so much for taking the time to contribute to this issue—I'm sorry we couldn't get to your work in time! Since some time has passed I'm going to close this for now, but please feel free to reopen this or work on this again, thanks!

**Pull request closed without merging**
