### PR TITLE
:sparkles: add toast to MobileIDEView

### LINKED ISSUE #1596: Save Sketch Toast on Mobile
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

Currently, the mobile editor can save, but it's missing the toast notification. This is because the `<Toast />` component is missing on `<MobileIDEView />`

### PR DESCRIPTION
**Pull request by ghalestrilo**
Fixes #1596

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by catarak** [comment]
Looking great 😄 What would you think about placing the toast under the header? I don't know how I feel about it blocking the title. Maybe the text could also be smaller on mobile?

**Comment by ghalestrilo** [comment]
Sure! I did it, and it does look better, but I wanna hear your thoughts on this:

1. It still covers the first two lines of code
2. Mobile apps usually have a pop-up banner above the header, to indicate lack of connectivity, or similar infrequent info. I was thinking of this as an alternative?

**Comment by catarak** [comment]
> Sure! I did it, and it does look better.

I agree it does look better! Also agree that it is annoying that it covers the first two lines of code.

> 2. Mobile apps usually have a pop-up banner above the header, to indicate lack of connectivity, or similar infrequent info. I was thinking of this as an alternative?

Do you have some examples we could use as a visual reference?

**Comment by ghalestrilo** [comment]
I thought of doing something like [this](https://css-tricks.com/pop-from-top-notification/), except pushing everything down a bit. In hindsight, not a brilliant idea :^)
I've seen a couple of apps placing the toast to the bottom, it's an alternative. Tell me which option feels best, and we'll go from there
image

edit.: changed the example - it's best not to hide the bottom bar with the toast

**Comment by catarak** [comment]
I like how it looks at the bottom! It feels less intrusive, I like that it's closer to reach with your thumb so that you can get rid of it if you want to, but it also doesn't feel like it's in a location that it won't be noticed.

**Comment by ghalestrilo** [comment]
I think it looks nicer now, check it out!

**Comment by catarak** [comment]
For me, this is what the toast looks like:
Screen Shot 2020-09-11 at 6 06 19 PM

**Comment by ghalestrilo** [comment]
lord, I forgot a css rule. definitely not a design choice!

**Review by catarak — APPROVED** [review]
Made one last change so that the toast doesn't sit right up against the edges, which looked strange with the border radius. Now this is ready to be merged in!

**Pull request merged**
