### PR TITLE
Add Promotion for 2023 Fundraiser

### LINKED ISSUE #2713: Adding Content to Promote 2023 PF Fundraiser
### Increasing Access

Promoting the fundraiser helps the Processing Foundation and its team continue to support its software, contributors, and overall community!

### Feature request details

- Add 'Donate' to the About Section. 
- Add a Link to the Navigation that opens a Modal describing the Fundraiser. 

This addition is due by 12/15.

### PR DESCRIPTION
**Pull request by raclim**
Fixes #2713 

### Overall Changes

- 'Donate' link added to `About.jsx`. 
- Fundraiser text added to `translations/locales/en-US/translations.json`.
- Link in Nav to Open a Fundraiser Modal
    - Adds `FundraiserSection()` to `client/modules/IDE/components/Header/Nav.jsx`.
    - Updates Styling in `client/styles/components/_nav.scss`.
    - Responsiveness added to `client/modules/IDE/components/Header/MobileNav.jsx`.
    - Updates Snapshots in `client/modules/IDE/components/Header/__snapshots__/Nav.unit.test.jsx.snap`.
- Fundraiser Modal
    - Adds `FundraiserModal.jsx` to `client/modules/IDE/components`. This is also added to `IDEOVerlays.jsx`
    - Adds Actions, Constants, and Reducers to open and close the Fundraiser Modal. 
    - Adds the Processing Foundation logo to `client/images`.
    - Adds Styling in `client/styles/abstracts/_variables.scss`, `client/styles/components/_fundraiser.scss`, and `client/styles/main.scss`. 

**Other Notes**
- The changes in this PR are intended to be temporary, and will be reverted once the fundraiser is over. 
- This PR is should be merged by 12/15, which is the fundraiser's launch date. It's a bit soon, so open to making any needed updates even if they are given after this date!
- This PR may change as I continue to receive feedback on the design. 
- _I initially intended to work off of the `release` branch so these updates could be deployed separately from the ones in the MINOR release. I realized near the end though that I ended up working off of `develop` 😭, so the next MINOR release will also probably be when this is deployed. The next one will probably be around the week of 01/08, since PF will be closed on 12/25-01/05._

#### What it Looks Like 
Screenshot of Fundraiser Link in the Navigation
Screenshot of Opened Fundraiser Modal

https://github.com/processing/p5.js-web-editor/assets/43053081/6788bc8c-9dab-415c-95a4-c701229181b8

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by PiyushChandra17 — APPROVED** [review]
Looks good to me 👍

**Comment by lindapaiste** [comment]
The images/video look good but the text in the header won’t show up at all on the mobile version.  We should think about how we can integrate it there.

If the git stuff is worth fixing then you can check out the release branch and then cherry-pick these commits onto it.  Pick them from this branch you created onto some other branch off of release.  You’d have to create a new PR though.

**Comment by raclim** [comment]
Thanks for pointing out the mobile version! I had it in mind but ultimately forgot about it at some point 😅 I'm not sure where the text in the header would fit in the layout. Maybe a direct link to it could be placed in the dropdown menu? I'll try some stuff out and update this PR with the mobile changes. 

Hmm for the git stuff, looking through the commits I feel like there might be a good number of them that might need to be cherry-picked. I'm thinking it might be okay to forgo it this time, but I'm also open to going through with it if there's a strong preference for it.

**Comment by raclim** [comment]
I just added in the mobile elements (screenshots of it are below)! I moved the original header text into the navigational dropdown menu, which ended up widening it quite a bit. I don't think this greatly affects anything, but I'm not sure if this implementing these kinds of changes should be avoided. 

Screenshot of Navigation for Mobile Version
Screenshot of Fundraiser Banner in the Mobile Version

https://github.com/processing/p5.js-web-editor/assets/43053081/1443816b-6f0d-4c73-8a34-19a9bdf171bf

**Comment by raclim** [comment]
There's a lot of changes here, but I'm going to try to get this out for today's fundraiser launch! Thanks again everyone for your input, and please let me know know if anyone has any further suggestions!

**Pull request merged**
