### PR TITLE
Added Placeholder for Clearer User Guidance in Console Input Componen…

### PR DESCRIPTION
**Pull request by gauravsingh94**
…t #2644

Fixes #issue-number

Changes:
Added Placeholder for Clearer User Guidance in Console Input Component

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by gauravsingh94** [comment]
Final Output will look like this:

[Screencast from 2023-11-28 00-14-57.webm](https://github.com/processing/p5.js-web-editor/assets/99260988/e089e704-94de-4d30-b17b-cb4b0ea6f9cc)

**Comment by lindapaiste** [comment]
I think this is a good idea.  We'll want the placeholder text to be something that comes from the `translation.json` files so that it's not always in English.

I wanted to see if there is a way to set a placeholder natively in CodeMirror, rather than displaying a `div` on top of it, and there is!  https://codemirror.net/5/demo/placeholder.html

**Comment by gauravsingh94** [comment]
@lindapaiste  Ok i will update this.

**Comment by gauravsingh94** [comment]
@lindapaiste  I have made changes according to your earlier instructions.
Please provide feedback on these changes.

**Comment by gauravsingh94** [comment]
Now the output is looking like this

[Screencast from 2023-11-29 22-19-19.webm](https://github.com/processing/p5.js-web-editor/assets/99260988/417044f2-f113-4b41-981d-fb389dfb9df5)

**Pull request closed without merging**
