### PR TITLE
fixed scroll

### LINKED ISSUE #2905: Not able to scroll the Privacy policy, Terms of use, and Code of conduct pages in mobile view
### p5.js version

2.10.2

### What is your operating system?

None

### Web browser and version

_No response_

### Actual Behavior

Cannot scroll the Privacy policy, Terms of use, and Code of conduct pages in mobile view

https://github.com/processing/p5.js-web-editor/assets/115213858/baf4d282-b183-4ad6-8b60-dab59b0a15e4

### Expected Behavior

The Privacy Policy, Terms of Use, and Code of Conduct pages should be scrolled to the end.

### Steps:
1. Open mobile view.
2. Go to about section then to Privacy Policy or Terms of Use or Code of Conduct page.
3. Try to scroll through the page.

### PR DESCRIPTION
**Pull request by rahulrangers**
Fixes #2905 

Changes:

@lindapaiste I have verified that this pull request:

https://github.com/processing/p5.js-web-editor/assets/127782777/87a45f28-1d4f-41cb-995d-454acc19b9f4

- [x] has no linting errors (`npm run lint`)
- [x] has no test errors (`npm run test`)
- [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
- [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by PiyushChandra17 — COMMENTED** [review]
👍

**Comment by raclim** [comment]
Thanks for your work on this! 

I think we might want to go with #2883 since it was created first and looks a bit closer to what we're looking for, so I'm going to close this PR for now. However, please feel free to check out our other issues or revisit this PR if another solution comes up!

**Comment by raclim** [comment]
Sorry about that, after taking a closer look I realized I didn't carefully look at which particular files were being changed! I think this PR is still good for review!

**Review by raclim — APPROVED** [review]
Thanks again for your work on this and I apologize for closing this earlier! After testing this out I think this looks good to go!

**Comment by lindapaiste** [comment]
@raclim the `min-height: 100vh` which was removed in this PR was previously put in to prevent jumpiness on the desktop view when the `fetch` for the `.md` file finishes and the content comes in.  Setting `min-height: 100vh` forces the scrollbar to be present at all times so that it won't disappear and reappear.  You can find the issues.  IMO we want to keep that when on desktop, but apply it conditionally using a media query.  That's what I meant by [my suggestion](https://github.com/processing/p5.js-web-editor/issues/2905#issuecomment-1892677840) (emphasis added)

> There's probably a few valid ways to fix this, with differences in what content is fixed to the top. One way would be in the `PolicyContainer`. We would add an `overflow: auto` and remove the `min-height: 100vh;` **_when in the mobile view._**

**Comment by raclim** [comment]
@lindapaiste Ohh I see, sorry I did notice the distinction for only the mobile view but didn't realize the reasoning behind it and assumed it seemed okay. I'll reopen the issue and can update this PR with the needed changes!

**Comment by beccyabraham** [comment]
It looks like those pages still don't scroll all the way down on mobile; on the Privacy Policy page, I can't see the "Contact information" section

**Pull request merged**
