### PR TITLE
Fixes overflow problem in overlays

### LINKED ISSUE #1654: Bottom Padding issue in Keyboard Shortcuts model
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System:  Windows 10
- Steps to reproduce this bug:
 1) Go to **Help** menu
 2) Select **Keyboard Shortcuts**
 3) Check the bottom padding of Keyboard Shortcuts model. Also try to resize the browser size and you will see the padding issue more clearly

Screenshot (14)

### PR DESCRIPTION
**Pull request by sagar-joshi**
Fixes #1654 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by plxity — DISMISSED** [review]
LGTM 👍

**Comment by catarak** [comment]
Your fix worked, but I think it makes sense to scroll the content rather than the header+content. Check out my changes and let me know what you think!

**Comment by sagar-joshi** [comment]
Yes agreed !

**Review by catarak — APPROVED** [review]
thanks for your help on this!

**Pull request merged**
