### PR TITLE
Portuguese Translation

### PR DESCRIPTION
**Pull request by felipesanchezz**
Fixes #issue-number

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by felipesanchezz** [comment]
This is  full Portuguese translation. Many people in Brazil work with JavaScript projects and editors, and I've been noticing a huge lack of properly translated ones. I really like and frequently use p5.js, and I think a translation will be very much appreciated by the Portuguese speakers community. I'm half Brazilian, so I'm legit lol. This is my first PR btw.

**Comment by byfelipesanchez** [comment]
there's some sort of running error, I'm not sure what is means

image

**Comment by catarak** [comment]
@byfelipesanchez this is so awesome and thank you for working on this!!! I can't wait to merge this in. Have you had anyone review your translation? Do you know of anyone who could review it? You can either send them your JSON file or you can use the staging link for this PR: [app-tedc41c-p5-js-web-editor.releaseapp.io](https://app-tedc41c-p5-js-web-editor.releaseapp.io)

Going to tag @ghalestrilo just in case he has time to look this over :)

**Comment by felipesanchezz** [comment]
> 
> 
> @byfelipesanchez this is so awesome and thank you for working on this!!! I can't wait to merge this in. Have you had anyone review your translation? Do you know of anyone who could review it? You can either send them your JSON file or you can use the staging link for this PR: [app-tedc41c-p5-js-web-editor.releaseapp.io](https://app-tedc41c-p5-js-web-editor.releaseapp.io)
> 
> Going to tag @ghalestrilo just in case he has time to look this over :)

I got a couple of Brazilian friends to review it. Is that enough? @catarak

**Comment by catarak** [comment]
@byfelipesanchez yes! that's perfect. obviously updates can be made via PRs in the future but I just wanted to make sure the translation is in a good place now!

**Review by catarak — APPROVED** [review]

**Comment by felipesanchezz** [comment]
> 
> 
> @byfelipesanchez yes! that's perfect. obviously updates can be made via PRs in the future but I just wanted to make sure the translation is in a good place now!

got you! Thanks for checking it! :)

**Pull request merged**
