### PR TITLE
Added translations to codemirror-search

### LINKED ISSUE #1588: Translation for Code Mirror Search
- New feature request

At this point, there are no translations for the Find functionality because it is a particular component in the sense that usual approaches used through the translation effort don't work. 
https://github.com/processing/p5.js-web-editor/blob/develop/client/utils/codemirror-search.js
I don't know how to expose it as a React Component, or if that is even required, and could be translated using i18n t functions only.

### PR DESCRIPTION
**Pull request by SundeepChand**
Fixes #1588 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

I have tried to pass the translations by directly importing the `i18n` into `codemirror-search.js`. Please check this out (I have added translation for find on line no 238) & let me know if this approach is fine. If its fine, then I will update rest of the words.

### CODE REVIEW

**Comment by catarak** [comment]
Thanks for working on this! I think there's some missing translations here:
- The input placeholder "Find in files" is not translated
- None of the ARIA labels are translated (the search options, Next, Previous, and Close).

**Comment by oruburos** [comment]
@catarak Sorry, have not had time to test it myself, but I think that @SundeepChand only want to test if the i8n t  translation function works testing just one label, and if it works then an additional PR could be created.

**Comment by catarak** [comment]
> @catarak Sorry, have not had time to test it myself, but I think that @SundeepChand only want to test if the i8n t translation function works testing just one label, and if it works then an additional PR could be created.

Thank you for reading this PR more closely than me 😄  you are right!

**Comment by SundeepChand** [comment]
> @catarak Sorry, have not had time to test it myself, but I think that @SundeepChand only want to test if the i8n t translation function works testing just one label, and if it works then an additional PR could be created.

Thanks @oruburos, I had meant this only. By the way, @catarak  I have changed all the labels now. Please check this out. And please verify the Spanish words as well.

**Comment by SundeepChand** [comment]
Hello @catarak! I'm closing this pull request as #1588 has been fixed by #1552.

**Pull request closed without merging**
