### PR TITLE
Moved fileNode to be a functional component

### PR DESCRIPTION
**Pull request by yosuva-rv**
Ref processing #2358 

Changes:
   Moved fileNode to be a functional component.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by lindapaiste — APPROVED** [review]
Looks good.  There is definitely more cleanup which can be done in this component, but you've handled the function component conversion well.

**Comment by yosuva-rv** [comment]
> Looks good. There is definitely more cleanup which can be done in this component, but you've handled the function component conversion well.

Thanks @lindapaiste

**Comment by lindapaiste** [comment]
This PR will have the problem explained in this comment: https://github.com/processing/p5.js-web-editor/issues/2524#issuecomment-1848825615

**Comment by raclim** [comment]
Thanks for your work on this! Since it's been a while since this PR was submitted, some of its contents have fallen quite out of sync with the current `develop` branch so I'm going to close this for now. I'm sorry that we couldn't get this in, but please feel free to reopen this PR with any updates or check out our other issues!

**Pull request closed without merging**
