### PR TITLE
Missing ARIA label NavBasic, Removing Italian entry from Language Dropdown, Changing translation for Asset

### PR DESCRIPTION
**Pull request by oruburos**
Addresses some points in discussion  #1509 
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named

This PR addresses :

* Missing ARIA label in NavBasic
* Removing Italian entry from Language Dropdown (it was there to test fallback funcitonality)
* Changing translation for Asset (Recurso in Spanish https://github.com/processing/p5.js-web-editor/issues/1509#issuecomment-680303467 )
* Remove unused imports regarding 18n in some files.

### CODE REVIEW

**Comment by oruburos** [comment]
@andrewn Can you have a look at this, please? Conflicts have been solved and it's up to date.

**Comment by andrewn** [comment]
@oruburos When I load my user's assets page (http://localhost:8000/andrewn/assets), I see a blank screen.

The Web Inspector's console tab shows the following error:

```
Uncaught TypeError: this.props.t is not a function
AssetList.jsx:89
```

Can you take a look please?

**Comment by catarak** [comment]
i'm really excited to get this in! do y'all think this is the last PR before i can turn the spanish translation on in production?

**Comment by oruburos** [comment]
@andrewn  Can you have a look at this, please?

**Review by andrewn — APPROVED** [review]
Great work!

**Comment by oruburos** [comment]
@catarak there is work to do to have a complete translation, specifically the issues mentioned in #1584 and #1587, but I think that in the current state is helpful.

**Comment by andrewn** [comment]
@catarak My feeling is that we can turn this on and address the two other issues soon.

**Comment by catarak** [comment]
> @catarak My feeling is that we can turn this on and address the two other issues soon.

Makes sense to me! I think it's okay to have the translation mostly done and to start getting feedback from users.

**Pull request merged**
