### PR TITLE
New Design for About

### PR DESCRIPTION
**Pull request by yining1023**
New design for about page, and Happy New Year! 🌸
screen shot 2016-12-31 at 11 42 54 am

### CODE REVIEW

**Comment by catarak** [comment]
i am slow and catching up on everything, this looks amazing!

**Comment by catarak** [comment]
One small thing: you don't need to include a smaller play button, you can actually change the size of an SVG in CSS:
```scss
.about__play-video-button svg {
  width: #{11 / $base-font-size}rem;
  height: #{11 / $base-font-size}rem;
}
```

**Comment by yining1023** [comment]
haha, you are right. I didn't know I could just change its CSS. Just pushed the changes!

**Comment by shiffman** [comment]
I am just noticing this now, fantastic work!!!

**Pull request merged**
