### PR TITLE
Updated `client/utils/javascript.js` to reflect changes in the CodeMirror's repository

### LINKED ISSUE #773: Bug with template string code formatting
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 
After trying the text editor with a larger project I have written, I discovered the following: when using a template string of the form

```text(`Lives ${playerLives}\nStreak ${round(streak*10)/10}`, 0, 0); ```

(used to display game information in `draw()`) the code after it is regarded as part of the template string, or in other terms:

image

Everything after this line turns turqoise.

Now, to be clear, this is fully functional code without any errors whatsoever, it is just a flaw in the editor's formatting system

- Web browser and version: Chrome 70.0.3538.110
- Operating System: Windows 10
- Steps to reproduce this: Open [this](https://editor.p5js.org/kleinesfilmroellchen/sketches/BkE1_Lh0X) Editor page and file sketch.js or create similar code to what is shown above.

### PR DESCRIPTION
**Pull request by LakshSingla**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`) (`eslint-disable` was used as it is an external file)
* [ ] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

[WIP] To fix #773 and update the `client/utils/javascript.js`

### CODE REVIEW

**Comment by LakshSingla** [comment]
@catarak Scope of this PR is to:-
[x] Update the code in `p5-javascript` to the latest version in CM's repo
[ ] Fix template bug formatting #773

I could use some help with the latter one. I am currently trying to go through CMs codebase and Docs to see how to extend the framework.

**Comment by LakshSingla** [comment]
I exactly did that and it breaks up on adding `p5-function` type

**Comment by LakshSingla** [comment]
@catarak Thanks for helping !!! The function breaks on adding p5 syntax. I just realized the issue. P5 keywords are defined of type `p5-function` and `p5-variable` respectively, although their type actually is `variable`. This caused errors in parsing the Javascript. The style to be applied would be `p5-function` and `p5-variable` although the type would be `variable`. I just tested it and it works. Lemme check with some more test cases and send a PR by tonight. Hopefully it will be solved. :smile:

**Comment by LakshSingla** [comment]
Here is the preview after making the above changes. Fixes #773 
screenshot from 2019-01-25 19-17-09

**Comment by catarak** [comment]
this seems to be working for me! i'm gonna merge it ✨

**Pull request merged**
