### PR TITLE
Issue-#2923 added test for the Account Form.

### PR DESCRIPTION
**Pull request by gauravsingh94**
Ref #2923

Changes:
Added the test for AccountForm.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by gauravsingh94** [comment]
@lindapaiste 

I have added the test for Account from please review it. if these test feel good to you then i started to write for the other component as well.

In the `AccountForm` test  i have added the test for :

- The form component renders correctly with the initial user values.
- clicking on `save all settings` will call the dispatch the `updateSettings`.
- when out data is submitting in this period our `save all settings ` button must be `disabled`.



image

**Review by lindapaiste — DISMISSED** [review]
These are very good tests! 👍 

I'm often not a fan of mocking because it's testing a fake behavior and not the real behavior.  But this is a case where it makes sense because I don't think that our dev/test setup has actual user accounts associated with it.  Maybe it does?  We should look into that.  When it comes to testing the login screen it would be cool if we could try submitting a wrong password and verify that it fails vs a correct password and verify that it succeeds.

**Comment by gauravsingh94** [comment]
@lindapaiste 
Added the tests for the LoginForm.

**Comment by gauravsingh94** [comment]
@lindapaiste 
Added the test for the `NewPasswordForm`.

image

**Comment by khanniie** [comment]
thanks, these are great tests! : ) lgtm to me overall but you will probably have to move the test locations as it looks like the files have moved locations a little bit

**Review by raclim — APPROVED** [review]

**Pull request merged**
