### PR TITLE
fixed Project og title added in ssr

### LINKED ISSUE #2177: Improve OG title for linked p5.js sketches
### **Problem description** 
When sharing a p5.js sketch from the web editor on social media or other websites, the OG title of the resulting webpage only says "p5.js Web Editor". This makes it difficult to distinguish between different linked sketches or know what the sketch is about.

### **Proposed solution** 
Update the OG title to include the title of the sketch and the name of the author, followed by "p5.js Web Editor". For example, the OG title could be "My Sketch by Username - p5.js Web Editor". This would improve the discoverability and sharing of p5.js sketches and help to promote the creators of these sketches.

### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to the p5.js Editor?

The new feature would help increase access to the p5.js Editor by making it easier for users to share and promote their p5.js sketches on social media and other websites. By improving the discoverability and sharing of p5.js sketches, more people will be exposed to the capabilities of p5.js, and may be inspired to try it out for themselves.

### **Additional information** 
Screenshot from the Processing Foundation forum showing the current behavior is attached below

image

### PR DESCRIPTION
**Pull request by Rishab87**
Fixes #2177

Changes:
modified ssr to display og title

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by Rishab87** [comment]
Hi @raclim ,

I wanted to follow up on my previous comment regarding the issue #2177. It’s been a few days, and I wanted to check if there are any updates or if additional information is needed from my side. 

Thanks for your time and help!

Best,  
Rishab

**Comment by raclim** [comment]
Hi @Rishab87, thanks for your work on this! 

I think although the changes here do work, I would double check that the changes to the `renderIndex()` function are compatible with where it's called in other parts of the codebase, especially since it seems to be called several times. 

I think a previously closed PR for this issue (https://github.com/processing/p5.js-web-editor/pull/2181/files#diff-b4206729ee1785504afa67759156d1d5dcaaa104c981f072f6e2538f0f2ff1d5), does create a solution for this by creating a separate function to render the index specifically for a project. One approach you could take is to reference this PR without including the portions that reformatted the files.

**Comment by Rishab87** [comment]
Thanks for your time and help @raclim.

I have added a separate `renderProjectIndex(username, projectName)` function. Please do tell if I need to do anything else.

**Comment by Rishab87** [comment]
Hi @raclim ,

I wanted to follow up on my previous commit regarding the issue #2177. It’s been a few days again , do tell if you need any additional info from my side!

**Review by raclim — APPROVED** [review]
Thanks for much for your patience on this—sometimes it might take a moment to review PRs depending on what's happening with the project! 

I went ahead with pushing some changes to this PR after noticing that some of the non-user project pages would crash on loading. It seems like this might be happening because the `sendHtml()` function in `server/views/index.js` was changed to expect an object rather than a boolean (which is how it's set up in other places where `sendHtml()` is called). 

To keep this consistent, I changed back the function to accept a boolean and added a new `getProjectForUser()` method in the controller to retrieve the project's name in the `/:username/sketches/:project_id` route. I did this to try to ensure that these changes don't affect the rest of the app while also trying to maintain your original work as much as possible. 

I think another potential change that could be added in finding a way to consolidate the `renderIndex()` and `renderProjectIndex()` functions in `server/views/index.js` since they're mostly doing the same thing, but I feel like it's okay to keep it for now and to refactor it later down the line!

I'm sorry that I ended up changing things around a bit—please feel free to create a new PR with any additional changes that you'd like to make here! Otherwise, thanks again for your work on this and I'm going to merge this in!

**Comment by raclim** [comment]
Here are also some screenshots I have after testing it on Tumblr for both the user's sketch and non-sketch pages: 

User's Sketch: 
Screenshot 2024-07-09 at 2 31 07 PM

User's Collections List Page:
Screenshot 2024-07-09 at 2 31 27 PM

**Comment by Rishab87** [comment]
Thanks for your feedback , I'm really sorry to hear that you had to make a few changes as my code was breaking few parts of the application , I will be more careful next time while testing the application, thank you for your time and help. I'll surely try to improve this further and merge both the functions into one.

**Comment by raclim** [comment]
No worries @Rishab87! I went ahead with implementing some of these changes to get this out since this issue's been around for a while 😅 I really appreciate you staying on top of this!

**Pull request merged**
