### PR TITLE
Converted 'About Block' into all available language

### LINKED ISSUE #2692: Translating the 'About Block' into all possible type of language
### Increasing Access

288120737-9ba54ab8-172d-41e9-b75f-b02bd2f77f9f

If we can change the about block into all the possible language available, it will be very easy for a Native Speaker of respective Languages, to navigate over to social media and other links.

### Feature request details

Change full 'About Block' into all possible Language.

### PR DESCRIPTION
**Pull request by swrno**
Fixes #2692, Ref #2609

Changes:
Trems Web Editor, Home, Twitter, Instagram, Discord changed in About Block

Screenshot (34)
Screenshot (37)
Screenshot (38)

About Block is now completely in all available languages:
Bengali
Spanish (Latin America)
French
German
Italian
Hindi
Japanese
Korean
Portuguese
Swedish
Turkish
Ukrainian
Simplified Chinese
Traditional Chinese

I have verified that this pull request:

* [X] has no linting errors (`npm run lint`)
* [X] has no test errors (`npm run test`)
* [X] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [X] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by swrno** [comment]
@lindapaiste @raclim Can you please review the PR? and give your feedback.

**Comment by raclim** [comment]
Thanks for your work on this! 

I think it would be great to get this one in before the upcoming release on February 15! I just merged in https://github.com/processing/p5.js-web-editor/pull/2691, which starts these changes in the 'About' modal and I think caused some merge conflicts here. Would you be able to resolve them before the release?

**Comment by swrno** [comment]
> Thanks for your work on this! 
> 
> I think it would be great to get this one in before the upcoming release on February 15! I just merged in https://github.com/processing/p5.js-web-editor/pull/2691, which starts these changes in the 'About' modal and I think caused some merge conflicts here. Would you be able to resolve them before the release? 

Yes definitely, I would resolve it by tonight.

**Comment by swrno** [comment]
conflicts resolved!

**Review by raclim — APPROVED** [review]
This adds back in the "Donate" link that was added and removed with the fundraiser campaign, but ideally we do want to keep this in so I think it's great that this is here! 

I did intend to merge this a while back so I'm going to get this in! There could be a few translation issues, but I'm hoping they could be raised down the line.

**Pull request merged**
