### PR TITLE
Added softwrap preference for users.

### LINKED ISSUE #836: add soft wrap for long text
#### Nature of issue?

- New feature request

#### Feature enhancement details:

in the examples, and when writing examples for my classes, there tends to be long descriptive comments. It'd be amazing to have the ability to toggle softwrap or even have a setting for it in the editor so these comments can automatically remain within the editor window and prevent excess scrolling.

perhaps we could implement the wrap/hardwrap.js addon for code mirror to accomplish this?
https://codemirror.net/demo/hardwrap.html

I'd prefer that the line numbers are incremented with the soft wrap in account but this would still be a welcome addition: eg: 
screen shot 2019-02-19 at 11 38 50 am

#### New feature details:

### PR DESCRIPTION
**Pull request by LakshSingla**
I have verified that this pull request:
* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

Fixes #836 
@catarak, @bmoren opinions.. :)
Screenshot from 2019-03-22 16-57-24
Screenshot from 2019-03-22 16-57-33

### CODE REVIEW

**Comment by bmoren** [comment]
This looks good to me except one issue – the Line Wrap should be on/true by default as per @catarak's comment in #836 . Thank you for your work on this!

**Comment by LakshSingla** [comment]
> This looks good to me except one issue – the Line Wrap should be on/true by default as per @catarak's comment in #836 . Thank you for your work on this!

Thanks for pointing it out!

**Comment by catarak** [comment]
looks great! super small thing—could the preference be called "Word Wrap" instead of "Line Wrap"?

**Comment by LakshSingla** [comment]
@catarak I looked up the difference online, and I found out that technically, Word Wrap should be the correct term for it. But since `CodeMirror` supports the feature as `lineWrapping`, I am only changing the name in the visual element in `Preferences.jsx`. This would help avoid confusions for anyone working on this feature in the future. If you believe otherwise, then lemme know and I will amend the commit by renaming it everywhere.

**Comment by catarak** [comment]
this is working great for me!

**Pull request merged**
