### PR TITLE
UI changes on Private sketch feature

### PR DESCRIPTION
**Pull request by vivekbopaliya**
Progress on #3034 

Changes:
- Design inspired by this [figma ](https://www.figma.com/file/IAqdYZhfODO0FvDmvL2pI2/p5js?type=design&node-id=88-205&mode=design&t=0a2BDjr1I9eBwIQI-0)design 

https://github.com/processing/p5.js-web-editor/assets/122638553/40cf3f6f-15af-43b6-9226-de5783b43ff0
 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by raclim** [comment]
Thanks @vivekbopaliya! I'll try to have an in-depth look at this by early next week!

**Comment by vivekbopaliya** [comment]
@raclim just wanted to ping you a real quick that i updated the test cases that were failing!

**Comment by raclim** [comment]
@vivekbopaliya Thanks so much for checking in on this, I'm sorry that it took a while to get back to this! 

I loaded this up on my local environment and I think functionality-wise this looks super amazing so far!!! 🎉 

One thing I noticed that the state of the "Private" checkbox on the editor sometimes doesn't align with the toggle on the `/sketches` page until it's refreshed (demonstrated in video below). This isn't a major issue at all, but I think this could be a potential source of confusion for some users. 

https://github.com/processing/p5.js-web-editor/assets/43053081/b1100f2e-52ca-42af-8a5b-32e73cc14b78

I also think some of the changes in this PR includes some that have already been merged into the `develop` branch. Would you be able to change the branch this PR is merging to be `develop` instead of `processing:feat/privatesketch`?

**Comment by vivekbopaliya** [comment]
Oops! How did I overlook this? Sure, I will try to fix it and merge it into the develop branch.

**Comment by raclim** [comment]
Sorry I think deleting the `processing:feat/privatesketch` branch ended up closing this PR! 😭 I don't think I can reopen this on my end, but this should be resolved once you make a new one to `develop`. Sorry again about this!

**Comment by vivekbopaliya** [comment]
Hi @raclim,

Haha no worries! You can consider the [old PR](https://github.com/processing/p5.js-web-editor/pull/3034) now. I pushed the updates to the old PR, and it is now up to date with the develop branch.

PS: I tried solving the bug. When a user switches a project from private to public( from sketch collection toggle ), it updates on the homepage. However, it does not change in other cases. A third person might catch the bug if they look into it, but for now... :(


https://github.com/processing/p5.js-web-editor/assets/122638553/8ba465db-327f-454f-a197-20d19cbd8a12

**Comment by raclim** [comment]
@vivekbopaliya Thanks so much for being flexible and adapting! I'll check out the other PR that you just updated :) 

Also thanks for looking into the bug! I feel like it's not a major issue, so I think might be fine to leave and have addressed in the future for now! 

Just a heads up, I'll be merging in a few older PRs that might cause some merge conflicts, but I'll try to make a shareable staging environment of what's currently there so other folks can test it out without having to load it locally as well! I'll update the PR with a URL of the environment once that's done!

**Pull request closed without merging**
