### PR TITLE
fix safari dropdown not getting closed when click outside

### LINKED ISSUE #2578: In `Safari` browser, sketches table `download` dropdown option is not getting closed when clicking another dropdown `or` clicking outside the table
### p5.js version

2.9.2

### What is your operating system?

Mac OS

### Web browser and version

Safari and Version 16.6

### Actual Behavior

In `Safari` browser, sketches table `download` dropdown option is not getting closed when clicking another dropdown `or` clicking outside the table.

https://github.com/processing/p5.js-web-editor/assets/47579287/4a66755c-0638-4048-b8fd-d8897f8fbca8

### Expected Behavior

In `Safari` browser, sketches table `download` dropdown option should get closed when clicking another dropdown `or` clicking outside the table as it is working in `Chrome`.

### Steps:
1. Open the editor app in `Safari` web browser
2. Click on file dropdown
3. Click on Examples
4. Click on the several dropdown `download` option back to back and also click outside
5. Notice the `download` option is not getting closed

### PR DESCRIPTION
**Pull request by PiyushChandra17**
Fixes #2578 

Changes:

Same as [this](https://github.com/processing/p5.js-web-editor/pull/2600#issue-1990424592), just added the same for `CollectionListRow` component

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by PiyushChandra17** [comment]
@lindapaiste Can you please review this PR? As this issue is labeled as "Priority High", we need to fix this issue ASAP. Yes you were right that it's occuring on other components aswell ( fixed in this PR). There is one instance more it's occuring but it's happening on Chrome too, probably someone has raised an issue.

add sketch

As discussed earlier, we need to stick with one approach of how we are handling outside click throughout our codebase, i think this is the way to go as it's more flexible and with less complications (might work for chrome issues aswell ). Thanks in advance.

**Comment by lindapaiste** [comment]
> @lindapaiste Can you please review this PR? As this issue is labeled as "Priority High", we need to fix this issue ASAP. Yes you were right that it's occuring on other components aswell ( fixed in this PR). There is one instance more it's occuring but it's happening on Chrome too, probably someone has raised an issue.
> 
> add sketch
> As discussed earlier, we need to stick with one approach of how we are handling outside click throughout our codebase, i think this is the way to go as it's more flexible and with less complications (might work for chrome issues aswell ). Thanks in advance.

I really don't think that handling it piecemeal component by component is a scalable solution.  That's how we get mistakes like the one in your picture where someone put in a menu and forgot to add click-outside handling (yes there is a PR it's #2525).

I did look into this more and the components which have the Safari problem don't have explicit outside click handling.  They are relying solely on `onFocus` and `onBlur` events.  The focus/blur stuff is good for keyboard `Tab` navigation but I guess Safari isn't firing the `blur` event when you click away like the other browsers do.  I wonder if Safari also omits the `blur` when using `Tab` navigation? I have to check that.

I want us to have one place in the code where we write the logic for outside closing and then use that component or hook in other places.  The [`useModalClose`](https://github.com/processing/p5.js-web-editor/blob/3ee98994abc8362a27b34ed9ecdd06a08339e888/client/common/useModalClose.js) hook that I wrote ensures that every element which can be closed by clicking outside can also be closed via the `Esc` key.  And then I used that in a [`DropdownMenu`](https://github.com/processing/p5.js-web-editor/blob/3ee98994abc8362a27b34ed9ecdd06a08339e888/client/components/Dropdown/DropdownMenu.jsx) component, which also adds the focus/blur logic.  Then the `AssetList`, `SketchList`, and `CollectionListRow` use the `DropdownMenu` (restyled as [`TableDropdown`](https://github.com/processing/p5.js-web-editor/blob/3ee98994abc8362a27b34ed9ecdd06a08339e888/client/components/Dropdown/TableDropdown.jsx)).  They aren't declaring any of their own logic.  They're just stating "this is a menu and here are the items in it".

Which is my long-winded way of saying that in my opinion the appropriate fix for this bug is to merge #2379.

@raclim:  I know we've talked about giving me authority to approve my own PRs.  In the meantime, can you just trust me on this and merge it for me?  I know that when I'm refactoring things I'm changing a lot of code and that it's a lot for you to process.  But I am writing good code and I'm fixing all sorts of issues like this that go on to reported by someone else months later.

**Comment by raclim** [comment]
@lindapaiste Sorry for the delayed response on this! 

Skimming over it I think so far that makes sense to me and I'm down to merge in #2309 and #2379. There are a lot of changes happening and I could probably be better at getting to them more quickly 😆 but I definitely do trust your process and insight! I'm going to merge in #2649 first and deploy it since the p5.js version just got updated, and then I'll get to merging the other two in.

**Comment by raclim** [comment]
Closing with reasons outlined in https://github.com/processing/p5.js-web-editor/issues/2578#issuecomment-1912491249!

**Pull request closed without merging**
