### PR TITLE
Fixed password length

### LINKED ISSUE #889: Add minimum length of at least 6 characters for password
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
As of now, the user can signup with 1 character length also, at least a minimum of 6 character length should be there for making application more strong

### PR DESCRIPTION
**Pull request by plxity**
I have verified that this pull request:
Fixes #889 
* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by catarak** [comment]
should there be a maximum password length as well? maybe it could be fairly long, like 50 characters or something, just so users can't add super long passwords too.

**Comment by plxity** [comment]
@catarak I don't think that should be a problem. As it up to the user completely, a website never displays an error if the password is too long as it provides more security.

**Comment by catarak** [comment]
cool, makes sense. can you change the copy to 'Password must be at least 6 characters'?

**Comment by plxity** [comment]
@catarak I have done the changes, Please review and merge.

**Comment by catarak** [comment]
you've re-added the different `package-lock.json` to this pr! can you remove it?

**Comment by plxity** [comment]
I am sorry, Actually, I just messed up with my package-lock.json. I have added a new PR #901. Please review that. Sorry for the inconvenience.

**Comment by catarak** [comment]
no worries!

**Pull request closed without merging**
