### PR TITLE
Deleted Unused component

### PR DESCRIPTION
**Pull request by HunainSiddiqui**
Fixes #issue-number

Changes:
Fixes:#2300

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [  ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by lindapaiste** [comment]
This is a duplicate of #2302.  Same exact code.

**Comment by HunainSiddiqui** [comment]
But the issue is also similar . if not can you suggest me what to do

**Comment by lindapaiste** [comment]
> But the issue is also similar . if not can you suggest me what to do

Help me understand, did you not see the existing pull request and so you opened a new one to fix the issue?  Or did you see the existing pull request and saw that it had not been merged?

---

The way GitHub works is that issues will stay open until the PR that fixes it has been reviewed and merged.  When someone creates a PR and writes `Fixes #2300` in it, that means GitHub will automatically close the issue #2300 when that pull request is merged.

You can see that on the PR:
image

When you look at an issue, you can see if it already has a PR attached to it. It's actually shown in three places:
1. in the sidebar:
image
2. near the comments:
image
3. below the title:
image

If you see that, and the linked PR is still "Open", then you don't need to submit a PR because it has already been handled.  We are waiting for someone to review, approve, and merge that existing PR.

If there is a linked PR but it's "Closed" then that means we don't have a fix for the issue.  So in that case it would be good to create a new PR for it.

**Comment by HunainSiddiqui** [comment]
Thanks for the Explanation i will keep that in mind sorry for the disturbance

**Comment by raclim** [comment]
As this is addressed by #2302 first I'm going to close this, but please feel free to check out and work on other issues in the repository!

**Pull request closed without merging**
