### PR TITLE
Changed arrow color on ConsoleInput

### LINKED ISSUE #2721: Consoleinput arrow is not Adjusting to changed theme.
### p5.js version

_No response_

### What is your operating system?

Windows

### Web browser and version

_No response_

### Actual Behavior

Arrow in consoleinput is not adjusted to Themes.
looking

### Expected Behavior

It should change colour according to theme.
shoullook

### Steps:
1.  Start the editor 
2. Change the theme

### PR DESCRIPTION
**Pull request by Typicalcodes**
Fixes #2721 

Changes:

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e.

### CODE REVIEW

**Comment by lindapaiste** [comment]
Looking at your changes I can see that we have an existing theme variable `console-active-arrow-color` specifically for this element.  But it was not being applied because we were only targeting `path` and this SVG uses `polygon`[1].  You fixed that 👍.  How does it look if we use your change in the targeting (`& g, & polygon, & path {`) but leave the color variable like it was before?  Better or worse?

[1] This sort of thing is a frequent problem throughout the app.  At some point in the future I would really like to overhaul how we recolor SVGs so that we only need to target the `<svg>` element, and the SVG file would use `currentColor` to pass down that color.

**Review by PiyushChandra17 — COMMENTED** [review]
👍

**Review by Sudarshan-21 — APPROVED** [review]
It is working fine and looks great too, but dont you think changing color to something similar to the 'console-header-color' would be more impressive.

**Review by raclim — APPROVED** [review]
Thanks for your work on this, I think this is great for now!

**Pull request merged**
