### PR TITLE
Fixed Issue #978

### LINKED ISSUE #978: Missing p5.js keyword/function highlights
#### Nature of issue?

- Found a bug

#### Details about the bug: 

After marking that the new `circle` and `square`  are not highlighting like other p5 functions. I have generated a list of functions that not highlighted by the editor.

Here you go:
https://editor.p5js.org/Janglee123/sketches/z5DUgwwjy

### PR DESCRIPTION
**Pull request by AnkurIngale**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] Fixes #978 
@catarak views?

### CODE REVIEW

**Comment by AnkurIngale** [comment]
https://editor.p5js.org/Janglee123/sketches/z5DUgwwjy All keywords have highlighted now.

**Comment by catarak** [comment]
this definitely improves the issue. i've noticed that they keywords in p5.dom and p5.sound are not highlighted, and i'd like to add those too.

**Comment by AnkurIngale** [comment]
@catarak Cool I'll add those as well. If you have a list, my work will get a bit easier.

**Comment by catarak** [comment]
I just opened processing/p5.js#3666 to address getting a list. I was trying to remember how I originally got the list of keywords, and I couldn't. The only thing I can think of is that I got it from the now deprecated p5.js desktop editor.

**Comment by AnkurIngale** [comment]
I found some :
https://github.com/processing/p5.js-sound/blob/master/docs/progress.txt
https://github.com/processing/p5.js/tree/master/utils

**Comment by catarak** [comment]
i think the way to approach this is going to be to parse the `[data.json](https://raw.githubusercontent.com/processing/p5.js-website/master/src/templates/pages/reference/data.json)` file that gets updated with every p5.js release

**Comment by AnkurIngale** [comment]
The 'name' key? Like extract all values with key 'name' and store them as keywords?

**Comment by catarak** [comment]
you'll also need to check `itemType` to determine if it's a function (method) or variable (property).

**Comment by AnkurIngale** [comment]
@catarak  I have a doubt! Should I include all constants with itemtype=property? Because that's including some really strange variables like x,y and z.

**Comment by catarak** [comment]
looking over data.json, i think for itemType=property, you also need to look at the class. for example, x, y, and z, are properties of p5.Vector, and the class for them is `p5.Vector`, whereas for `mouseX`, the class is just `p5`. i _think_ you can ignore the ones that are not `p5`, but i'm not totally sure. there may be some edge cases.

**Comment by AnkurIngale** [comment]
@catarak I have added them. Just check if some methods or variables have to be removed?

**Comment by catarak** [comment]
this is working great for me, and the dom/sound variables are included! woohoo!

**Pull request merged**
