### PR TITLE
Added Sorting to SketchList #789

### PR DESCRIPTION
**Pull request by siddhant1**
I have verified that this pull request:

* [x ] has no linting errors (`npm run lint`)
* [x ] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by catarak** [comment]
thanks for working on this! i'd prefer if you did the sorting using selectors:
- [Computing Derived Data](https://redux.js.org/recipes/computing-derived-data) from the Redux Docs
- [Understanding JavaScript Selectors with and without Reselect](https://medium.com/@pearlmcphee/selectors-react-redux-reselect-9ab984688dd4) - i think it makes sense to use reselect in this case. there are times i've thought about using it for the web editor so why not add it in now 😄

**Comment by siddhant1** [comment]
I made some progress with this , but just to make sure that I am on the right path , I have to put sort params in the redux store right , so that I can get them from the state inside the selector.

**Comment by catarak** [comment]
@siddhant1 yes! you'll need to store which field you are sorting by, and whether it's ascending or descending.

**Comment by siddhant1** [comment]
Closing this , moved to #910

**Pull request closed without merging**
