### PR TITLE
Translation into Ukrainian

### PR DESCRIPTION
**Pull request by gtmizyuk**
Fixes #issue-number

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by tarasvigevskiy — DISMISSED** [review]
I liked this translation into Ukrainian. I think everyone interested will be happy.

**Review by tarasvigevskiy — DISMISSED** [review]

**Comment by catarak** [comment]
Thanks for working on this translation! Are you able to get other person(s) to review your translations? Unfortunately the release branch has expired but I'm looking into how to redeploy it.

**Comment by catarak** [comment]
Create Release Environment

**Review by RomanPolichuk — DISMISSED** [review]
The translation is good, you can safely use.

**Comment by catarak** [comment]
Create Release Environment

**Comment by catarak** [comment]
Create Release Build

**Review by catarak — APPROVED** [review]

**Pull request merged**
