### PR TITLE
Added the right click

### LINKED ISSUE #2359: Dropdown menu items cannot be right-clicked
### Increasing Access

Allows users to open a link in a new tab, etc.

### Feature enhancement details

I wanted to open "My Collections" in a new tab, but the menu closed immediately when I right-clicked the link.  Opening in a new tab is possible via `Ctrl` + click.  But right-click should work too.
image

### PR DESCRIPTION
**Pull request by sdivyanshu90**
Fixes #2359 

Changes:
- Simplified `onMouseUp`, retained `if` statement for `e.button` check.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #2359`

### CODE REVIEW

**Comment by Biki-das** [comment]
duplicate #2414

**Comment by Biki-das** [comment]
why copy others work?

**Comment by sdivyanshu90** [comment]
Hi @Biki-das,
I was working on this issue, but due to exams, I was busy and couldn't make progress. I'm currently catching up on it, and I'm not using your code.

**Comment by Biki-das** [comment]
> 

what a lie?

**Comment by lindapaiste** [comment]
@sdivyanshu90 I'm going to close this as @Biki-das's PR was submitted first, but thank you for your contribution!

@Biki-das Please be kind. Any two people working on this issue are likely to come up with the same solution.

**Comment by Biki-das** [comment]
> @sdivyanshu90 I'm going to close this as @Biki-das's PR was submitted first, but thank you for your contribution!
> 
> @Biki-das Please be kind. Any two people working on this issue are likely to come up with the same solution.

Sorry for my harsh outlook @sdivyanshu90 , i got  a little irritated as to fix this issue took me a few hours! I apologize

**Pull request closed without merging**
