### PR TITLE
Fix linting issues

### PR DESCRIPTION
**Pull request by dhruvdutt**
Clean linting issues

### CODE REVIEW

**Comment by catarak** [comment]
this pull request re-adds the submodule that was removed—can you please remove it?

**Comment by dhruvdutt** [comment]
@catarak Cleaned. Please review.

**Comment by catarak** [comment]
for some reason this commit is also changing `package-lock.json`. could you remove those changes as well?

**Comment by dhruvdutt** [comment]
@catarak Cleanup. :100:

**Comment by catarak** [comment]
thanks!

**Pull request merged**
