### PR TITLE
Minor fix

### LINKED ISSUE #587: Keyboard handling function is triggered twice when first login
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

The steps to reproduce:
1. log in
2. saving a default sketch through ctrl/command s
3. an ErrorModal pops up
4. if you refresh the page and try saving again, it will go back to normal

### PR DESCRIPTION
**Pull request by shinytang6**
Before your pull request is reviewed and merged, make sure you

* [x] there are no linting errors -- `npm run lint`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master. If you're asked to make more changes make sure you rebase onto master then too!
* [x] pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

Thank you! Fixes #587

### CODE REVIEW

**Comment by catarak** [comment]
is this related to #561?

**Comment by shinytang6** [comment]
maybe l should open a new issue? Acually if #561 is not submitted, `handleGlobalKeydown` is still triggered twice in the following case, but will not cause problem because first trigger will do nothing(with `this.isUserOwner() = this.props.user.authenticated = false`).
1. log in
2. saving a default sketch through ctrl/command s
3. an ErrorModal pops up
4. if you refresh the page and try saving again, it will go back to normal

**Comment by catarak** [comment]
go ahead and open a new issue! do you think it makes sense to merge this in since it fixes part of the issue, or roll it together with whatever fixes the issue you've outlined above?

**Comment by shinytang6** [comment]
not very sure of what you mean, do you think its not clean enough or？l think l have listed the problem and pr related to that one O_o

**Comment by catarak** [comment]
i'm confused! which issue/PR is that? hard to keep track of all of this stuff 🎉

**Comment by catarak** [comment]
but i can merge this in since it amends #561.

**Pull request merged**
