### PR TITLE
prettier formatting to v2.2.1 and lint error fix

### PR DESCRIPTION
**Pull request by dewanshDT**
Changes:

prettier formatting and lint errors.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.

### CODE REVIEW

**Comment by lindapaiste** [comment]
Hmm so this doesn’t actually impact the scss files?

**Comment by dewanshDT** [comment]
How do I do the scss files then

**Comment by dewanshDT** [comment]
@lindapaiste, this is because we're not using prettier to format scss files

**Comment by lindapaiste** [comment]
Yeah I kinda thought that Prettier was just for the JS.  So the formatting on the `.scss` files must just be from your VSCode settings?  So it's whatever.  Not worth worrying about.

**Comment by dewanshDT** [comment]
so I should close this right?

**Pull request closed without merging**
