### PR TITLE
Toast displayed when settings are saved.

### LINKED ISSUE #932: Modal/ snackbar should be displayed when settings are saved.
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
Whenever Settings are saved on https://editor.p5js.org/account page, a modal or snack bar should be displayed confirming settings are saved

### PR DESCRIPTION
**Pull request by plxity**
I have verified that this pull request:
fixes #932 
* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by plxity** [comment]
@catarak Please review this. :)

**Comment by catarak** [comment]
see my update to #932!

**Comment by plxity** [comment]
@catarak  I think displaying alert would be right because in many places inside the project alert is used for notifying a user.

**Comment by catarak** [comment]
@plxity i don't agree. alerts are only used to prevent a user from leaving the page with unsaved changes, and it's because there's not a way to do it without alerts. using alerts on a website is not best practice unless it's totally necessary.

**Comment by plxity** [comment]
@catarak Please review the changes. I have used toast component. :)

**Comment by plxity** [comment]
@catarak  Please review this. :)

**Comment by plxity** [comment]
@catarak Please review this and if any changes are required let me know. :)

**Comment by catarak** [comment]
this is great, thanks!

**Pull request merged**
