### PR TITLE
[WIP] Allow nesting of files and folders using AddFile and AddFolder modal

### LINKED ISSUE #765: Allow adding nested files and folders in `Add File` and `Add Folder` modal
#### Nature of issue?

- [ ] Found a bug
- [] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### New feature details:

### PR DESCRIPTION
**Pull request by LakshSingla**
Before your pull request is reviewed and merged, please ensure that:

* [x] there are no linting errors -- `npm run lint`
* [x] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [x] your pull request is descriptively named and links to an issue number

**`Fixes #765 `**
#765 
**Todo**
 - Return parent folder's ID in case if a user is logged in ( I think it would cause issues due to asynchronous nature of execution )
I have added an empty placeholders.
[line#85](https://github.com/LakshSingla/p5.js-web-editor/blob/21a972b4e06da7219c3ac196fa277a722f9b20ea/client/modules/IDE/actions/files.js#L85)
[line#196](https://github.com/LakshSingla/p5.js-web-editor/blob/21a972b4e06da7219c3ac196fa277a722f9b20ea/client/modules/IDE/actions/files.js#L196)
They are to be replaced by the ID of the newly created folder. ( As done in the case when user is not logged in ).
 - Filter out empty folder names caused due to split method called on successive delimiters
 - Add documenting comments to the function
I would complete the last 2 points in a day or two.

### CODE REVIEW

**Comment by LakshSingla** [comment]
@catarak Apparently, nodemon keeps disconnecting from my mongoDB database on making any changes, forcing a recompilation of webpack (on restarting the server). Is this issue observed anywhere else? I will attach the screenshot of the terminal later today.

**Comment by LakshSingla** [comment]
@catarak I am unable to figure out how to resolve the issue if the user is logged in (where subsequent folder requests would need to be sent to the server)...

**Comment by catarak** [comment]
@LakshSingla maybe all of the file id's should be generated client-side? i'm not sure if that's the issue you're having.

**Comment by LakshSingla** [comment]
@catarak So here's the deal.. If the user is logged in, the Folder Id is not created on the client side, rather a request is made to the server, which creates the file and sends the desired response. Thus to generate child folders/file, I would need to have the parent id of the folder which was newly created. How should I get that ?? (As requests are made asynchronously). TLDR: Help me fill the [line#85](https://github.com/LakshSingla/p5.js-web-editor/blob/21a972b4e06da7219c3ac196fa277a722f9b20ea/client/modules/IDE/actions/files.js#L85) and [line#196](https://github.com/LakshSingla/p5.js-web-editor/blob/21a972b4e06da7219c3ac196fa277a722f9b20ea/client/modules/IDE/actions/files.js#L196) and make sure that the parent id is updated before the request to create next file/folder is made

**Comment by LakshSingla** [comment]
@catarak The folder id is created on the client side when the user is not logged in. The problem arises when the user **is** logged in. It seems as if the API is creating some ID and passing it as a response to the client. Now I am concerned that as the call is asynchronous, what should I return as a parameter for passing of the next folder creating function. It would help me greatly, if you could help me implement this logic.

**Comment by LakshSingla** [comment]
> @LakshSingla maybe all of the file id's should be generated client-side? i'm not sure if that's the issue you're having.

This is doable, if all of the file's and folder's ids are generated client side, but it would require changes from the backend code. I doubt if it would be feasible that much, as currently the id returned is the mongodb's internally created id. Would it be possible, if we extend this feature to those users who aren't logged in (although it would be a source of confusion). As and when this issue is resolved for those users who are logged in, we could extend the support to them.

**Comment by catarak** [comment]
maybe there's a bigger (and separate) issue here, which is that the data structure of the files/folders should be abstracted on the front end. #542 has some discussion about this, but it's interesting to see how this affects the application outside of the context of a public API. 

for context, i used a mongodb tutorial (https://docs.mongodb.com/manual/tutorial/model-tree-structures-with-child-references/) as reference for how to structure the files.

**Comment by catarak** [comment]
@LakshSingla no worries! this is not an urgent issue and there is higher priority stuff i am focusing on at the moment.

**Comment by LakshSingla** [comment]
@catarak I was trying to take up this issue once more, but it seems that my code is not working after merging the changes with the latest master branch. Has the structure on the server side changed since my last commit?? There were no merge conflicts present while merging.

**Comment by catarak** [comment]
@LakshSingla the reason for that `if` statement is to check if a project is new and needs to be created, server-side, in which `state.project.id` would be undefined, or if the project already exists, in which `state.project.id` would be defined, and would then need to be updated server-side.

**Comment by raclim** [comment]
Closing due to this being stale. Please reopen or make another pull request if you'd like to make the updates! :)

**Pull request closed without merging**
