### PR TITLE
update authentication in examples.js to authenticate with request hea…

### PR DESCRIPTION
**Pull request by Swapnil-2001**
…ders

Referencing issue #1613 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by Swapnil-2001** [comment]
@catarak I'd be grateful if you could let me know if I'm headed in the right direction with the changes.

**Comment by catarak** [comment]
> @catarak I'd be grateful if you could let me know if I'm headed in the right direction with the changes.

This is working great for me! This is exactly right. The expected behavior is that these scripts will still run (`npm run fetch-examples` and the `ml5` and `generative-design` ones), and the sketches will still run in the exact same way. Want to try updating the other two scripts?

**Comment by Swapnil-2001** [comment]
Thank you, I'd be glad to update the other two scripts as well!

**Comment by catarak** [comment]
I just realized you opened a new pull request for the other changes. In the future, you can push to the same branch and your pull request will get updated with your changes!

**Pull request closed without merging**
