### PR TITLE
Show and hide password option added

### LINKED ISSUE #888: Add eye button to see password in login form
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
Add eye button to see the password in the password field like usual login / signup form
Capture

#### New feature details:

### PR DESCRIPTION
**Pull request by plxity**
I have verified that this pull request:
Fixes #888 
* [X] has no linting errors (`npm run lint`)
* [X] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [X] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by plxity** [comment]
@catarak This is failing because I have used double quotes instead of single quotes. but if I use single quotes, the functionality doesn't work i.e input field always behaves like a text field. I searched a lot about it but couldn't find a solution. Can you suggest some solution? :) Thank you.

**Comment by plxity** [comment]
@catarak Please review this. I think this is the fine approach to implementing show/hide password functionality.  :)

**Comment by plxity** [comment]
@catarak Please review this. I think this is the fine approach to implementing show/hide password functionality. :)

**Comment by catarak** [comment]
thanks for working on this! i think the design should look like this: 
show-hide-pw
"Show" should change to "Hide" when the password is visible. Note that for accessibility reasons, Show/Hide should be a checkbox, but presented as a button. You can do this by using a `<label>`, making the checkbox itself `display: none`, and change the styling of the label based on `.checkbox-class:checked`.

**Comment by plxity** [comment]
@catarak Okay, I will make the changes. :)

**Comment by nimishagarwal76** [comment]
@plxity you still working on it or can I fix the issue?

**Comment by plxity** [comment]
@nimishagarwal76 I am working on this.

**Comment by shakti97** [comment]
Its being a long time, if this issue still not resolved. I would like to contribute to it.

**Pull request closed without merging**
