### PR TITLE
Patched console.log to only log in dev mode (#853)

### PR DESCRIPTION
**Pull request by siddhant1**
I have verified that this pull request:

* [x ] has no linting errors (`npm run lint`)
* [x ] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [ x] is descriptively named and links to an issue number, i.e. `Fixes #123`

I don't think this is the mode elegant solution , but we can add another logger that logs with time and everything.
Also there is a need to remove console.logs from error callbacks and actually handle errors.
I will look into it next

### CODE REVIEW

**Comment by siddhant1** [comment]
Also I feel the errors are handled at the backend but there are many logs too.
I think we should remove those logs and actually log into a file (winston or morgan) or a datastore.
That'll be a great improvement.

**Comment by catarak** [comment]
rather than overwriting `console.log` in production, is there a way with webpack to just remove all console.log statements from the javascript? i think that is a better solution.

**Comment by siddhant1** [comment]
https://www.npmjs.com/package/babel-plugin-transform-remove-console

I think terser and uglifyJs also do it , but I found this babel plugin which is handy too .

@dhruvdatt @catarak

**Comment by siddhant1** [comment]
The console.logs were not removed from the bundle and I opened a new pr with a better approach( #884 ) , babel-plugin will remove logs from the bundle in the prod.
Closing this for now/

**Pull request closed without merging**
