### PR TITLE
Fixed color of add folder option

### LINKED ISSUE #1005: Fix Colors in "Add Folder" dialog box
#### Nature of issue?

- Found a bug

#### Details about the bug: 

On hover, Color of the button should change and error message colour should be displayed according to the theme set.

Capture

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

I am working on this.

### PR DESCRIPTION
**Pull request by plxity**
I have verified that this pull request:
Fixes #1005 
* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by plxity** [comment]
@catarak Please review this. :)

**Comment by plxity** [comment]
@catarak  Can you review this? :)

**Comment by dhruvdutt** [comment]
@plxity Can you please send a screenshot for the change?

**Comment by catarak** [comment]
can you please attach an issue number to this? also it seems you have added some changes that are not relevant, by removing some props.

**Comment by plxity** [comment]
@catarak Actually I referred add files code and I checked it was working fine. I will check it once again.

**Comment by plxity** [comment]
@catarak Can you review the changes? 😃

**Comment by catarak** [comment]
I don't think `red` on the background is WCAG 2.0 compliant.

**Comment by plxity** [comment]
@catarak Then which color should I use?

**Comment by catarak** [comment]
`$p5-contrast-pink: #FFA9D9;` is included in the high-contrast color code syntax theme—this is probably the closest to red!

**Comment by plxity** [comment]
@catarak Okay, I will add this color.

**Comment by plxity** [comment]
@catarak I have done the changes. Please review it again. :)

**Comment by catarak** [comment]
1. You have put in a raw color inline. This will not change per the theme. You need to add the color to the theme map, along with error colors for the other themes, and use the SASS function to get the color per theme.
2. You still have changes in here that are not relevant to this PR.

**Comment by plxity** [comment]
@catarak Okay, I thought you wanted to keep same color for error in all the themes. My bad. I'll make the required changes and push them :)

**Comment by plxity** [comment]
@catarak I just have one query. Which color for error should I use for different themes? Can you tell the hex codes for them? :)

**Comment by catarak** [comment]
sure!
light error color: #ed225d
dark error color: #ed225d
high contrast error color: #FFA9D9;

**Comment by plxity** [comment]
@catarak Thank you so much. :)
Can you also review #958 PR I have made the following changes?

**Comment by plxity** [comment]
@catarak Please review and merge this. :)

**Comment by catarak** [comment]
even though it doesn't appear i merged this, i did merge it. i squashed the commits which removed its attachment from this PR.

**Comment by plxity** [comment]
@catarak Should I open a new PR now?

**Comment by catarak** [comment]
@plxity no it's merged to master! sorry, it's confusing. i don't know how to:

1. add commits to someone else's PR,
2. squash those commits into one commit,
3. push those commits, and
4. have it match up again with the PR.

like, am i the only one who wants to do this?? why can't i figure it out, haha

**Comment by plxity** [comment]
@catarak How did this happen? 😨 I guess it never happened before right?
Don't worry we will figure this out soon 😆

**Comment by catarak** [comment]
i like to squash all of the commits from a PR into one commit, as i think it's cleaner. however, if i want to add a commit to a PR that i didn't make (i.e. sometimes the fix is so small that it's faster for me to just fix it, or someone started a PR and never finished it, so i want to finish it), i have to merge in the PR manually. however, this doesn't squash all of the commits.

**Pull request closed without merging**
