### PR TITLE
Added Bengali Language Support to the editor and Some terms are converted into Korean 

### LINKED ISSUE #2616: Add Bengali Language Support to the Full Editor
### Increasing Access

The current version of the p5.js web editor lacks Bengali language support in the full editor, limiting accessibility for Bengali-speaking users. This issue is opened to initiate the addition of Bengali as a supported language in the full editor, ensuring a more inclusive and user-friendly experience for the Bengali-speaking community.

### Feature enhancement details

Addition of Bengali language support will cater to a wider audience, fostering inclusivity and usability for Bengali-speaking users. Users will be able to engage with the full editor in their preferred language, making the overall experience more intuitive and user-friendly. This enhancement aligns with the goal of engaging with and catering to the diverse global community of p5.js users.

### PR DESCRIPTION
**Pull request by swrno**
Fixes #2616 
Changes:

Screenshot (23)
Screenshot (24)
Screenshot (25)

As a native bengali speaker, I have personally checked and verified all the words and sentences are correct.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by raclim — CHANGES_REQUESTED** [review]
Thanks so much for working on this! I personally don't speak Bengali, but I think this looks great so far! 

I would remove the translation changes to the following files though to keep it consistent to the purpose of this pull request, which is adding Bengali translations: 

 - translations/locales/fr-CA/translations.json
 - translations/locales/hi/translations.json
 - translations/locales/it/translations.json
 - translations/locales/ja/translations.json
 - translations/locales/ko/translations.json
 - translations/locales/pt-BR/translations.json
 - translations/locales/sv/translations.json
 - translations/locales/tr/translations.json
 - translations/locales/uk-UA/translations.json

**Comment by swrno** [comment]
> Thanks so much for working on this! I personally don't speak Bengali, but I think this looks great so far! 
> 
> I would remove the translation changes to the following files though to keep it consistent to the purpose of this pull request, which is adding Bengali translations: 
> 
>  - translations/locales/fr-CA/translations.json
>  - translations/locales/hi/translations.json
>  - translations/locales/it/translations.json
>  - translations/locales/ja/translations.json
>  - translations/locales/ko/translations.json
>  - translations/locales/pt-BR/translations.json
>  - translations/locales/sv/translations.json
>  - translations/locales/tr/translations.json
>  - translations/locales/uk-UA/translations.json
> 

Great! Thanks for your guidance and support.

**Comment by lindapaiste** [comment]
@raclim @Swarnendu0123 If we merge the other PR first then those changes won't show up as "Files changed" here.

**Comment by swrno** [comment]
Yeah! That's also a good idea. On the confirmation of @raclim , let's first merge those 2 PRs and then this PR.

**Comment by swrno** [comment]
> Thanks so much for working on this! I personally don't speak Bengali, but I think this looks great so far!
> 
> I would remove the translation changes to the following files though to keep it consistent to the purpose of this pull request, which is adding Bengali translations:
> 
> * translations/locales/fr-CA/translations.json
> * translations/locales/hi/translations.json
> * translations/locales/it/translations.json
> * translations/locales/ja/translations.json
> * translations/locales/ko/translations.json
> * translations/locales/pt-BR/translations.json
> * translations/locales/sv/translations.json
> * translations/locales/tr/translations.json
> * translations/locales/uk-UA/translations.json

Hey @raclim I have removed all your mentioned files now its ready for merging. I have not removed Korean language file because some terms are added which makes the editor completely into Korean, if Korean is selected as a language.

**Review by raclim — APPROVED** [review]
Sorry for getting to this a bit late and thanks for removing all of the files! 

I don't feel 100% confident about keeping the Korean translations, but I think they could be okay for now. Thanks again for your work!

**Pull request merged**
