### PR TITLE
Aligned Properly fixes #914

### LINKED ISSUE #914: Align in one line
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Capture

- Web browser and version:  Edge 
- Operating System: Windows
- Steps to reproduce this bug:

Both the fields should be in one line.

### PR DESCRIPTION
**Pull request by plxity**
I have verified that this pull request:
fixes #914 
* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by plxity** [comment]
@catarak Please review this. :)

**Comment by catarak** [comment]
now for me this is misaligned (on Mac OSX/Chrome)
Screen Shot 2019-03-20 at 3 22 30 PM

**Comment by catarak** [comment]
rather than using `margin-top` to do the alignment, see if you can use flexbox 😄

**Comment by plxity** [comment]
@catarak okay, I'll just try to fix it properly and will send a Pull Request ASAP. :)

**Pull request closed without merging**
