### PR TITLE
show toast for success/failure of file creation

### LINKED ISSUE #1313: Display message of file created
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
On adding a new file by typing the file name and hitting "enter", file gets created.
I think on hitting "enter",  text should appears like "file.js was created" and should disappear after few seconds on the modal box.
Screenshot from 2020-03-06 12-24-34

### PR DESCRIPTION
**Pull request by saijatin28**
This solves #1313  
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #1313`

### CODE REVIEW

**Comment by saijatin28** [comment]
> I have verified that this pull request:
> 
> * [ ]  has no linting errors (`npm run lint`)
> * [ ]  is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
> * [ ]  is descriptively named and links to an issue number, i.e. `Fixes #1313`

**Comment by catarak** [comment]
I took a look at this and I'm not convinced about showing a popup every time a file is successfully created—it doesn't feel useful? I could see just having one when a file is not created successfully.

**Comment by saijatin28** [comment]
> I took a look at this and I'm not convinced about showing a popup every time a file is successfully created—it doesn't feel useful? I could see just having one when a file is not created successfully.

I have taken this into consideration and made the neccessary changes.

**Comment by saijatin28** [comment]
> LGTM 👍

Hey! Could you re-review this work

**Comment by saijatin28** [comment]
Hey @catarak @plxity . Not to sure you guys but could you please re-review this pull request?

**Comment by catarak** [comment]
Sorry for the delay on merging this! My concern with this PR is the inconsistency throughout the application. There's no other actions that show an error like this, and rather than just merging this in, I'd like to take a step back and look at what errors need to be better displayed.

**Pull request closed without merging**
