### PR TITLE
Fixes #2524, Close create file menu when clicking outside

### LINKED ISSUE #2524: The "+" button that toggles the menu with options to create a folder and create a file does not close the menu when clicking anywhere else on the screen.
### Increasing Access

When we are clicking on the plus "+" for creating the folder or file the menu which get toggle is not close when we click any where on the screen.

### Feature enhancement details

This will increase the user experience.

[Screencast from 2023-10-21 19-20-49.webm](https://github.com/processing/p5.js-web-editor/assets/99260988/5febbd2c-7372-4bfd-8bb6-c25d49aaaf9e)

### PR DESCRIPTION
**Pull request by gauravsingh94**
Fixes #2524

Changes:
Fix: clicking anywhere will close the menu of creating and deleting file and folder.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by gauravsingh94** [comment]
The final output will look like this.

[Screencast from 2023-10-21 20-11-46.webm](https://github.com/processing/p5.js-web-editor/assets/99260988/59f8b4a7-6d30-44b9-8c0c-8287cd5f80ac)

**Review by lindapaiste — APPROVED** [review]
This looks fine.  I hate that we have such similar code in so many components and [I wrote a utility hook to fix that](https://github.com/processing/p5.js-web-editor/pull/2309/files), but that PR still has not been merged 🙃 So I guess we should merge this to fix the immediate problem.  (I can merge your PR but not my own).

I haven't loaded up your branch and run it yet.  I will do that before merging but I'm approving it now because the code looks good.

**Review by PiyushChandra17 — APPROVED** [review]
These changes looks good to me and it has working demo aswell

**Comment by gauravsingh94** [comment]
Hello @raclim,

I've noticed that my pull requests are not getting merged. Specifically, this one was reviewed in October but has not been merged yet.

Could you please provide me with feedback on the status and any necessary actions to move forward?

**Comment by raclim** [comment]
Thanks for working on this! We ultimately ended up merging another fix for this, so I'm going to close this PR and issue.

**Pull request closed without merging**
