### PR TITLE
Removed redundant redirects between client and server

### LINKED ISSUE #2992: Evaluate redundant redirects between client and server
### Increasing Access

It is confusing to work with code where redirections can be be initiated from multiple places.

### Feature enhancement details

Ref: https://github.com/processing/p5.js-web-editor/pull/2987#issuecomment-1925915203

We should look through the https://github.com/processing/p5.js-web-editor/blob/develop/client/routes.jsx file and see which redirects are not actually needed because they are already handled by the server in https://github.com/processing/p5.js-web-editor/blob/develop/server/routes/server.routes.js.

Specifically, we should check over our usages of `userIsNotAuthenticated`, `userIsAuthenticated`, `userIsAuthorized`, and `createRedirectWithUsername`.  I have a hunch that we can actually delete all four of those functions.  Let's make a list of all routes which use some form of redirection and whether each route's redirect logic duplicates what is already implemented on the server.

### PR DESCRIPTION
**Pull request by Mubashirshariq**
Fixes #2992 

Changes:
Server Side:
Made changes on the server: Redirected "/sketches" and "/assets" to URLs with the username. Also, redirected "/reset-password" and "/reset-password/:reset_password_token" to "/account" if the user is logged in.
client :
Made changes on the client: Removed all Higher-Order Component (HOC) auth checks from routes.jsx, deleted createRedirectWithUsername component, and removed auth.js file.

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by Mubashirshariq** [comment]
@lindapaiste  plz review this PR ,i have made the proposed changes.

**Comment by Mubashirshariq** [comment]
@raclim  could you please reveiw this PR since it has been open for a very long time

**Comment by raclim** [comment]
@Mubashirshariq Sure, I'm sorry that it took some time! Would you be able to resolve some of the merge conflicts here first?

**Comment by Mubashirshariq** [comment]
@raclim  sure will do that

**Comment by Mubashirshariq** [comment]
@raclim  done with resolving conflicts

**Review by raclim — APPROVED** [review]
Thanks for your work on this!

**Pull request merged**
