### PR TITLE
favicon issue resolved

### PR DESCRIPTION
**Pull request by parteekcoder**
issue #2140 solved

@raclim please review this PR and suggestions of your will be admired

### CODE REVIEW

**Review by lindapaiste — CHANGES_REQUESTED** [review]
Great catch on the malformed URL!  Once again I think there's a better solution though, because we actually *do* have the file included in the website so we don't need to load it from GitHub.

The current url path `href='favicon.ico'` is *relative* so it looks for the file in the current directory.  That's why it resolves to https://editor.p5js.org/greenStone83/sketches/favicon.ico which is not found.

We can change it to an *absolute* path by starting with a `/`.  The path `href='/favicon.ico'` will look for the file in the root directory and this URL https://editor.p5js.org/favicon.ico does load.

**Comment by parteekcoder** [comment]
yeah @lindapaiste that is also a good suggestion , but let @raclim @catarak decide as here also is same thing at line https://github.com/processing/p5.js-web-editor/blob/develop/server/views/404Page.js#L48

But thanks @lindapaiste I am always open to new suggestions

**Comment by parteekcoder** [comment]
@raclim @catarak @davepagurek  plz review this PR , your suggestions are admired by me

**Comment by raclim** [comment]
Thanks for working on this! I'm down to try out and follow through with @lindapaiste's suggestion if it sounds good to you!

**Comment by parteekcoder** [comment]
> Thanks for working on this! I'm down to try out and follow through with @lindapaiste's suggestion if it sounds good to you!

is @lindapaiste also maintainer of this repo

**Comment by parteekcoder** [comment]
> Thanks for working on this! I'm down to try out and follow through with @lindapaiste's suggestion if it sounds good to you!

I want to contribute to p5web-editor , I am understanding the codebase and solving the issues to have a better understanding

**Comment by parteekcoder** [comment]
> Thanks for working on this! I'm down to try out and follow through with @lindapaiste's suggestion if it sounds good to you!

yeah , I am also always open to new suggestions

**Comment by lindapaiste** [comment]
> > Thanks for working on this! I'm down to try out and follow through with @lindapaiste's suggestion if it sounds good to you!
> 
> is @lindapaiste also maintainer of this repo

I'm not a maintainer, I just have a lot of opinions 😜.  I think @raclim is the only active maintainer at the moment.

**Comment by raclim** [comment]
I'm going to close this PR for now, but please feel free to revisit this or create a new one! :)

**Pull request closed without merging**
