### PR TITLE
Solved the issue with replace Behaviour. 

### LINKED ISSUE #2523: Issue with Replace Behavior in p5.js Web Editor
### p5.js version

_No response_

### What is your operating system?

None

### Web browser and version

_No response_

### Actual Behavior

Currently, when the arrow keys are pressed without entering text for replacement, it opens the find elements box.

https://github.com/processing/p5.js-web-editor/assets/127239756/0bed3aac-e0c8-4faa-ab12-87b7361da9d1

### Expected Behavior

When the "Replace" box is open, pressing the arrow keys should navigate to and focus on the find elements in the "Replace" block itself as soon as text is entered for replacement.

### Steps:
1.Open the p5.js web editor.
2. Use the "Replace" functionality (Ctrl+F) without entering any text for replacement.
3. .Press the arrow keys (^ and V) for previous and next, respectively.

### PR DESCRIPTION
**Pull request by perminder-17**
Fixes #2523 

Changes: DONE THE REQUIRED CHANGES, here are the result

https://github.com/processing/p5.js-web-editor/assets/127239756/a038dfbb-bc92-405e-967f-ca9c5587866c

When the input field is empty, the up and down arrow keys will focus on the searchField.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by perminder-17** [comment]
@raclim @lindapaiste ,I have made the changes. U may add this to minor relase.

**Comment by perminder-17** [comment]
I have also verified that increasing the z-index of the box does not have any adverse effects on other boxes.

**Review by lindapaiste — APPROVED** [review]
Thanks for fixing this!  This is a really messy area of the codebase because we've copied and modified the core CodeMirror code.  Definitely not an easy one.

**Comment by perminder-17** [comment]
> Thanks for fixing this! This is a really messy area of the codebase because we've copied and modified the core CodeMirror code. Definitely not an easy one.

So true, it was challenging for me too to make changes into this file. Anyways, thanks for your support.

**Pull request merged**
