### PR TITLE
Fix [#2785] text color not changing in dark/high contrast theme

### LINKED ISSUE #1852: Set default iframe background color to white
#### Nature of issue?

- Found a bug

#### Details about the bug: 

Hi @catarak I have run into this as well, here is a screenshot of how text looks in the Preview window in Dark mode, but in High Contrast mode it is similar, defaulting to black text on a very dark background:
image
Here's an example of a sketch that displays this issue: https://editor.p5js.org/ml5/sketches/XCFPKqIKrt

_Originally posted by @leemark in https://github.com/processing/p5.js-web-editor/issues/1400#issuecomment-803752647_

@catarak: I think the issue here is that the iframe should have a default background color of white, as is the norm for websites.

### LINKED ISSUE #2785: text colour not changing in dark/high contrast theme in ```describe()```
### p5.js version

1.9.0

### What is your operating system?

Mac OS

### Web browser and version

Chrome , Version 120.0.6099.109 (Official Build) (arm64)

### Actual Behavior

when the ```LABEL``` is passed in ```describe()``` the text colour is not changed when switched to dark/high contrast theme.

Light theme:
Screenshot 2023-12-26 at 4 04 36 PM

Dark theme:
Screenshot 2023-12-26 at 4 05 03 PM

### Expected Behavior

The text colour should toggle as the user switches between light and dark theme

### Steps:
1. Go to https://editor.p5js.org/ and paste the below code in the editor ( or any other code which uses ```describe()```)
### Snippet:
```js

function setup() {
  background('pink');

  // Draw a heart.
  fill('red');
  noStroke();
  circle(67, 67, 20);
  circle(83, 67, 20);
  triangle(91, 73, 75, 95, 59, 73);

  // Add a general description of the canvas
  // and display it for debugging.
  describe('A pink square with a red heart in the bottom-right corner.', LABEL);
}

```

### PR DESCRIPTION
**Pull request by somesh4747**
fix [#2785] I have changed the preferences.js file for detecting the state and changed the files in the state, and index.js for reflecting the changes to actual files, createDefaultFiles.js for the default CSS setting.
 [#1852] Here the same problem.

Fixes #2785 
fixes #1852 

Changes:

I have verified that this pull request:

* [X] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

https://github.com/processing/p5.js-web-editor/assets/109422834/210a747f-f588-44bf-9f72-e4cdf37a7de5

I am a beginner still learning to contribute, if further changes are needed do let me know... thank you

### CODE REVIEW

**Comment by lindapaiste** [comment]
This is a really interesting approach.  We had talked about solving it in a much simpler way by forcing the sketch background to always be white.  I'm honestly not sure if modifying the user's sketch files is over-reaching or if it's genius.

If we decide to go with this general approach then I have some more specific feedback about your code.  But at this point I'm on the fence about the fundamentals.  @raclim -- thoughts?

**Comment by somesh4747** [comment]
@lindapaiste, see... before several PRs were trying to solve this by changing the default style.css file to as background-color: white, but the problem is -- design-wise @raclim is not that sure that it is the best solution -- in https://github.com/processing/p5.js-web-editor/pull/2481#issuecomment-1793064898. 

That's why I tried a different approach to change the file based on the theme selected by user. please feel free to give any suggestions or feedback for any further updates, I would highly appreciate any feedback from you and other respected maintainers.

**Comment by raclim** [comment]
Thanks for working on this @somesh4747! I think this feels closer to what I was imagining when I mentioned in that comment wanting to find another solution that would blend in better with the High Contrast and Dark Themes! 

I also agree with @lindapaiste that this approach is really interesting but might need some minor adjustments. I'm not sure if there's a different one that could work better, but I'm not opposed to giving this a go either.

**Comment by somesh4747** [comment]
@raclim thanks for the feedback, please tell me what to improve in this, I would really appreciate any further suggestions and updates on this PR.

**Comment by raclim** [comment]
Thanks so much for your work on this! I'm sorry that we couldn't get back to this in time, but since it's been a while since this PR was submitted I'm going to close this for now. I'm really sorry again that we couldn't get this in, but please feel free to reopen this PR with any updates or check out our other issues!

**Pull request closed without merging**
