### PR TITLE
Implementing Pagination while rendering examples.

### LINKED ISSUE #2952: Implementing Pagination while rendering examples
### Increasing Access

Implementing pagination can enhance accessibility by : 
- Improving load times,
- Enabling keyboard navigation
- Ensuring screen reader compatibility
- Enhancing compatibility with assistive technologies
- Providing better scalability
- Optimising for mobile devices,

### Feature request details

Their should be pagination in the examples page, with a particular number of examples rendered each time

https://github.com/processing/p5.js-web-editor/assets/91189139/b87c736b-a1a9-4eec-990e-035dae21d9a3

## I want to Work on this issue

### PR DESCRIPTION
**Pull request by gAurav-0x07**
Fixes #2952

Changes: I added pagination to the sketches section. 

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

https://github.com/processing/p5.js-web-editor/assets/99645553/a43b8eb0-3328-43b1-bf48-a70ab4d470da

### CODE REVIEW

**Comment by gAurav-0x07** [comment]
@lindapaiste what more design is expected? can you explain it please?

**Comment by lindapaiste** [comment]
> @lindapaiste what more design is expected? can you explain it please?

The pagination buttons are a totally new design element so we need to put some thought into what we want them to look like.  In my opinion the hot pink is too over-emphasized but I'm not a designer.

**Comment by DrizzyOVO** [comment]
@lindapaiste how is this? 

image

Default :- 

image

Hover :- 

image

**Comment by gAurav-0x07** [comment]
@lindapaiste I've made a few changes. This ui makes it litter easier for users to navigate. 


https://github.com/processing/p5.js-web-editor/assets/99645553/939c1c6d-f181-4449-b25b-571625a408a6


https://github.com/processing/p5.js-web-editor/assets/99645553/833fa842-c09a-4ab6-8247-af12aab627fb

**Pull request closed without merging**
