### PR TITLE
Fixes ##795 resizer hover issue

### PR DESCRIPTION
**Pull request by siddharthshah3030**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

I checked on both Mozilla and Chrome seems good to me
I have changed resizer width 6px for vertical and 8 px for horizontal
with a little padding to the off side
kindly review and verify my changes

I have a typo on commit message instead of "scroll bar" it should be "resizer"

### CODE REVIEW

**Comment by chrisorban** [comment]
Thanks for working on this!

**Comment by catarak** [comment]
a few things:
1. if you run `npm run lint`, there is a linting error
2. this brings back an old bug, #441. the mouseX position won't go below 4.

**Comment by siddharthshah3030** [comment]
I have fixed the linting issue 
and I understand the problem in issue #441 

I would like to fix this issue 
but can't understand what should I fix exactly 
shall I give some width to just the resizer (it would take considerable screen like 6px width or so)

**Comment by catarak** [comment]
i think the way to handle this is to give the **one** resizer, dividing the code from the preview, some width. **not** every single horizontal and vertical resizer.

**Pull request closed without merging**
