### PR TITLE
initial Korean Translation of Web Editor

### LINKED ISSUE #1632: Korean Translation of Web Editor
**Currently in progress with @kangashley & @yinhwa** 

- - - - - - - - - - 

Hi @catarak, @ghalestrilo ! I'm trying to add Korean translation to the web editor to increase the editor's lingual accessibility to Korean speakers. My particular concern is on some dozens of older adults in Korea that I'll be having p5.js workshop with on November, but it certainly will be helpful for the language group in general both in and out the country.

I have checked in with @ghalestrilo if there'd be any conflicts on the mobile UI if I add new translation, and Thales's told me it will work automatically :)  I've also noticed that [Spanish translation] was successfully added a couple months ago!🎉

And yet, I would like to ask if it will be alright for me to start working on it by now; and if adding translation was part of the maintenance plan. If everything's fine, I'm planning to have it done before the Week 2 of November, since I'm having the workshop on Week 3-4 and afterwards.

Please let me know your opinion!
Thank you :)

#### Nature of issue?
- Existing feature enhancement
- New feature request

#### Feature enhancement details:
- Add Korean translation of log in/sign up; menus; (+examples if possible) 

#### New feature details:
- Add "Korean" button on the top right corner

### PR DESCRIPTION
**Pull request by yinhwa**
Fixes #1632

* initial Korean translation of p5 web editor, following the guideline provided in [developer_docs/translations.md](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/translations.md)
1. Newly added `translations > locales > ko` folder with `translation.json` file
2. Edited `Nav.jsx` and `i18n.js`

Thank you ☺☺

### CODE REVIEW

**Comment by catarak** [comment]
This is so rad! Let me know when it's ready to be reviewed. The cool think about the Release integration is that you can use the above link when you're ready to get some feedback from folks using the p5.js Editor!

**Comment by yinhwa** [comment]
@catarak Thank you Cassie for the kind guideline 🤩 yes, the releaseapp was so much helpful in testing out how the editor in Korean will be looking like in the end ! (And needless to mention, I'm looking so much forward to the newly updated mobile UI! they look amazing and even more accessible!)

I was thinking if it's ok with you, maybe the codes can be reviewed for now, so we can make sure that the basic set ups for the i18n is working alright? Then, I'll continue translating on the rest of the `ko`-relevant json files. Pls let me know what you think :) Thank you!

**Comment by catarak** [comment]
The code looks good to me! Switching to and from Korean is also working for me.

**Comment by yinhwa** [comment]
Thank you @catarak for the quick review! I'll continue working on the translation then :) Should I close this request and then re-open it with more translation added, or can it be merged to `develop` branch now? Pls lemme know what's comfortable for you!

**Comment by catarak** [comment]
You can keep adding to this PR! As you push more changes to your branch, it will get added to this PR. I'll merge it in when the translation is finished.

**Comment by raclim** [comment]
Hi @yinhwa! Just wanted to check-in on the status of these translations, or if you feel like it's ready to be merged, thanks! :)

**Review by raclim — APPROVED** [review]
So far, it looks great to me! I'm going to merge in the work that's been done for now!

**Pull request merged**
