### PR TITLE
Fix #2351 & cleanup `AddToCollectionList` component

### LINKED ISSUE #2351: PropTypes errors on `CollectionList`
### p5.js version

_No response_

### What is your operating system?

None

### Web browser and version

_No response_

### Actual Behavior

Adding a sketch to a collection works just fine, this is only a code-quality issue.

I'm seeing two prop-types validation errors on the `CollectionList` modal:
> checkPropTypes.js:20 Warning: Failed prop type: The prop `projectId` is marked as required in `CollectionList`, but its value is `null`.
>    in CollectionList (created by Connect(CollectionList))

> checkPropTypes.js:20 Warning: Failed prop type: The prop `collections[0].items[0].project.createdAt` is marked as required in `CollectionList`, but its value is `undefined`.
>    in CollectionList (created by Connect(CollectionList))

image

### Expected Behavior

It should not have errors.

### Steps:
1. Open a sketch
2. Click "File" menu
3. Click "Add to Collection"

### LINKED ISSUE #2363: "Add To Collection" doesn't work when viewing another user's sketch list
### p5.js version

_No response_

### What is your operating system?

None

### Web browser and version

_No response_

### Actual Behavior

When I click the "Add to Collection" button from another user's sketches page, I see a list of **_their_** collections.  Clicking on a collection to add or remove a sketch will give a 403 API error because I do not have permission to modify their collections (good).

image

These are codingtrain's collections, not mine:
image

The p5 user has no collections:
image

### Expected Behavior

I should see a list of **_my_** collections, and be able to add their sketch to my collection.

### Steps:
1. Go to https://editor.p5js.org/p5/sketches
2. Click on the 🔻 next to a sketch
3. Click "Add to collection"

### PR DESCRIPTION
**Pull request by lindapaiste**
Fixes #2363
Fixes #2351
Progress on #2179 

Changes:
- Convert `AddToCollectionList` to a function component.
- The only prop needed is `projectId` -- the id of the project to add to the chosen collection.
- Access Redux state via `useSelector` and `useDispatch`.
- Return a `Promise` from the `getCollections` action so that the component knows when loading is complete.
- Delete the `getProject` fetch as the project details are not used.
- Delete the `if` condition on the title as a user is always adding to their own collections, even when it's another user's project.
  - `AddToCollectionList.AnothersTitle` can be removed from translation files, but I didn't do this.
- Delete so many `PropTypes`.
- Delete imports for unused action creators (see #2179).  Only `/actions/collections` is used.  The other four are not needed.
- Removed over 100 lines!

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by PiyushChandra17 — APPROVED** [review]
Nicely Done

**Review by raclim — APPROVED** [review]
Thanks for working on this! 

I fixed some merge conflicts and also updated the props passed in `IDEOverlays` to reflect the new changes. Besides that, I don't think there should be any other major additional changes, but let me know if you spot anything!

**Comment by lindapaiste** [comment]
> Thanks for working on this!
> 
> I fixed some merge conflicts and also updated the props passed in `IDEOverlays` to reflect the new changes. Besides that, I don't think there should be any other major additional changes, but let me know if you spot anything!

@raclim there is definitely in a problem in the `IDEOverlays`.  There is no `this.state` so `projectId={this.state.sketchToAddToCollection.id}` won't work.  It looks like we want to keep the `projectId={params.project_id}` there and the only change to that file is to remove the line `username={params.username}`.

**Comment by raclim** [comment]
Thanks for catching that! I'll create a new issue now to quickly update it.

**Pull request merged**
