### PR TITLE
Fixes #2383

### LINKED ISSUE #2383: Cannot edit names on SketchList or CollectionList using keyboard controls
### p5.js version

_No response_

### What is your operating system?

None

### Web browser and version

_No response_

### Actual Behavior

The name turns into an input, but immediately closes.

This is because the "Enter" keyboard event which was used to select "Rename" is still being processed, and "Enter" will submit the form.

### Expected Behavior

The name should turn into an input and stay that way until you press "Enter" again.

### Steps:
1. Go to your `/sketches` page. 
2. Click somewhere on the page to focus.
3. Press "Tab" until you focus on the dropdown at the end of the table row.
image
4. Press "Enter" to open the dropdown.
5. Press "Tab" to focus on "Rename".
image
6. Press "Enter" to select "Rename".
7. Try to edit the name...you can't.

---

I came across this issue while working on #2382 and it will be fixed in that PR.  We could also implement a more immediate fix for just this issue if we deem it high-priority.

### PR DESCRIPTION
**Pull request by Ankush263**
Fixes #2383

Changes:

I have verified that this pull request:

* [✅] has no linting errors (`npm run lint`)
* [✅] has no test errors (`npm run test`)
* [✅] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [✅] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by Ankush263** [comment]
Should I need to change something here??

**Comment by lindapaiste** [comment]
We’ve gotten a lot of PRs in the past few days and I haven’t had a chance to review them all yet!

We were previously looking at the keyup event.  With your fix we are now looking at both the keydown (fired first) and the keyup.  Is it necessary to check for “enter” on both events?  It seems a little odd, but I need to check out your branch and play with it to see how it behaves.

**Comment by Ankush263** [comment]
Yeah, it's odd to use both keyUp and keyDown, I tried different approaches, but this works perfectly .

**Comment by raclim** [comment]
Since it's been a while since this PR has been updated, I've marked it with a "closing soon" label, which signifies that this PR will be closed in 10 days. Please feel free to revisit this to make any further updates or indicate that you would like to keep this open!

**Pull request closed without merging**
