### PR TITLE
Update/Updated Generative Design Examples

### PR DESCRIPTION
**Pull request by joeyklee**
Hello! 

The Generative Design group recently did a review and update of the Generative Design Examples (see: https://github.com/generative-design/Code-Package-p5.js/commit/c40b36e57620ece7449358a33e1f81544e8146ce). We'd love to do a bulk update of the examples in the p5 web editor when you get a chance! 

If you don't mind running the `npm run fetch-examples-gg` so that all the sketches in the `generative-design` account are updated, that would be super. We currently have our examples running directly on [our site](http://www.generative-gestaltung.de/2/sketches/?01_P/P_1_1_1_01) and include a link to the P5 editor for people to jump into the code if they are curious :) 

Thanks so much @catarak 🌈❤️✨!

### CODE REVIEW

**Comment by catarak** [comment]
I noticed that in the PR you linked, it uses p5 version 0.7.2. Do you want to change the p5 version here to 0.7.1 or 0.7.2?

**Comment by joeyklee** [comment]
@catarak - ah yes! Thanks so much for catching this one. Yes, the latest version would be best. I've commit the changes in https://github.com/processing/p5.js-web-editor/pull/774/commits/e261b5062a662faf266ec36e3f3a3eb08bf436fb Thanks so much!

**Comment by catarak** [comment]
great! i'll merge this in now.

**Comment by joeyklee** [comment]
Super! Thanks so much @catarak  🌈🙌

**Comment by catarak** [comment]
@joeyklee just ran the script to update the examples, let me know that it worked!

**Comment by joeyklee** [comment]
@catarak - thanks! I switched from [raw git](https://rawgit.com/) to [githack](https://raw.githack.com/) I think there might be some issues with the way that images are served up via those URLs. 

E.g. https://editor.p5js.org/generative-design/sketches/P_4_1_2_02 doesn't load the image via:
* 🙅‍♂️ - does not load:  https://raw.githack.com/generative-design/Code-Package-p5.js/master/01_P/P_4_1_2_02/data/pic.png
* ✅ - loads: https://raw.githubusercontent.com/generative-design/Code-Package-p5.js/master/01_P/P_4_1_2_02/data/pic.png

Just flagging this in case you need to switch any of your other examples over from rawgit to something else. I will look into the fix here.

**Pull request merged**
