### PR TITLE
Enable Creation of .xml files

### LINKED ISSUE #1741: Cannot upload or create .xml file into editor.p5js
Hi everyone,

Teaching the different data file format, I need to upload a .csv, .json and .xml file into p5.js web editor. Doing this, the editor  gives an error message (after upload trial) : 'You can't upload files of this type'. When trying to create an empty .xml file, the editor says: 'Invalid file type. Valid extensions are .js, .css, .json, .txt, .csv, .tsv, .frag, and .vert.' So it's impossible to work with .xml files...

I don't see any reason to forbid adding .xml file to an online Processing project. Even more when p5.js librariy provides a loadXML() function and resources in order to process .xml data. Is it a bug and could it be corrected?

Thanks a lot for your attention and help!

Laurent
 
- Web browser and version: Google Chrome Version 86.0.4240.75 (Build officiel) (32 bits)
- Operating System: Windows 10 Pro 64 bits version 1909 / 18363.1316

### PR DESCRIPTION
**Pull request by SundeepChand**
Fixes #1741

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

Hello @catarak. I have not enabled syntax-highlighting for XML files. How can I enable that in codemirror?

### CODE REVIEW

**Comment by SundeepChand** [comment]
create release environment

**Comment by SundeepChand** [comment]
create release environment

**Comment by catarak** [comment]
You also need to update the translations (`NewFileModal.InvalidType`) to add `.xml` files. I think in all of the translations it's just a list of extensions so you don't need to speak that specific language.

**Comment by SundeepChand** [comment]
Hello @catarak, please let me know if anything is missing in the PR.

**Review by catarak — APPROVED** [review]

**Comment by catarak** [comment]
working great for me ✨

**Comment by Wildernesss** [comment]
Hello Cassie (@catarak ). I don't know if I'm doing something wrong but on my side nothing has changed: cannot create, upload or rename to .xml files. For .xml and .html files I try to create I still get the following message: 'Invalid file type. Valid extensions are .js, .css, .json, .txt, .csv, .tsv, .frag, and .vert.' Trials to rename a .txt file to .xml do nothing: the .txt extension remains, without any message from editor. Uploading .html file is possible, but not .xml file ('You can't upload files of this type' message'). Does it work for you with the p5js editor on production now or with a development version that will be pushed in production later? Thanks a lot to everyone for your work on these issues! :o)

Laurent

PS: sketch I've used for testing is [this one](https://editor.p5js.org/bardyl/sketches/FN11uV_DZ). Tried with Google Chrome and Firefox, cache beeing clear and editor reloaded before testing.

**Comment by catarak** [comment]
@Wildernesss this is because this change has not yet been deployed to production! I'm scheduling a deploy this weekend so look out for this change very soon 😄

**Pull request merged**
