### PR TITLE
Fix: Incorrect translation for Terms & Conditions on Signup page

### LINKED ISSUE #3274: the t&c portion of the signup page isn't translated correctly
### p5.js version

_No response_

### What is your operating system?

None

### Web browser and version

_No response_

### Actual Behavior

it isn't being translated

### Expected Behavior

it should be translated

WhatsApp Image 2024-11-13 at 6 48 48 AM

### Steps:
1. 2. 3.
### Snippet:
```js

// Paste your code here :)

```

### PR DESCRIPTION
**Pull request by Deepeshjoshi123**
Fixes #3274

Changes:

Fixed translation issue for "By signing up, you agree to the Terms of Use and Privacy Policy" not displaying correctly in Simplified Chinese (zh-CN) and Traditional Chinese (zh-TW).

I have verified that this pull request :

has no linting errors (npm run lint)
has no test errors (npm run test)
is from a uniquely-named feature branch and is up to date with the develop branch.
is descriptively named and links to an issue number, i.e. Fixes #3274

Screenshot 2024-12-21 195933

### CODE REVIEW

**Comment by raclim** [comment]
Thanks for working on this! We currently have an update these translations in #3275, which we're waiting on native speakers to vet and verify. Since we already have an open PR for this I'm going to close this one for now, but please feel free to give input on the translations there!

**Comment by Harshit-7373** [comment]
@Deepeshjoshi123  @raclim  This same issue arose in issue #3274 . I worked on it and resolved it in my PR. Kindly review it.

**Comment by Harshit-7373** [comment]
@Deepeshjoshi123 @raclim 

Screenshot 2025-02-11 at 9 01 45 PM

In the uploaded image, you can see that the entire line "By signing up, you agree to the p5.js Editor's" is now correctly displayed according to the selected language.

**Comment by Harshit-7373** [comment]
@Deepeshjoshi123 @raclim  
Screenshot 2025-02-11 at 9 01 45 PM
In the uploaded image, you can see that the entire line "By signing up, you agree to the p5.js Editor's" is now correctly displayed according to the selected language.

**Pull request closed without merging**
