### PR TITLE
Check mode for current doc when errors occur

### LINKED ISSUE #588: Console errors highlight wrong file
#### Nature of issue?

- [X] Found a bug

#### Details about the bug: 

If you run a sketch and it throws an error, the line of any file that is selected will be highlighted, rather than switching to the file that has the error. The expected behavior is that it would switch to the file that threw the error.

- Web browser and version: Chrome (also this is really N/A)
- Operating System: Mac OSX (also N/A)
- Steps to reproduce this:

1. open a new sketch
2. make a syntax error in `sketch.js`
3. switch to `index.html`
4. click play and run the sketch
5. `index.html` will still be selected and the line number that threw the error in `sketch.js` will be highlighted.

### PR DESCRIPTION
**Pull request by shinytang6**
Before your pull request is reviewed and merged, please ensure that:

* [ ] there are no linting errors -- `npm run lint`
* [ ] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [ ] your pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

Thank you! Fixes #588

### CODE REVIEW

**Comment by catarak** [comment]
awesome! just for the sake of documentation, in the future, could you submit an issue first before submitting a PR?

**Comment by shinytang6** [comment]
Forgot it :disappointed:

**Comment by catarak** [comment]
no worries, it happens!

**Comment by catarak** [comment]
this doesn't quite fix #588. this will still happen if there are multiple javascript files and the user is open to a JS file that doesn't have the error. this at least helps so i'm going to leave it merged.

**Comment by shinytang6** [comment]
Thanks, l will continue to investigate

**Pull request merged**
