### PR TITLE
Make saving more user-friendly

### LINKED ISSUE #560: Make saving more user-friendly
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:

1. Saving file through ctrl+s when user is unlogged doesn't popup the ErrorModal.
2. Although Save option is diabled when the user is not the owner of the sketch, l think it  will be better if another ErrorModal pops up when using ctrl+s ?

### LINKED ISSUE #567: Fail to close the modal after login
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Steps to reproduce this:

1. Open the editor, not logged in 
3. Press the Save button. It will tell you to login or signup.
4. Login.
5. it will still show a modal asking you to login or signup.

### PR DESCRIPTION
**Pull request by shinytang6**
Before your pull request is reviewed and merged, make sure you

* [x] there are no linting errors -- `npm run lint`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master. If you're asked to make more changes make sure you rebase onto master then too!
* [x] pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

Thank you! Closes #560 , Fixes #567

### CODE REVIEW

**Comment by catarak** [comment]
not sure if this is the right way to handle this—just added a thought on #560!

**Comment by catarak** [comment]
i found a weird bug, and here are the steps to reproduce:

1. Open the editor, no logged in (I recommend an incognito window)
2. Open an existing sketch (one of the examples is easiest)
3. Try to save it using command + s. It will tell you to login or signup
4. Login.
5. Try to save it again using command + s. It will properly fork it but then it will also show a modal asking you to login or signup. 

This does work if you are already logged in and navigate to a sketch that you do not own!

**Comment by shinytang6** [comment]
l think it should be a real bug and doesn't matter with my changes because it can be reproduced in current version:)
Just fixed it in this PR and l will report that issue :no_mouth:

**Comment by catarak** [comment]
got it, thanks for fixing it!

**Comment by shinytang6** [comment]
@catarak It seems there are still some bugs related to that PR. 
1. l shouldn't delete the `closeOverlay={this.props.hideErrorModal}`
2. when you log in normally and save the changes through command/ctrl s, it still pops up the ErrorModal

l will try to fix that as soon as possible

**Pull request merged**
