### PR TITLE
Rohanjadhav -  fixes #3083

### LINKED ISSUE #3083: p5js Logo On Editor Redirect to My Sketches
### Increasing Access

@beccyabraham @raclim and I discussed having the p5 logo in the top left redirect to "my sketches" or p5js.org because it seems like it should lead to somewhere.
image

### Feature enhancement details

We discussed the p5 logo acting as a home page for editor.p5js.org as most newcomers click on it expecting to lead somewhere. It could lead to the p5js.org website and save the sketch or ask the user to login and display their sketches.

### PR DESCRIPTION
**Pull request by rohanjadhav05**
Fixes #3083

When clicking on the PS5 logo, the user will be navigated to their saved sketches if they are logged in. If the user is not logged in, they will navigate to (https://p5js.org/)

Changes:
     
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by rohanjadhav05** [comment]
When clicking on the PS5 logo, the user will be navigated to their saved sketches if they are logged in. If the user is not logged in, they will navigate to (https://p5js.org/)

**Review by raclim — CHANGES_REQUESTED** [review]
Thanks for your work on this! I think this seems like a good solution so far. 

It's not passing the tests so far, so I think you might need to update the snapshots! You can do that by running this line: `npm run test -- -u`. You can also look further into this through the [Contributor Docs on Testing](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/testing.md).

**Comment by rohanjadhav05** [comment]
Hello @raclim,  I have updated the snapshot and added the commit can you please have look towards this PR.

Thank you

**Review by raclim — APPROVED** [review]
I think this looks good to me! Thanks so much for your work on this!

**Pull request merged**
