### PR TITLE
[WIP] Fixes #769

### LINKED ISSUE #769: Broken error messages
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Firefox 64.0
- Operating System: Manjaro Linux
- Steps to reproduce this:
It seems a recent commit has broken the error messages. When making an error in the sketch (for instance using an undeclared variable) no error message is shown in the editor's console, although one is present in the browser's web console.
Moreover, if I use `console.error("Something something")` the editor simply crash (with a React log).
I think the bug was introduced in a recent commit, because one of my local branches pointing at 61dd0bb4d0b220f57667e8e60fce187dd6964d67 is working flawlessly. I'm going to investigate further to find the exact commit causing the bug.

**EDIT**: Weirdly enough, the editor doesn't crash when testing it locally with the latest version of the master branch, but it does still show errors related to `consoleEvent.arguments` in the browser's console. I'm guessing these problems are related to the changes related to #761 and the following multiple corrections.

### PR DESCRIPTION
**Pull request by Vertmo**
Before your pull request is reviewed and merged, please ensure that:

* [X] there are no linting errors -- `npm run lint`
* [X] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [X] your pull request is descriptively named and links to an issue number, i.e. `Fixes #123`
* [ ] you have completed all the changes you wanted to do

Fixes #769
As the title indicates, I'm trying to fix bugs related to error logging in the console. I have already fixed in my first commit the crash when using `console.error()`, and I'm working on making error logs available again.

### CODE REVIEW

**Comment by catarak** [comment]
i was going to say that i could fix this rather than just comment it out, but it seems like you're already on top on it 😸

**Comment by catarak** [comment]
the file `consoleUtils.js` should use the `console-feed` `Encode` function to post console messages.

**Comment by catarak** [comment]
i just spent a bunch of time steeped in that code so i'm happy to tackle this. I'm also trying to merge in #667 which is related to all of this.

**Comment by Vertmo** [comment]
Actually, it would indeed probably be better if you fixed the remaining problems, since I'm not sure how to fix the line numbering problem ^^ Thanks !

**Pull request closed without merging**
