### PR TITLE
[WIP] display the script error caused by external library

### PR DESCRIPTION
**Pull request by shinytang6**
Before your pull request is reviewed and merged, make sure you

* [x] there are no linting errors -- `npm run lint`
* [x] code is in uniquely-named feature branch, and has been rebased on top of latest master. If you're asked to make more changes make sure you rebase onto master then too!
* [x] pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

Thank you!

### CODE REVIEW

**Comment by shinytang6** [comment]
partly relates to #468 :)
fixes e.g. 
```
let txt;

function setup() { 
  createCanvas(400, 400);
  text(txt,100,100);
} 
```

```
function setup() { 
  createCanvas(400, 400);
} 

function draw() { 
  background(220);
  rotateZ(100);
}

```

Still need to know more about how to display lineNumber when the error caused by external library.
Currently it only shows the error line in e.g p5.min.js :)

**Comment by catarak** [comment]
this is interesting and i'm not sure how to handle it. the issue is that the user is using the library improperly. i think the ideal case is that we would get the full stack trace of the error, figure out the line that is in one of the files in sketch itself, and put the error on that line, and show the full stack trace in the console. can you get the whole stack trace? there's a script called `hijackConsole.js` that sends the console messages through a message channel to the web editor console.

**Comment by shinytang6** [comment]
The first one seems to be working properly now:)
```
function setup() { 
  createCanvas(400, 400);
} 

function draw() { 
  background(220);
  rotateZ(100);
}
```
this one doesn't show whole stack trace, only reports `Uncaught not supported in p2d. Please use webgl mode`, l think it is relevant to the p5.js's console?

**Comment by catarak** [comment]
cool, i like where this is going! i wonder if it would make sense to send the whole stack back to the in-window console? is it too confusing for a coding newbie? 
screen shot 2018-03-01 at 1 43 31 pm

vs.

screen shot 2018-03-01 at 1 43 07 pm

is there potentially a happy medium? as someone with coding experience i found the error confusing because i was like, "toString isn't being called on this line," and i think it's important to say that the error is being thrown in another file, but is a result of the user not using the library correctly, and therefore there still is in error. thoughts @lmccart & @shiffman?

i also just changed the p5 version to the non-minified version to see if the friendly errors system would catch it, and it doesn't.

**Comment by shiffman** [comment]
I think the ideal outcome would be for the error to read something like:

```
p5 cannot render undefined text. sketch: line 5
```

So maybe this is a matter of adding this particular scenario to the friendly errors system?

If rewriting the error is not an option I think I would stick with the single error over the full stack trace for the web editor? We could reconsider this based on any future work on the console itself #7 -- for example, maybe the full stack trace could "unfold"?  But my instinct says that the full stack trace is more scary than helpful, and it would be available in the chrome developer tools should someone want to look.

**Comment by catarak** [comment]
makes sense to me!

**Comment by shinytang6** [comment]
@catarak @shiffman so what is the verdict on this one currenly:)

**Comment by shiffman** [comment]
For now let's go with "Uncaught TypeError: Cannot read property 'toString' of undefined (sketch: Line 5)". I can add an issue regarding a friendly error for this separately in the p5.js repo.

**Comment by shinytang6** [comment]
That will be fine :smile:

**Comment by catarak** [comment]
cool, then this PR is good to be merged.

**Pull request merged**
