### PR TITLE
Update public_api.md (changes made)

### LINKED ISSUE #1769: Update public_api.md in developer_docs to set UI_ACCESS_TOKEN_ENABLED=true
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Hello @catarak. While working on #975 it took me a few hours to figure out how to enable access token UI in settings page. I think it would be nice if it is mentioned in the docs to set  `UI_ACCESS_TOKEN_ENABLED=true` in the .env file. I would like to work on this.

### PR DESCRIPTION
**Pull request by soniyadotp**
Fixes #1769

Changes:

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by PiyushChandra17 — APPROVED** [review]
Nicely Done 👍

**Review by raclim — CHANGES_REQUESTED** [review]
Thanks so much for working on this, this is great so far! 

I think one change that I feel would make more sense is for the added section "Enabling Access Token UI in Settings Page" to be higher up in the document, such as in between the sections "Models" and "Sketch".

**Comment by soniyadotp** [comment]
> Thanks so much for working on this, this is great so far!
> 
> I think one change that I feel would make more sense is for the added section "Enabling Access Token UI in Settings Page" to be higher up in the document, such as in between the sections "Models" and "Sketch".

Did some changes, is it good to go?

**Review by raclim — APPROVED** [review]
Thanks for working on this!

**Pull request merged**
