### PR TITLE
Delete legacy mobile UI - Fixes #2557

### LINKED ISSUE #2557: `localhost` displays incorrect mobile design due to legacy `mobileFirst` components
### p5.js version

2.9.0

### What is your operating system?

None

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

p5 sketches examples not showing in full height on `mWeb(chrome)` and `mWeb(safari)`, it's not responsive.
ios
android

### Expected Behavior

p5 sketches examples should work properly on small screens ie. mWeb(chrome) and mWeb(safari). It should be responsive.

### Steps:
1. Open the editor app on either mWeb(safari) or mWeb(chrome)
2. Press the three dots
3. Press on Examples
4. Notice the example page, it should take the full height of the screen

### PR DESCRIPTION
**Pull request by lindapaiste**
Fixes #2557 
Progress on #2555 

This will clear up a lot of developer confusion and ensure that what contributors see on `localhost` matches what we are using in production.

Changes:
- Delete `MOBILE_ENABLED` feature flag from `.env` as the new responsive design is always enabled.
- Delete `mobileFirst` HOC which was previously used to show the experimental mobile design on `localhost` when the `MOBILE_ENABLED` flag was set.
- Delete component-switching via `mobileFirst` from the app routing.
- Delete the components `MobileIDEView` etc. which are no longer used anywhere.
- Delete elemental UI components (`ActionStrip`, etc.) which were only used in those views.
- Moved remained component `IconButton` to the `/common` folder and deleted the `client/components/mobile` folder.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by PiyushChandra17 — APPROVED** [review]
Nicely Done.

**Comment by raclim** [comment]
Thanks for working on this! Glad to see some of the errors that were starting to pop up from the legacy components resolved!

I'm wondering if you think if the files within the [components/mobile](https://github.com/processing/p5.js-web-editor/tree/develop/client/components/mobile) folder should be deleted here too?

**Comment by lindapaiste** [comment]
> I'm wondering if you think if the files within the [components/mobile](https://github.com/processing/p5.js-web-editor/tree/develop/client/components/mobile) folder should be deleted here too?

I’ll take a look.  I think IconButton is the only one still in use.  We can move that to a different folder.

**Comment by raclim** [comment]
Just did a check as well and think you're right! I think deleting that file and moving the IconButton would be great here, but also could merge in this PR as is!

**Comment by lindapaiste** [comment]
> Just did a check as well and think you're right! I think deleting that file and moving the IconButton would be great here, but also could merge in this PR as is!

I just deleted those files. 🪓 

Next up...we need to delete the translations for the components that we deleted, but I want to give that a closer look because some of those phrases we may want to move rather than delete ("My Stuff" is one).  There's a few places in the new code where phrases are not translated. `//TODO`

**Review by raclim — APPROVED** [review]
This is great, thanks so much again for cleaning this up!

**Pull request merged**
