### PR TITLE
Add installation.md Korean Translation

### PR DESCRIPTION
**Pull request by min-kim42**
I have verified that this pull request:

* [X] has no linting errors (`npm run lint`)
* [X] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [X] is descriptively named and links to an issue number, i.e. `Fixes #123`

Addresses #1350

### CODE REVIEW

**Comment by catarak** [comment]
My suggestion in #1356 also affects this PR!

**Comment by mjaything** [comment]
same here! I'll add future translations in the same way too!

**Comment by catarak** [comment]
This PR also accidentally adds the file `translations/ko/installation.md` which should be removed!

**Comment by catarak** [comment]
I think the contents of `Installation.md` somehow got deleted? When to go to "files changed" in this PR the file is empty 😢

**Comment by mjaything** [comment]
My mistake! Thanks, restored it!

**Comment by catarak** [comment]
Hmmm, do you think that `installation.md` should be in `translations/ko/developer_docs` to match the english organization? It's a little confusing organizing all of this stuff, given that GitHub needs files to be in certain places (in the root or in `.github`) in order to use them.

**Comment by mjaything** [comment]
I agree with you that these documents that belong to `developer_docs` should be separated from other documents. If both the translated `README.md` of the root and the translated `README.md` of `developer_docs` are put into `translations/ko`, it would be confusing.

Before talking about the ideal file structure of translated documents and files for internationalization, I'm not 100% sure what you mean that Github requires files to be in certain places.

I've found out that [community health files](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file)(CONTRIBUTING, CODE_OF_CONDUCT and etc) should be in the root or in `.github` or in `docs`. By doing so, GitHub will recognize and automatically surface your README to repository visitors. Also, when someone opens a pull request or creates an issue, they will see a link community health files as shown in the screenshot.

Code

Do you mean that translated community health files should also be in these folders, for above reasons? I've checked to see if there's any feature in github that detects preferred language of the user and displays these community health files in certain language. There were [some people asking](https://github.com/github/markup/issues/899) for such feature, but there isn't one yet. Please let me know if there are other reasons to put certain translated files in certain places. :-)

**Comment by mjaything** [comment]
If we don't have any constrains, we could organize files as we like. It's probably too early, but maybe organization for files related to internationalization other than documentation should also be taken into account. There doesn't seem to be constraints on location of files when loading translations. At least for i18next, you can configure the path to resources, according to the [i18next-gitbook](https://github.com/i18next/i18next-gitbook/blob/master/loading-translations.md).

I've collected several tips on file organization, to have clearer idea on this issue:
- clear hierarchical structure that makes meaningful URLs, so that you could immediately tell where you are navigating
- organize content by topic, not by type
- every data element should be mastered (or edited) in only one place to avoid overlaps and duplication(SSOT, Single Source of Truth)

**Comment by mjaything** [comment]
For now, as we don't have definite file structure for internationalization files other than documentation, I think it would be good enough to put translated `README.md` in the root in `translations/ko` directory, and put `README.md` of developer_docs in `translations/ko/developer_docs`.

If there is a need for significant change in file structure due to to-be-added internationalization files, we could rearrange things. I don't think it would be too complicated. Please let me know what you think! :-)

I've looked into several (fully and partially) localized projects to see how they organize files. Just in case this might be useful in the future, I will share several possible options that I have observed from other projects.

a) Inside `translations` folder, create folders that match original file structure for each language.
e.g. `p5.js-web-editor/translations/ko/developer_docs/installation.md`
Reference: [fullPage.js](https://github.com/alvarotrigo/fullPage.js)

b) Inside `translations` folder, put translated files with language abbreviation in the file name. 
e.g. `p5.js-web-editor/translations/installation.ko.md`
Reference: [First Contributions](https://github.com/firstcontributions/first-contributions/tree/master/translations)

c) For translated documents, create folders for each language inside `developer_docs` folder. For other files related to internationalization, put them in `translation`.
e.g. `p5.js-web-editor/developer_docs/ko/installation.md`
Reference: [p5.js](https://github.com/processing/p5.js/tree/master/contributor_docs), [three.js](https://github.com/mrdoob/three.js/tree/dev/docs/manual)

d) In each original directory, put translated files with language abbreviation in the file name. 
e.g. `p5.js-web-editor/developer_docs/installation.ko.md`
Reference: [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts), [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped)

e) Create separate repository for translated documentation, and simply put link to it in README. Some deploys website for documentation.
Reference: [Gulp](https://github.com/gulpjs/gulp/tree/master/docs), [Pug](https://github.com/pugjs/pug), [Netdata](https://github.com/netdata/localization), [Sails](https://github.com/balderdashy/sails-docs)

**Review by raclim — APPROVED** [review]

**Pull request merged**
