### PR TITLE
Add toast to notify when creating new file. Fixes #1140

### LINKED ISSUE #1140: Notification should appear when new sketch is opened
#### Nature of issue?

- New feature request

#### Details about the bug: 
Capture

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
When a user clicks on 'New' option, the toast should appear stating the new file is created.
As of now if a user clicks on 'New', only the file name changes else there is no notification regarding new file opened. 

#### New feature details:

### PR DESCRIPTION
**Pull request by RickBr0wn**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

As title states this PR adds a 'toast' notification to alert the user when a new file has been created. Fixes #1140

### CODE REVIEW

**Comment by RickBr0wn** [comment]
Good thinking. If you're happy for me to continue, I will fix that.

**Comment by RickBr0wn** [comment]
I am just thinking about this. What case would there be, for the _file/new_ to be clicked and a new file not be created? I can see in the reducer it just returns initialState. How would I replicate that case (_file/new_ & no new file) locally?

**Comment by catarak** [comment]
i don't think that clicking "new" would fail! i think the copy in the toast should read "New Sketch Created!" rather than new file, since it's creating a new sketch rather than a new file.

**Comment by RickBr0wn** [comment]
@catarak I think initially I misunderstood the instruction from @plxity 
> @RickBr0wn There should be an error message displayed in case a new file is not created.

I think it was meant to mean that a notification is also required when creating a new file with unsaved changes (See f675190).

As for the Sketch/File question, I actually deliberated this for a little time. I finally decided to follow the fact that the menu option is File, but I can easily rectify this.

**Comment by catarak** [comment]
looks good to me! i ended up changing the copy to "opened new sketch" as the sketch isn't initially saved.

**Pull request merged**
