### PR TITLE
Feature/autoclose brackets quotes

### LINKED ISSUE #941: Autocomplete bracket and quotation mark pairs
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

I know this has been brought up first in #55. The case was made that beginners might find it confusing. I agree with that. The first impression can certainly be confusing. However, within two-three days of programming, I believe they will realise how nice it would be to have brackets autocomplete themselves :) Not only just brackets, but also double and single quotes.

I believe this can be a useful toggle switch to have in the settings. @catarak thoughts? if you're ok with it, I would wish to work on it!

### PR DESCRIPTION
**Pull request by sagar-joshi**
Fixes #941 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #941 `

### CODE REVIEW

**Comment by sagar-joshi** [comment]
@catarak  kindly let me know if the changes are okay

**Comment by catarak** [comment]
Thanks for working on this! You know, the more that I've watched folks new to programming code, the more I think this setting should be on by default. I updated this PR accordingly. Also, @oruburos, would you mind translating the following phrases to Spanish? Thank you!

`"Autoclose Brackets and Quotes"`
`"autoclose brackets and quotes on"`
`"autoclose brackets and quotes off"`

**Comment by oruburos** [comment]
Hi @catarak sure, here are my suggestions, notice that I used capital letters to start the second and third options, up to you if you want to maintain consistency with the current style.

* >  "Autoclose Brackets and Quotes"
   >"Cerrar automáticamente llaves y comillas"

* >"autoclose brackets and quotes on"
   >"Activar cierre automático de llaves y comillas"

* >"autoclose brackets and quotes off"
   "Desactivar cierre automático de llaves y comillas"

**Comment by catarak** [comment]
thank you @oruburos!!

**Review by catarak — APPROVED** [review]

**Comment by oruburos** [comment]
> thank you @oruburos!!

You're welcome, is cool to see that the translations module is being used.

**Pull request merged**
