### PR TITLE
After claiming size limit of 250MB storage, the Upload File button will be disable

### LINKED ISSUE #2080: Error message claiming size limit of 250MB reached
- p5.js version: web editor
- Web browser and version: Safari Version 15.6.1
- Operating System: MacOSX 10.15.7

When I attempt to upload a file to a new or existing sketch, I receive the following response:

“Error: You cannot upload any more files. You have reached the total size limit of 250 MB. If you would like to upload more, please remove the ones you aren’t using anymore by in your [assets](https://editor.p5js.org/assets).”

My account shows a total asset size of 344.86 MB, exceeding the 250 MB limit. However, after deleting a number of files, my calculations result in a total asset size of only 143 MB. I can't figure out this discrepancy that has persisted for several months. Thanks in advance for your help.

### PR DESCRIPTION
**Pull request by swrno**
Logic Implemented: If the currendSize >= sizeLimit then the `Upload File` button will be automatically disabled

Fixes #2080

Changes:

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by Swarnendu0123** [comment]
Hey @raclim, I got stuck into some linting error. Can Your please help me to fix the linting error.

**Review by PiyushChandra17 — COMMENTED** [review]
Nicely Done 👍

**Comment by swrno** [comment]
> Nicely Done 👍 

Thanks @PiyushChandra17 for your review

**Comment by swrno** [comment]
@lindapaiste @raclim Can you please review the PR? and give me your feedback.

**Pull request closed without merging**
