### PR TITLE
Bulk Sketch Download Feature (Fixes #1939)

### LINKED ISSUE #1939: Feature-request: download all sketches as zip
Apologies if this already exists, but would be very useful to be able to bulk download all sketches from the 'My Sketches' page

### PR DESCRIPTION
**Pull request by dwight9339**
Fixes #issue-number

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by dwight9339** [comment]
Here's my fix for issue #1939. It's able to combine all projects into a single zip file but we're going to need to do a serious refactor the bundleExternalLibs() function in project.controller.js if we want to add external dependency files to each project. I'm also not sure about the placement of the "Download all" button on the sketches page. Thanks

**Comment by dwight9339** [comment]
Managed to add external lib bundling to bundled project files without doing any major refactoring after all.

**Comment by NanoDano** [comment]
If there is anything I can do to help get this feature over the finish line, this is something I'd love to see. It is also similar to this PR about downloading collections as a zip: https://github.com/processing/p5.js-web-editor/pull/1997

**Comment by raclim** [comment]
Hey @dwight9339, sorry for the delay in reviewing this! 

Would you be interested in revisiting this again? I'd love to see your work on this come to fruition in the near future!

**Comment by raclim** [comment]
I'm going to close this for now, but please feel free to rework this PR or create a new one regarding this feature!

**Pull request closed without merging**
