### PR TITLE
Added right-clicked

### LINKED ISSUE #2359: Dropdown menu items cannot be right-clicked
### Increasing Access

Allows users to open a link in a new tab, etc.

### Feature enhancement details

I wanted to open "My Collections" in a new tab, but the menu closed immediately when I right-clicked the link.  Opening in a new tab is possible via `Ctrl` + click.  But right-click should work too.
image

### PR DESCRIPTION
**Pull request by sdivyanshu90**
Fixes #2359

Changes:
Added target

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)

### CODE REVIEW

**Comment by sdivyanshu90** [comment]
Hi @lindapaiste and @raclim, could you review my pull request and provide feedback? Thanks!

**Comment by lindapaiste** [comment]
Hey, this wasn’t exactly what I had in mind.  I think the links should open in the same window most of the time.

The issue has to do with the event handling.  I think it’s an onMouseDown in the Nav?  We would want to ignore the behavior that closes the menu if the mouse event is a right-click event.  You can explore the MDN docs to figure out what property of the MouseEvent we should be looking at to see if it’s a right click.  There may also be a way to do it by looking at the e.defaultPrevented property?

**Comment by sdivyanshu90** [comment]
Apologies for the oversight. I didn't notice this earlier, but I'm now working on a new PR to address the issue.

**Comment by Biki-das** [comment]
https://github.com/processing/p5.js-web-editor/assets/72331432/81528c00-0455-441c-bcbe-9b5bb79a7c3f

i think i understood the problem correctly now, the `mouseup` event makes the `setDropdownOpen` to none resulting in the drop down closed, i have added a filter to look for right click button and just doing an early return. this is the behaviour on right click currently.

**Comment by sdivyanshu90** [comment]
Hello @lindapaiste,

I've opened a new PR #2425 that addresses and can potentially close this issue. I would greatly appreciate it if you could review it. Your feedback and insights would be valuable in making sure that the solution is good.

Thank you in advance for your time and assistance!

**Comment by Biki-das** [comment]
@sdivyanshu90 stop raising duplicate PR's

**Comment by sdivyanshu90** [comment]
Thank you for your input. I want to clarify that I've been actively working on this issue. It came as a surprise to me when I noticed your PR, as I was already in the process of addressing it. Let's coordinate our efforts to avoid submitting duplicate PRs in the future. Your collaboration is appreciated.

**Comment by Biki-das** [comment]
> Thank you for your input. I want to clarify that I've been actively working on this issue. It came as a surprise to me when I noticed your PR, as I was already in the process of addressing it. Let's coordinate our efforts to avoid submitting duplicate PRs in the future. Your collaboration is appreciated.

close your PR since i have already raise one and i am early!

**Pull request closed without merging**
