### PR TITLE
Patched console.logs to work only in dev mode (#853)

### PR DESCRIPTION
**Pull request by siddhant1**
I have verified that this pull request:

* [ x] has no linting errors (`npm run lint`)
* [ x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by siddhant1** [comment]
@catarak , the package-lock will again conflict :p , maybe we can setup .nvmrc for consistent node version across the project

**Comment by catarak** [comment]
thanks for working on this! it seems like you can remove console.* statements using uglify, which is already installed. so why not do that instead of adding another dependency?

**Comment by siddhant1** [comment]
Yes , I think we can also do it with webpack and uglifyJs and since we are already using uglifyJs plugin that'd be a better approach

**Comment by siddhant1** [comment]
Moved to #890

**Pull request closed without merging**
