### PR TITLE
Refactored all HTTP requests to use axios

### LINKED ISSUE #975: Refactor all HTTP requests to use axios
As I was working on #521 , we use a package named 'request' which only supports callbacks.
I think we should switch to request-promise alternative.
LInks :- https://github.com/petkaantonov/bluebird
https://github.com/request/request-promise-native

@meiamsome @catarak Should I switch it up?

### PR DESCRIPTION
**Pull request by SundeepChand**
Fixes #975 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

Hello @catarak, please review this. I have not been able to test `fetch-examples-ml5.js` as I could not find the `EDITOR_API_ACCESS_TOKEN`.

### CODE REVIEW

**Comment by catarak** [comment]
I can't even tell you the joy this brings me. Feels so good to clean up code! Since this is touching on some fundamental stuff I'm going to test this carefully.

**Comment by catarak** [comment]
Everything seems to be working for me except for fetching the ml5 examples. However, this could be because of some necessary changes in #1762—I think I'm going to get that one merged in first, handle the git conflicts, and see if that fixes it.

**Comment by SundeepChand** [comment]
I've tested `examples-ml5.js` & its working for me now.

**Review by catarak — APPROVED** [review]

**Comment by catarak** [comment]
The `ml5` script is also working for me! All of the other functionality this touches also is working for me:
- p5.js example fetching script
- generative design example fetching script
- downloading sketches
- using sketch assets by url
- syntax highlighting script

**Pull request merged**
