### PR TITLE
For #675, needs more testing to know if it fixes it!

### PR DESCRIPTION
**Pull request by catarak**
Before your pull request is reviewed and merged, please ensure that:

* [X] there are no linting errors -- `npm run lint`
* [X] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [X] your pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

Thank you!

@GaurangTandon, I was testing your PR and still running into the bug from #675, and then ended up digging into how to fix the issue, and then, just, ended up trying out a new fix. I appreciate you working on these and helping me find the issue!

### CODE REVIEW

**Comment by catarak** [comment]
🙏 this actually fixes #675, which has been super annoying. grateful that everyone has been putting up with this.

**Comment by GaurangTandon** [comment]
> I was testing your PR and still running into the bug from #675,

Hey @catarak, I was following [this procedure](https://github.com/processing/p5.js-web-editor/issues/675#issuecomment-420805393) of replicating the bug. [This video](https://youtu.be/5Ao_uuhD1H0) - running at my PR above - does not seem to have the issue, even after doing the procedure twice.

Were you following a different procedure?

**Comment by shiffman** [comment]
Yay, thank you @GaurangTandon and @catarak!!! 👏👏👏👏

**Comment by catarak** [comment]
@GaurangTandon yeah! So I noticed that your fix partially fixed the issue, when saving a sketch manually, but when you edited a sketch, and then waited for the autosave to automatically save, it would still be marked with unsaved changes.

**Comment by GaurangTandon** [comment]
@catarak Oh, alright, thanks for the info!

**Pull request merged**
