### PR TITLE
Fixes "Cannot exit log in and sign up pages" #985

### PR DESCRIPTION
**Pull request by Marton6**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by catarak** [comment]
this fixes the bug of not being able to exit out of sign up or login; however, i don't like what this does to the browser history! ideally, the last page that was open before the user opened login or signup would be pushed onto the browser history.

**Comment by Marton6** [comment]
Okay. I will look into this.

**Comment by siddhant1** [comment]
In my opinion when the user clicks on the cross (x) button , he/she should land at the home page

**Comment by siddhant1** [comment]
I was looking at how jsfiddle handles it , and it looks like they do not even provide a (x) button , they provide a logo which routes to home page.

**Comment by siddhant1** [comment]
Also looking at trello.com , they also handle similar to jsfiddle (no cross button , just a logo to go back at the home page)

**Pull request closed without merging**
