### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by MathuraMG**
This PR has the following changes -

* textOutput is now accessibleOutput
* Preferences have textOutput, gridOutput and soundOutput which can be set separately

Once this PR is approved, I will merge the submodule changes as well.
[Submodule PR](https://github.com/MathuraMG/p5-interceptor/pull/5)

@catarak - We tested these changes in the [development env ](http://34.209.21.24/) which was merged with this [PR](https://github.com/processing/p5.js-web-editor/pull/328)

cc @CleezyITP @lm-n

### CODE REVIEW

**Comment by catarak** [comment]
this looks good to me, let me know when the submodule is also merged and I'll deploy this.

**Comment by MathuraMG** [comment]
thanks @catarak !
I have merged the submodule [PR](https://github.com/MathuraMG/p5-interceptor/pull/5) as well

**Comment by MathuraMG** [comment]
hi @catarak  - I just wanted to check when these changes would be deployed to the editor.
Thanks!

**Comment by CleezyITP** [comment]
just coming to this, apologies. have the changes been deployed @catarak @MathuraMG ?

**Comment by catarak** [comment]
not deployed yet but i'll do it today!

**Pull request merged**
