### PR TITLE
Feature generic table

### LINKED ISSUE #1442: Add sorting columns to Asset List
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

As reported in #1424.

The Sketch List and Collection List components have the ability to sort their columns (name, date created, etc.). The Asset List should have the ability to sort by name-, size- and sketch-. 

This also brings up a bigger issue... which is should these three components be integrated into a `Table` component? With a search bar and sortable columns? Should their state be stored in React and removed from Redux?

### PR DESCRIPTION
**Pull request by sagar-joshi**
Fixes #1442 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

SketchList, CollectionList, AssetList, AddToCollectionList, AddToCollectionSketchList and Collection use the Table component. The Table component has the sorting state, sorting function, searching function. Search state is in redux.

Also I was not able to test the AssetList due to some error (Error: getaddrinfo ENOTFOUND s3) ( at line .get(s3/objects) inside getAssets() ). After this error app used to crash.

hi @catarak  please review the changes.

### CODE REVIEW

**Comment by sagar-joshi** [comment]
Hi, @catarak I think I have made mistakes in committing the changes (like committing intermediate changes, not deleting a file when it is no longer used, and deleting it in a later commit). I am really sorry for making it difficult to review the changes.
I think I should have squashed the changes from the first four commits into a single commit. Please check the changes from the first four commits together rather than checking the changes in 1st then 2nd then 3rd then 4th commit because some code in the first and second commits is removed in the third and fourth commits. Also please ignore the file TableRow.jsx I forgot to delete that file and deleted it in a later commit. SearchBar.jsx can also be ignored because later it is also deleted and the existing Searchbar.jsx is used.

Please let me know if it does not make sense to review this PR due to improper commit history or any other reason or if there are any other problems with these changes. In such case I would like to work on this again.

**Comment by catarak** [comment]
Thanks for your patience in my getting back to you on this! I've been on a GitHub hiatus and am now reviewing PRs again. I have some suggestions for changes—are you able to work more on this or should I make them?

**Comment by sagar-joshi** [comment]
I will not be able to manage time for this due to other works. You can make the changes.

**Comment by sagar-joshi** [comment]
I will not be able to manage time for this due to other works these days. You can make the changes.

**Comment by raclim** [comment]
Thank you so much for taking the time to contribute to this issue—I'm sorry we couldn't get to your work in time! Since some time has passed I'm going to close this for now, but please feel free to reopen this or work on this again, thanks!

**Pull request closed without merging**
