### PR TITLE
Turkish Translations

### PR DESCRIPTION
**Pull request by cemergin**
Adds Turkish translations to the editor client. 

Process Details:
- Rough translations were first done by `Chat GPT3.5`
- Personally (a Native Turkish speaker, living in the US) went over each line to see if anything sounds unnatural or silly. 
- Did some manual testing to see if it works as expected
- Ran lint & tests
- Voila!

[Issue Here](https://github.com/processing/p5.js-web-editor/issues/2183)

Changes:

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptive name

Screen Shot 2023-03-23 at 9 45 52 PM
Screen Shot 2023-03-23 at 9 45 48 PM
Screen Shot 2023-03-23 at 9 45 31 PM
Screen Shot 2023-03-23 at 9 44 09 PM
d and links to an issue number, i.e.

### CODE REVIEW

**Comment by lindapaiste** [comment]
PR-wise this looks great, thank you!

I cannot vouch for the validity of the translations as I don't know Turkish, but I doubt we can find a reviewer who does 🤷  @raclim what's the process for approving new translations?

**Comment by omertarikkoc** [comment]
I am also a native Turkish speaker and I can vouch for the translations.

**Comment by raclim** [comment]
@lindapaiste There probably could be a more organized way to facilitate this, but I believe that our process so far has been to validate any incoming translations from another native speaker (thanks @omertarikkoc 🙂)! 

Thank you so much @cemergin for providing your translation process, I also think it looks great so far! One last change I would suggest adding is to also [include Turkish into the Navigation dropdown](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/translations.md#navjs) when you have the chance.

**Comment by cemergin** [comment]
Hey @raclim! Great callout, forgot to add that. My last commit should handle it. 

You can reach out to me for the maintenance or updates to the Turkish translations.

**Review by raclim — APPROVED** [review]
Looks great, thanks so much! :)

**Pull request merged**
