### PR TITLE
Added eye icon

### LINKED ISSUE #2466: Eye Icon for Revealing and Hiding Passwords
### Increasing Access

The proposed feature entails the addition of a small eye icon next to password input fields within the application's user interface. Users would have the option to click on this icon, toggling between two states:
1. Password hidden
2. Password revealed

### Feature enhancement details

1.Improved User Experience: This feature would enhance the overall user experience by providing an option to easily view the entered password, reducing frustration associated with mistyped or forgotten passwords during the login or registration process.

2.Enhanced Security: Despite the password being temporarily visible, this feature does not compromise security since it is under the user's control. Passwords would still be securely stored and transmitted as usual.

3.Accessibility: The eye icon would be particularly helpful for users with visual impairments who rely on screen readers. They can easily verify their entered password before submission.
image

### PR DESCRIPTION
**Pull request by perminder-17**
Fixes #2466 

Changes: I have made the eye icon which is very helpful. here's how it works

https://github.com/processing/p5.js-web-editor/assets/127239756/9e3126e3-eb5b-474b-8025-36c07afcb0bb

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by perminder-17** [comment]
Hi @lindapaiste  can u please review the pull request.

**Comment by perminder-17** [comment]
My apologies for any inconvenience, @lindapaiste. I accidentally deleted the pull request along with my repository. Should I resubmit the pull request, or do I need to recreate the code (the one you mentioned regarding {copyableInput} after your cleanup pull request) and then submit a new pull request? Please let me know.

**Comment by perminder-17** [comment]
@raclim @lindapaiste  can this be merged or should I change something

**Comment by perminder-17** [comment]
I have tested the changes for microsoft edge too. @lindapaiste @raclim

**Review by PiyushChandra17 — APPROVED** [review]
Looks good to me, also working demo seems pretty fine!

**Comment by perminder-17** [comment]
> Looks good to me, also working demo seems pretty fine!

Thankyou so much.

**Comment by perminder-17** [comment]
@lindapaiste Can we merge this PR? Or shall work on it's design? if Yes, can you please tell me what kind of design should i go with?

**Comment by katiejliu** [comment]
I think this eye icon looks bette than the other "hide" "show" pull request @raclim

**Comment by raclim** [comment]
I think one issue I'm finding here is that the eye icon shifts when the error message for the form appears! 

Screenshot 2024-04-12 at 11 33 07 AM

I haven't thought this through yet, but I'm wondering if it'd be better to either move the styles within the `LoginForm.jsx` and `SignupForm.jsx` file into a separate one, or to convert it into a styled-component?

**Comment by perminder-17** [comment]
Sorry for the delay, I'll git it done very soon @raclim

**Comment by perminder-17** [comment]
I will  be making a commit by june 6th. And will update what's required here.

**Comment by perminder-17** [comment]
https://github.com/processing/p5.js-web-editor/assets/127239756/b7f5d518-af60-4412-9086-26286a1efda0


so sorry for being too late @raclim . I was busy with my university exams and GSOC work, happily I got some time to shift styles to seperate one. also fixed the issue which was arising.

**Review by raclim — APPROVED** [review]
No worries, thanks so much for getting back to this, I really appreciate it! 

I made a minor adjustment to the styling of the eye icon (changed the `top` property from `5px to 7px`), but overall I think this looks great so far! Thanks so much again for your work on this! :)

**Comment by perminder-17** [comment]
Hahahhaa no worries @raclim . I love to contribute and will surely contribute in this awesome organization with these awesome Mentainers like you❤

**Pull request merged**
