### PR TITLE
Fix: Restrict sketch name length in backend

### PR DESCRIPTION
**Pull request by shakeabi**
- Add sketch name validation in backend
- Add respective error toasts in the frontend
- Do lint-fix

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

Fixes Issue #568 
@catarak What do you think?

### CODE REVIEW

**Comment by siddhant1** [comment]
Hey , @catarak I don't think we have any validation at the backend , I think we need a complete validation at the backend , should I open a separate issue for this?

**Comment by meiamsome** [comment]
I think I would suggest we should prefer to [validate at the model level](https://mongoosejs.com/docs/validation.html) instead of ad-hoc, so as to enforce it across all current and new routes, but am open to other opinions

**Comment by siddhant1** [comment]
Validating at the model level should be done but for example I send in wrong info or wrong type the server will throw an error when trying to insert in mongodb but the frontend won't get any 400 status , so I feel there should be 3 level validations , one at front end (can be disabled by changing html) , one at server level and one at db level .

**Comment by meiamsome** [comment]
@siddhant1 Generally I've seen it done where you catch the save errors and forward it to the client if it is an instance of `mongoose.Error.ValidationError` as a 400 error, which also keeps the format for validation errors consistent as well as meaning you only have to implement the validation twice (Once for the model, once for the form), though I guess you can argue that you end up implementing the error flow in multiple places

**Comment by siddhant1** [comment]
I agree , I think we can send mongoose error to the client , I have personally used Hapi.js Joi to validate my queries mostly but this makes sense too.

**Comment by shakeabi** [comment]
@meiamsome I agree with you. Model level validation removes redundancy of validation across various routes. I think its the best solution. Will do it if its confirmed.... @catarak

**Comment by catarak** [comment]
i also think that the validation should be done at the model level. would it make sense for the names to just be truncated rather than a 400 error/the save failing?

**Comment by shakeabi** [comment]
@catarak Closing this as these changes are implemented in #1025

**Pull request closed without merging**
