### PR TITLE
Moved CollectionListRowBase to be a functional component

### PR DESCRIPTION
**Pull request by aviroopjana**
Fixes #issue-number 2358

Changes:
Refer #2358 
Converted the Legacy React class component to the Functional component.

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by lindapaiste** [comment]
It's very strange that every single line in the file is showing up as a "change" in git, even the lines that are the same.  I wonder if your computer uses a different line break character or something like that.

**Comment by aviroopjana** [comment]
@lindapaiste can you tell me, what should I do to make this PR mergeable because I too unable to figure out why this is showing

**Review by PiyushChandra17 — APPROVED** [review]
Nicely Done!

**Review by lindapaiste — APPROVED** [review]
Thanks for you patience on this.  I didn't review it right away because we had another PR pending which impacted this component.  That one finally got approved and it created a bunch of conflicts with your PR so I went in and merged the two branches together.  I still don't know why every line here is showing up as a change but I'm gonna merge it anyways.

**Pull request merged**
