### PR TITLE
fixing line numbers in console

### LINKED ISSUE #36: error line numbers don't match in console
This is due to how the JS code is inserted into iframe HTML file.

screen shot 2016-08-10 at 3 09 39 pm

### PR DESCRIPTION
**Pull request by lmccart**
closes #36

### CODE REVIEW

**Comment by catarak** [comment]
This works great! I'm trying to keep a consistent JavaScript style for this project, specifically using ES6, and using ESLint to check for these consistencies. These are some of the linting errors I'm seeing:
screen shot 2016-08-27 at 3 21 39 pm

This is 100% my bad because I didn't put this on the README, which I will definitely update now, and link to ES6 reference/a JS style guide. 

Also, let me know if you're not seeing the linting errors, it is entirely possible that I haven't configured webpack correctly.

**Comment by lmccart** [comment]
Oh sorry about that. I'm not seeing linting errors... I'm following the instructions under "production installation". I do see these warnings:
```
WARNING in ./~/htmlhint/lib/htmlhint.js
Critical dependencies:
8:7694-7701 require function is used in a way in which dependencies cannot be statically extracted
8:13011-13018 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/htmlhint/lib/htmlhint.js 8:7694-7701 8:13011-13018
```

Do I need to be running some other command to see the linting errors?

**Comment by catarak** [comment]
What I intended is that "Development Installation" is for setting up the editor on your local computer, and "Production Installation" is for setting up the editor on a server (i.e. the AWS server [alpha.editor.p5js.org](http://alpha.editor.p5js.org) is running on now). I can edit the README and add a description to each of these sections, but do you have a suggestion for words that make this more clear rather than "development" and "production"?

**Comment by lmccart** [comment]
agh of course. no need to change anything, I just completely spaced, haha sorry!

**Comment by lmccart** [comment]
ok, should be good now with the linting, sorry about that!

**Pull request merged**
