### PR TITLE
"Transformed the search bar into a functional component with slight modifications.

### PR DESCRIPTION
**Pull request by Mithun1508**
Fixes #issue-number

Changes:
Fixes #2358

I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] has no test errors (`npm run test`)
* [ ] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Review by Mithun1508 — COMMENTED** [review]
Overview : Refactor Searchbar component from class to functional component
Details:

1 Converted the Searchbar component from a class component to a functional component.

2 Replaced state and lifecycle methods with useState and useEffect hooks.

3 Updated event handling functions to use the useState and useEffect hooks.

**Comment by Mithun1508** [comment]
@lindapaiste please look into it..!!

**Review by Mithun1508 — COMMENTED** [review]
Overview : Refactor Searchbar component from class to functional component
Details:

1 Converted the Searchbar component from a class component to a functional component.

2 Replaced state and lifecycle methods with useState and useEffect hooks.

3 Updated event handling functions to use the useState and useEffect hooks.

**Comment by raclim** [comment]
Thanks for your work on this! Since we have a few PRs for this issue already, we'll probably be going with those since they were submitted earlier. I'm sorry that we couldn't get this in, but please feel free to check out our other issues!

**Pull request closed without merging**
