### PR TITLE
Trigger Immediate Refresh when ticking the Auto-Refresh checkbox

### LINKED ISSUE #2511: Auto-Refresh Button Doesn't Trigger Immediate Refresh
### p5.js version

_No response_

### What is your operating system?

None

### Web browser and version

_No response_

### Actual Behavior

Our current auto-refresh feature doesn't immediately refresh code output when the "auto-refresh" button is clicked. Auto-refresh, which should provide a means for developers to see the output corresponding to the code they've written, currently falls short, potentially leading to inconsistencies between the code and its output.

[issuep5.webm](https://github.com/processing/p5.js-web-editor/assets/127239756/a9fed1e9-c9bf-4e14-a657-6fefd8d08122)

### Expected Behavior

Upon clicking the "auto-refresh" button, the code output should refresh immediately, allowing users to see the impact of their code changes without requiring additional edits.

### Steps:
1. Go to home page
2.Click on auto-refresh.

### PR DESCRIPTION
**Pull request by perminder-17**
Fixes #2511 

Changes: 

[issuelast.webm](https://github.com/processing/p5.js-web-editor/assets/127239756/aa5dfc6d-48fc-4933-aefc-ab86b794f389)

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by perminder-17** [comment]
is anything else we want @raclim . Please review the PR whenever you are free @raclim @lindapaiste

**Review by PiyushChandra17 — APPROVED** [review]
Looks good to me

**Comment by perminder-17** [comment]
> Looks good to me

Thankyou

**Comment by SableRaf** [comment]
Hey @perminder-17 thanks for your contributions! 

Just a friendly note: Could you please use more descriptive names for your Pull Requests? It helps maintainers review your work more efficiently.

For instance, I've renamed your PR from `solved for issue #2511` to `Trigger Immediate Refresh when ticking the Auto-Refresh checkbox`.

Keep up the great work!

**Comment by perminder-17** [comment]
Thankyou so much @SableRaf . I am going to change the names of other Pull Requests name ASAP. Thanks for your suggestion.

**Review by lindapaiste — APPROVED** [review]
Looks good!

Just a note that there are other possible places in the code where this could be addressed, such as handling it inside the `setAutoRefresh` action.

**Comment by perminder-17** [comment]
> Looks good!
> 
> Just a note that there are other possible places in the code where this could be addressed, such as handling it inside the `setAutoRefresh` action.

Ok @lindapaiste I will take care of it next time.

**Pull request merged**
