### PR TITLE
font size fix

### PR DESCRIPTION
**Pull request by parteekcoder**
issue #2053 

@raclim this issue is solved you can check my PR

Thanks , any suggestion from you will be admired

### CODE REVIEW

**Comment by parteekcoder** [comment]
@raclim @catarak plz review this PR , your suggestions are admired by me

**Comment by parteekcoder** [comment]
@raclim @davepagurek I tested this it runs fine , i think it can be merged

If you have any suggestions I will appreciate that

**Comment by davepagurek** [comment]
Thanks @parteekcoder, this fix does look like it will effectively convert the input value to a number before incrementing! I'm not super familiar with the p5 editor source, so I'll still defer to @raclim for a final say here, in case e.g. there's a better place for this conversion.

**Comment by parteekcoder** [comment]
> Thanks @parteekcoder, this fix does look like it will effectively convert the input value to a number before incrementing! 

Yes you are right , as before it is doing string concatenation that's why the issue occurred but now I improved to first convert input to number

**Review by raclim — APPROVED** [review]

**Comment by raclim** [comment]
Looks good to me, thanks @parteekcoder and @davepagurek!

**Pull request merged**
