### PR TITLE
Fix/cant see shaders code

### LINKED ISSUE #1595: Can't see shaders code
#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: all Chromium, FireFox, Opera  tested
- Operating System:  Windows 10
- Steps to reproduce this bug:

open any example with shaders e.g. https://editor.p5js.org/p5/sketches/3D:_shader_as_a_texture
navigate to shader file. Nothing appears.

### PR DESCRIPTION
**Pull request by vulongphan**
Fixes #1595 

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by catarak** [comment]
Thank you for working on this! It's working for me. I know that the code in this script is a little messy, but would it be possible for you to put the new code you added into a separate function? I think eventually it would make sense to clean up this file, but for now, when adding new code, I think it makes sense to add it in as cleanly as possible.

**Comment by vulongphan** [comment]
Yes, it makes sense to me too. I have moved all my added code to `addAssetsToProject()`. Could you please have a look?

**Review by catarak — APPROVED** [review]
Thanks for making that change! Looks good to me.

**Comment by catarak** [comment]
This is working great for me. I think the next important step here is refactoring this file so that it just uses async/await—there are callbacks, promises, and async/await here and it's kind of a mess :) I'll open a new issue!

**Pull request merged**
