### PR TITLE
Fix: Logout Glitch

### LINKED ISSUE #2449: Login Session Still Persists Despite Logout
### p5.js version

1.7.0

### What is your operating system?

Windows

### Web browser and version

chrome, edge, Brave

### Actual Behavior

When we try to log out, the session Id is not deleted

Screenshot (92)
Screenshot (95)
Screenshot (93)
Screenshot (94)

As a result, after clicking logout, when I refresh the page, I again enter the login state on the website.

### Expected Behavior

The sessionId got deleted and after refresh, the user can not go back to the login state.

### Steps:
1. click logout.
2. hit refresh
3. you get back to login state

### PR DESCRIPTION
**Pull request by rajatmohan22**
Fixes: #2449

@lindapaiste I noticed your comments on the issue. You mentioned that you're not an expert on cookies, and I'm in the same boat 😄. However, after some investigation, here's what I've discovered:

**1. Why doesn't the error occur on localhost?**
Ans: Seemingly, browsers have different policies regarding cookies for different domains. Therefore, cookies and session management may behave differently compared to an external server ( This is actually evident if you open the networks tab on both localhost and the prod site and check the `status code` of the session.) This could lead to differences in how sessions are managed and why the issue doesn't occur locally.

**2. How do we fix it?**
Ans: Deleting the session. What's happening now is that, on logout, the session Id is changing. However, we want it gone!
Apparently Passport provides another function for this. It is called: `session.destroy`.

Please check it out, and let me know if any changes is required.

Here is a brief video/gif:

with `req.session.destroy`
[screen-capture (1).webm](https://github.com/processing/p5.js-web-editor/assets/77490034/65425538-cf13-4639-a76f-4b52aa060aae)

with `req.logout`:
[screen-capture (3).webm](https://github.com/processing/p5.js-web-editor/assets/77490034/9e0df71f-54a5-4d5e-892c-760f5368e046)

Changes:

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by rajatmohan22** [comment]
@lindapaiste If the uploaded video isn't clear, I can create a brief YouTube video explanation and share the link here

**Comment by rajatmohan22** [comment]
@lindapaiste Have a look at both the videos:

- Using `req.logout` alone creates a new session.

- Using `req.session.destroy` deletes the session permanently.

**Comment by lindapaiste** [comment]
Thanks for researching this! At first glance it looks good.

**Comment by rajatmohan22** [comment]
@lindapaiste,Is there a way to verify this? because it still runs on localhost even in production mode. So I can't reproduce the issue.

**Comment by rajatmohan22** [comment]
Maybe I must deploy on Heroku to verify ?

**Comment by rajatmohan22** [comment]
@lindapaiste 
I found this link online: https://copyprogramming.com/howto/either-req-logout-or-req-session-destroy-does-not-work
It discusses the distinctions between using `req.logout` and `req.session.destroy`. (Please note, I made a minor mistake earlier – `req.session.destroy` is actually an Express function, not a Passport one.)

I want to highlight a small paragraph from the website. Which says:  It is not recommended to implement logout from the server side, as the token is not stored on the server. Therefore, it's best to let clients handle the logout by deleting the token. Additionally, it's important to avoid storing tokens in the database unless necessary, and if they must be stored, they should be hashed like passwords. Storing tokens in a database can be risky if there is a security vulnerability, as it could give intruders too much power.

Currently, we're handling the hashing part, but we're not deleting the token on the server upon logout. As I mentioned earlier, we're modifying it instead. Don't think it would be a good modification to implement in the codebase?

**Comment by rajatmohan22** [comment]
@lindapaiste, this works. I deployed a test app. Repo link: https://github.com/rajatmohan22/AuthTest1.

Additionally, we can include HTML tags to clear the browser cache. Do you want me to do anything else to test it out particularly?

**Comment by rajatmohan22** [comment]
@raclim could you verify this?

**Review by raclim — APPROVED** [review]
Thanks for working on this! I also think this looks good to me for now.

**Comment by rajatmohan22** [comment]
@raclim Thank you! appreciate it.

**Comment by lindapaiste** [comment]
@raclim We need to roll this back.

I had not run it before (FYI, if I say something like "At first glance it looks good." that usually means I looked at the code but didn't run it).  Now that I am running it I am getting a 500 error from the API when logging out, [detailed here](https://github.com/processing/p5.js-web-editor/issues/2292#issuecomment-1791419467). 

The passport logout function throws an error if there is no `req.session`.  This PR is calling `req.session.destroy` first and `req.logout` second.  Therefore the logout fails because the session is gone.

**Comment by rajatmohan22** [comment]
Refer to #2473 for detailed error explanations. I'm also super open to providing a line-by-line breakdown. I believe the code is error-free. However, we can also consider using the 'destroy' method **without** Passport's 'logout' if desired.

**Comment by raclim** [comment]
After giving another look at it I'm also getting the same 500 error here. Sorry I think I didn't give it as thorough of a glance as I should've at the time!

I'm going to revert this PR for now, and we can take a look at the new one submitted for this.

**Pull request merged**
