### PR TITLE
Fixed Issue #896

### LINKED ISSUE #896: Repetition in Console after changing "Accessible text-based canvas" options.
#### Nature of issue?
Repetition in Console after changing "Accessible text-based canvas" options.

Screenshot 2019-03-15 at 8 29 08 PM

- Found a bug

#### Details about the bug: 

- Web browser and version: On Chrome
- Operating System: MacOSX
- Steps to reproduce this bug:

Clear the console after every change.

@catarak please express your views on it.

### PR DESCRIPTION
**Pull request by AnkurIngale**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] Fixes #896 

@catarak Please review.

### CODE REVIEW

**Comment by catarak** [comment]
i don't think this is the right approach. the sketch is re-rendering because the preference is changing, so i think the re-rendering should handle clearing the console.

**Comment by AnkurIngale** [comment]
So you mean to say, it should fix the next time the user runs the sketch?

**Comment by AnkurIngale** [comment]
@catarak  I got your point and made the necessary changes. I have a PR pending, so can you please review that so that I can make a PR on this as well?

**Comment by AnkurIngale** [comment]
@catarak Will returning dispatch(Actiontype.clearconsole) in setTextOutput work?

**Comment by catarak** [comment]
no, the function `renderSketch` should dispatch a `clearConsole` action.

**Comment by AnkurIngale** [comment]
Where is this `renderSketch`? Couldn't find it.

**Comment by AnkurIngale** [comment]
On further research, I believe the console is cleared on rendering. 
The problem is, when we change the setTextOutput, the sketch is not rendered again. 
To see this, make an error and run once. You will see red highlight. Now run again. The highlight disappears and comes back showing that it rendered again. But when we change the setTextOutput, it is not rendered.
Therefore, we need to find where the next line in console is given and clear the console before it. @catarak

**Comment by AnkurIngale** [comment]
Where is this `renderSketch`? I tried finding it but couldn't get it.

**Comment by catarak** [comment]
it's in PreviewFrame.jsx.

**Comment by AnkurIngale** [comment]
Resolved this issue.

**Pull request closed without merging**
