### PR TITLE
update non-breaking dependencies (#785)

### PR DESCRIPTION
**Pull request by GaurangTandon**
Before your pull request is reviewed and merged, please ensure that:

* [x] there are no linting errors -- `npm run lint`
* [x] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [x] your pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

Thank you!

I have verified each version number manually from `npm audit's` output, and I have also verified the editor to be functional (`npm start`) works, and also basic functionality works (logging in/saving/etc.).

### CODE REVIEW

**Comment by catarak** [comment]
did you also update `package-lock.json`? shouldn't that also be added to this PR? when i ran `npm install`, my package-lock.json got updated to reflect the changes to `package.json`.

**Comment by GaurangTandon** [comment]
Yeah, sorry, it did get updated. I should have committed it too. Have added it now.

**Comment by catarak** [comment]
great! i'll do another sanity check and then merge this.

**Comment by catarak** [comment]
what version of npm are you running? i noticed that your `package-lock.json` has a bunch of carets with the versions. i'm running npm 5.6.0, and when i run `npm install`, it removes the carets, e.g. changes a version from "^2.0.2" to "2.0.2"

**Comment by GaurangTandon** [comment]
Hmm, I do remember having to switch to Node v8.14.0 LTS for this project. That switch automatically switched me to npm 6.4.1 (on v10.14.2 LTS I get npm v6.5.0). I did the switch to v8 LTS because the project would give several errors and refuse to run on `npm start` otherwise. But it did not complain about npm being v6.4.1. So, I never thought of changing it.

I suppose that now we are in the process of updating the dependencies, it might also be a very good time to upgrade both Node and npm versions to the latest stable releases :)

(As for the specific issue of caret insertion, it seems to have been discussed [here](https://github.com/npm/npm/issues/20891))

**Pull request merged**
