### PR TITLE
Issue #1211 fixed - End of empty element is broken

### LINKED ISSUE #1211: The end of empty element is broken
#### Nature of issue?

- Found a bug

#### Details about the bug: 

At server/views/index.js line 15, the end of empty element is broken.

```html
  <link rel='shortcut icon' ... type='image/x-icon'/ >
```
should be
```html
  <link rel='shortcut icon' ... type='image/x-icon' />
```

- Web browser and version: Microsoft Edge (I see the error message at the developer console.)
- Operating System: Windows
- Steps to reproduce this bug: run the editor

### PR DESCRIPTION
**Pull request by ani4aniket**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [ ] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

Fixes #1211
The end of empty element is broken.

### CODE REVIEW

**Comment by catarak** [comment]
thanks for creating this PR! it seems like this fixes multiple issues? in the future, it's easier to review PRs when they fix only one issue, because one fix might be perfect and one might need some adjustment.

**Comment by catarak** [comment]
your changes for #1211 and #1192 are okay, but I don't agree with the way that you fixed #1199! why add a whole javascript library for something that should be a design change?

**Comment by ani4aniket** [comment]
@catarak okay will create another PR without any library using only CSS.

**Comment by catarak** [comment]
great, thank you!!

**Comment by ani4aniket** [comment]
@catarak I have created this new PR to fix #1199 without the use of any JS library. Please review it.
Thank you.

**Pull request closed without merging**
