### PR TITLE
fixes #568

### LINKED ISSUE #568: Add character limit to sketch name - Back end validation
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

name a project with special characters and try to donwload.
some of them will cause problem, e.g. &,|...

### PR DESCRIPTION
**Pull request by GaurangTandon**
Before your pull request is reviewed and merged, please ensure that:

* [x] there are no linting errors -- `npm run lint`
* [x] your code is in a uniquely-named feature branch and has been rebased on top of the latest master. If you're asked to make more changes, make sure you rebase onto master then too!
* [x] your pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

Thank you!

I have tested it locally and it works correctly. I have removed `slugify` as a dependency and setup `generateSlug` as the new function that generates the slugs. Also, I have retained the replacer for invalid characters as an underscore as it was before. Please suggest any additional changes. Thanks!

### CODE REVIEW

**Comment by GaurangTandon** [comment]
I didn't notice that because in my case I always got URLs like these `https://editor.p5js.org/znryfyjssharklasers/sketches/{random 9 letter alphanumeric mixed case string}`, like `TJHua0ShP. Are only some specific user accounts allowed to generate those URLs?

**Comment by catarak** [comment]
no, it's just a secret feature that's not fully implemented yet. it was necessary to support web editor integration with the [generative design](http://www.generative-gestaltung.de/2/) release.

**Comment by GaurangTandon** [comment]
Oh nice, but now I don't know what more to do to restore support for that feature other than add slugify back to the dependency list?

**Comment by GaurangTandon** [comment]
Hi, I made the necessary changes. Please review!

**Comment by GaurangTandon** [comment]
The build seems to fail because it is unable to execute test script. How can I help in resolving this?

**Comment by catarak** [comment]
this is working great for me! i'll commit a change that fixes the test error.

**Pull request merged**
