### PR TITLE
Add matches search into code mirror fixes #936

### LINKED ISSUE #936: Show the count of search elements found
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:

 When seacrhed for some word, count of the results found should be displayed like most of the applications.

#### New feature details:

### PR DESCRIPTION
**Pull request by davidbmx**
I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Show the count of search elements found #936`

### CODE REVIEW

**Comment by catarak** [comment]
thanks for working on this! this is super cool. is there a way to make this function more like how find works in other applications? usually it will jump to the first result and say "1/4" if there are 4 results. i don't think adding the word "result" is necessary either!

**Comment by davidbmx** [comment]
Hi,
if possible I will make the changes

**Comment by davidbmx** [comment]
Ready, make the changes to look like other applications find

**Comment by catarak** [comment]
cool, this is working great for me. i'm noticing some funkiness with search in general but i think that's a separate issue. thanks for working on this!

**Pull request merged**
