### PR TITLE
Translations for Dates (fixes #1584)

### LINKED ISSUE #1584: Translations for Dates
- Existing feature enhancement

At this moment translations in the Client-Side for dates are not provided
The dates functionality is provided by 

``` 
import differenceInMilliseconds from 'date-fns/difference_in_millisecond';
import distanceInWordsToNow from 'date-fns/distance_in_words_to_now';
```
date-fns has an own way to use locales, but they need to be declared (and present) before use (no fetching based on current language)

#### Feature enhancement details:
* Create a custom wordstonow function to extend current functionality for the case where the saved date is bigger than 35 seconds
* Analyze the tradeoff of importing all the date-fns in advance for use dates in the different languages vs custom solution vs different library.

### PR DESCRIPTION
**Pull request by andrewn**
- centralise all date formatting into two utility functions (`dates.format()`, `dates.distanceInWordsToNow()`)
- upgrade app to use date-fns v2 which supports localisation
- use date-fns' locales to translate into English/Spanish

Both locales are imported into the bundle at the moment. They're only 1.5k each so not a huge issue but as we add more languages we might want to dynamically import each locale as needed. This will take more work as the components expect the formatting to be synchronous at the moment.

Fixes #1584

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #1584`

### CODE REVIEW

**Comment by oruburos** [comment]
Hi @andrewn 
I checked the code locally.

Trying to test the `saved ago`  functionality I found the following messages displayed in console:

```
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use parseISO to parse strings. See: https://git.io/fjule
Error:
    at toDate (D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\date-fns\toDate\index.js:56:20)
    at isAfter (D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\date-fns\isAfter\index.js:39:42)
    at D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\server\controllers/project.controller.js:23:31
    at D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\mongoose\lib\model.js:4828:16
    at D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\mongoose\lib\query.js:4390:12
    at D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\mongoose\lib\query.js:2869:28
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:5216) DeprecationWarning: Mongoose: findOneAndUpdate() and findOneAndDelete() without the useFindAndModify option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#-findandmodify-
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use parseISO to parse strings. See: https://git.io/fjule
Error:
    at toDate (D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\date-fns\toDate\index.js:56:20)
    at isAfter (D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\date-fns\isAfter\index.js:39:42)
    at D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\server\controllers/project.controller.js:23:31
    at D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\mongoose\lib\model.js:4828:16
    at D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\mongoose\lib\query.js:4390:12
    at D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\mongoose\lib\query.js:2869:28
    at processTicksAndRejections (internal/process/task_queues.js:79:11) 
```

**Comment by andrewn** [comment]
> ```
> Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use parseISO to parse strings. See: https://git.io/fjule
> Error:
>     at toDate (D:\gsocP5\p5.js-web-editor-master\src\p5.js-web-editor\node_modules\date-fns\toDate\index.js:56:20)
> ...
> ```

Good spot! I've pushed a new commit that removes this warning.

**Comment by oruburos** [comment]
Great, indeed, the translations for dates work.

**Review by oruburos — APPROVED** [review]
Great, indeed, the translations for dates work. Timer messages in the bar are not displayed but I checked against messages in console and they were correct. So functionality for this PR is there.

**Comment by catarak** [comment]
> Great, indeed, the translations for dates work. Timer messages in the bar are not displayed but I checked against messages in console and they were correct. So functionality for this PR is there.

I tested this and I'm also not seeing the timer messages!

**Comment by andrewn** [comment]
> > Great, indeed, the translations for dates work. Timer messages in the bar are not displayed but I checked against messages in console and they were correct. So functionality for this PR is there.
> 
> I tested this and I'm also not seeing the timer messages!

I couldn't see the Timer, but I think that's unrelated to this PR as I don't see it in the develop branch either. Or on [the deployed editor](https://editor.p5js.org/).

Do you know what the behaviour of the Timer is and I'll try and fix it....!

**Comment by catarak** [comment]
> I couldn't see the Timer, but I think that's unrelated to this PR as I don't see it in the develop branch either. Or on [the deployed editor](https://editor.p5js.org/).
> 
> Do you know what the behaviour of the Timer is and I'll try and fix it....!

Oh thanks for pointing that out! It's the [Timer.jsx](https://github.com/processing/p5.js-web-editor/blob/develop/client/modules/IDE/components/Timer.jsx) component that renders in the Editor.jsx component. Since this is unrelated to this PR, I'll open a new issue so it can be merged in a separate PR :)

**Comment by catarak** [comment]
Just fixed the Timer issue with #1617 :)

**Review by catarak — APPROVED** [review]
okay this is now working as expected for me 😄 so rad!

**Pull request merged**
