### PR TITLE
Fix typos in translation

### LINKED ISSUE #1948: Typo in translation
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

In translations.json for pt-BR there's a typo in [line 86](https://github.com/processing/p5.js-web-editor/blob/develop/translations/locales/pt-BR/translations.json#L86) where is written Enrar instead of Entrar

### PR DESCRIPTION
**Pull request by code4humanity**
Fixes [#1948](https://github.com/processing/p5.js-web-editor/issues/1948)

I have verified that this pull request:

* [X] is from a uniquely-named feature branch and has been rebased on top of the latest `develop` branch. (If I was asked to make more changes, I have made sure to rebase onto `develop` then too)
* [X] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by catarak** [comment]
@code4humanity it seems like some of the changes you made are fixing typos, and others are a little more major. Would it be possible to have another person who speaks Brazilian Portuguese to review these changes? 

tagging @byfelipesanchez, who did the original translation, to weigh in.

**Comment by code4humanity** [comment]
@catarak, I agree. Most of them were fixing typos, I think the ones in line 60 and 297 were the major ones. Do you want me to remove them while we discuss the issue [#1951](https://github.com/processing/p5.js-web-editor/issues/1951)?

**Comment by catarak** [comment]
I think because the changes suggested in #1951 are relatively small, we can leave this as it is.

Do you need help soliciting feedback from others?

**Comment by code4humanity** [comment]
@catarak, I'm sorry for the delay in my response.

I was thinking I could revert the changes that worries you and in [#1951](https://github.com/processing/p5.js-web-editor/issues/1951) I could finish reviewing the whole file and create a draft PR so we can discuss it as I believe there are more modifications than the ones I wrote. What do you think?

**Comment by catarak** [comment]
> I was thinking I could revert the changes that worries you and in [#1951](https://github.com/processing/p5.js-web-editor/issues/1951) I could finish reviewing the whole file and create a draft PR so we can discuss it as I believe there are more modifications than the ones I wrote. What do you think?

Fine by me!

**Review by cesardeazevedo — APPROVED** [review]
Looking good

**Review by raclim — APPROVED** [review]
Merging this in now, these changes will be out after the next version update :)

**Pull request merged**
