### PR TITLE
Translate 'Autocomplete Hinter' into All Available Language

### LINKED ISSUE #2601: Translate 'Autocomplete Hinter' into Hindi
### Increasing Access

in this, all the headings and buttons are in Hindi except 'Autocomplete Hinter'

p5-issue2

### Feature enhancement details

it would be better if we convert this in Hindi as well so that it matches the language of whole page.

**In order to reproduce it**

- got to https://editor.p5js.org/
- on Top-right corner, click on 'English' button
- then select Hindi as Language
- then click on settings wheel
- and notice 'Autocomplete Hinter' in सामान्य सेटिंग्स tab

### PR DESCRIPTION
**Pull request by swrno**
Fixes #2601 

Changes:
Translated the 'Autocomplete Hinter' feature into Hindi to align with the overall language of the page.
Extended the translation fix to cover all languages, ensuring a consistent user experience across different language preferences.

English:
Screenshot (21)
Hindi:
Screenshot (19)
Français:
Screenshot (20)

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by lindapaiste** [comment]
I'm assuming that these are from Google Translate or another automated tool, yes?  This is something that @raclim and I have been discussing and I'm not sure where we stand on machine translations.  My instinct is that it's better than no translation.  We discussed how it would be nice to know which translations were written by a native speaker vs. which were automated, but that's not something that our current system supports.

**Comment by swrno** [comment]
These transactions are done by ChatGPT and I have prompted such a way that it should act like a native speaker. So, all of those are more or less like standard speaking words.



Also I am a native speaker of Hindi, so the translation ChatGPT generated for Hindi, is standard. I have already verified it.

**Comment by raclim** [comment]
> I'm assuming that these are from Google Translate or another automated tool, yes? This is something that @raclim and I have been discussing and I'm not sure where we stand on machine translations. My instinct is that it's better than no translation. We discussed how it would be nice to know which translations were written by a native speaker vs. which were automated, but that's not something that our current system supports.

I mostly feel the same here as well! Ideally the machine translations should be verified or revised by another native speaker (which it seems like it has been done in this case). Maybe a temporary solution that we could encourage for now to identify how translations were created is to have folks explain their translation process in their PRs and where they came from?

**Comment by swrno** [comment]
Thank you for the feedback! I've reviewed the code, and I believe it's ready for merging. If there are any lingering grammatical errors or improvements, I encourage contributors to make additional pull requests. Let's collaborate to enhance the code further. Appreciate everyone's hard work on this!

**Pull request merged**
