### PR TITLE
Adjust light theme colors to WCAG AA

### PR DESCRIPTION
**Pull request by meganindya**
This addresses #1263 . I've adjusted the text colors in the light theme to conform to WCAG AA standards. It includes the editor and console colors too.

### CODE REVIEW

**Comment by catarak** [comment]
Thanks for working on this. However, I'd prefer if you start from some of the adjusted colors in this [design system](https://www.figma.com/file/cyHiandYyEAPj0Kj6tJbHc/p5-design-system-2018?node-id=0%3A1). Also please include an updated design or screenshots, and the results from a WCAG AA test.

**Comment by meganindya** [comment]
Sure. Thanks for the advice.

**Comment by elit-altum** [comment]
@meganindya are you still working on this? I'd be happy to take this up if you are busy :)

**Comment by meganindya** [comment]
Yes, please go ahead.

**Pull request closed without merging**
