### PR TITLE
Feat: Give Preferred language based Credential Error from Backend

### LINKED ISSUE #2860: Issue with Language Change and Invalid Username/Password Error on p5.js Web Editor
### p5.js version

v1.9.0

### What is your operating system?

Windows

### Web browser and version

120.0.6099.199

### Actual Behavior

**When we sign in and give the wrong credentials then the error message from server is always appear in english even though we have changed the preferred language.**

Screenshot 2024-01-07 134808

### Expected Behavior

**The Error message should also be in the preferred language.**

### Steps:
1. Go to the sign in page in the p5.js web editor.
2. Try to sign in with wrong credential 
3. You will see some errors but when you change the preferred language from the top then also you will find the same error.

### PR DESCRIPTION
**Pull request by Vishal2002**
Fixes #2860

Changes:

- Added i18next in the backend to automatically determine the language and map the correct error credential message.
- In the `Nav.jsx` component, a backend request is sent to the endpoint `/getCurrentLanguage` to store the current language. The language is then changed using `i18n.changeLanguage(language);`.
- Utilized `i18nextMiddleware` to capture the language and facilitate mapping errors accordingly.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] has no test errors (`npm run test`)
* [x] is from a uniquely-named feature branch and is up to date with the  `develop` branch.
* [x] is descriptively named and links to an issue number, i.e. `Fixes #2860`

Screenshot 2024-01-14 215132
Screenshot 2024-01-14 215224

### CODE REVIEW

**Comment by lindapaiste** [comment]
This shows a lot of potential!  Translating server-side messages is something that we've been discussing for a long time.  See #1587

**Review by perminder-17 — APPROVED** [review]
Looks good!

**Comment by Vishal2002** [comment]
> This shows a lot of potential! Translating server-side messages is something that we've been discussing for a long time. See #1587

What to do next?

**Review by PiyushChandra17 — COMMENTED** [review]
Looks good 👍

**Comment by raclim** [comment]
Thanks so much for your work on this!

Due to some of the changes here falling out of date and some of the other features/fixes we'd like to prioritize over the next two months, I'm going to close this pull request for now. I'm really sorry that it took a while to get to this and that we couldn't get this in at the moment, but please feel free to update and reopen this pull request in the future!

**Pull request closed without merging**
