### PR TITLE
add readme korean translation

### PR DESCRIPTION
**Pull request by mjaything**
I have verified that this pull request:

* [X] has no linting errors (`npm run lint`)
* [X] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [X] is descriptively named and links to an issue number, i.e. `Fixes #123`

Addresses #1350

### CODE REVIEW

**Comment by catarak** [comment]
Yay this is so awesome! Looking at this again, I think that it would make sense to put this at `translations/ko/README.md`, and then link to this README in the root README.

**Comment by mjaything** [comment]
changed the file structure accordingly! :-)

**Comment by catarak** [comment]
Great! I'd also like to link to this file from the root README (like under the first header). I'd just do it myself but I don't know how to say Korean in Korean so... I'll let you do it 😄

**Comment by mjaything** [comment]
Thanks for pointing it out! I'll make a table with links just like [All Contributors Readme](https://github.com/all-contributors/all-contributors/blob/master/README.md). Just after the title [p5.js Web Editor](p5.js Web Editor) and before its first paragraph.

**Comment by mjaything** [comment]
I have made a link to the translation/ko directory, so that a user could see the all the translated documents. Please let me know if you want something to be changed! :-)

**Comment by catarak** [comment]
I was playing around with the table formatting a bit and decided to take it out. Otherwise looks good and going to merge this!

**Comment by mjaything** [comment]
Thank you for reviewing and organizing it! Yes, I agree that table didn't look great especially with just one box. A table could be useful when the number of supported languages grows to 10 or 20. Thanks for the merge!

**Pull request merged**
