### PR TITLE
Write tests for name verification logic (<ToolBar />, <FileNode />)

### PR DESCRIPTION
**Pull request by ghalestrilo**
Some additional tests for these two components, just to make sure the logic works as intended, and to prevent it from breaking in the future.

I have verified that this pull request:

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by andrewn** [comment]
This is really cool! 🎉 

Have you ever used [React Testing Library](https://testing-library.com/) to write tests instead of Enzyme? I've used it in a couple of projects now and it really helps me to write more accessible components. It moves focus into testing how the user experiences the app via labels and text, rather than testing internal details like state or props.

Was thinking it might be worth moving to this while we don't have a huge number of UI tests in the project.

@catarak?

**Comment by ghalestrilo** [comment]
That's a great idea, I'm all for it!
React Testing Library also seems a lot more future-proof

**Comment by catarak** [comment]
React Testing Library looks awesome! I think it would be worth trying it out in a separate PR and see how it looks compared to the enzyme tests.

**Comment by catarak** [comment]
these tests look good to me for right now!

**Comment by catarak** [comment]
Opened an issue about React Test Framework: #1432

**Pull request merged**
