### PR TITLE
accessibility screen in dark mode

### PR DESCRIPTION
**Pull request by parteekcoder**
issue #1852 

@raclim please review this PR

Your suggestions will be admired

### CODE REVIEW

**Comment by parteekcoder** [comment]
@raclim @catarak plz review this PR , your suggestions are admired by me

**Comment by parteekcoder** [comment]
@raclim @davepagurek I would appreciate your suggestions on this PR and work upon them if any

**Comment by raclim** [comment]
Thanks for working on this! So far it's looking good but I think in it's current state, it still holds a potential issue where the entire preview pane is white even when no sketch is running, which can result in a confusing user experience. https://github.com/processing/p5.js-web-editor/issues/1852#issuecomment-835465957 highlights an alternative solution. If what they described sounds good, you can try to give it a go!

**Comment by parteekcoder** [comment]
> Thanks for working on this! So far it's looking good but I think in it's current state, it still holds a potential issue where the entire preview pane is white even when no sketch is running, which can result in a confusing user experience. [#1852 (comment)](https://github.com/processing/p5.js-web-editor/issues/1852#issuecomment-835465957) highlights an alternative solution. If what they described sounds good, you can try to give it a go!

yeah I will look into it and propose a better solution

**Comment by raclim** [comment]
I'm going to close this PR for now, but please feel free to create a new one when you're ready, thanks! :)

**Pull request closed without merging**
