### PR TITLE
Implement Mobile version of Files tab / sidebar

### PR DESCRIPTION
**Pull request by ghalestrilo**
Requires #1528

This branch implements an `<Explorer />` mobile component, which uses a `<Sidebar />` modal component (new) as a modal. It also updates the logic of the `useAsModal` HOC to support components that require the ability to close themselves (like the sidebar).

* [x] has no linting errors (`npm run lint`)
* [x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by catarak** [comment]
This also looks so good! It's really, really exciting 😄 

The only thing I'm unsure about is the floating file button, and I'd like to try having it be one of the icons next to the console icon.

**Comment by ghalestrilo** [comment]
Nice! I moved it to the bottom bar, and improved a couple things there

**Comment by catarak** [comment]
This looks great! I'm not sure what changes i would add other than getting the dropdown button to do stuff, but that could be another PR I think.

**Comment by catarak** [comment]
I think this one is ready 😄

**Pull request merged**
