### PR TITLE
Enabled tree-shaking #976

### PR DESCRIPTION
**Pull request by siddhant1**
I have verified that this pull request:

* [ x] has no linting errors (`npm run lint`)
* [ x] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [ x] is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by meiamsome** [comment]
Does this just make it work? Do we have a way to prove tree shaking is enabled? Perhaps we can compare bundle sizes before and after as a metric to see if anything changes?

**Comment by siddhant1** [comment]
Yes , webpack by default enables tree-shaking (also we should upgrade to v4) but it only works on esm , babel transpiles down esm to cjs which are not tree-shakable , disabling modules on babelrc enables webpack to tree-shake bundle

**Comment by siddhant1** [comment]
Yes , we can compare bundle sizes , there is a webpack plugin named webpack-bundle-analyzer

**Comment by catarak** [comment]
i'm super confused—does this enable tree-shaking or is that dependent on webpack v4?

**Comment by siddhant1** [comment]
https://stackoverflow.com/questions/47663486/webpack-3-babel-and-tree-shaking-not-working

Also webpack tree-shaking guide explains this as well , and webpack 3 supports tree-shaking.

**Comment by catarak** [comment]
when running `npm start` the build fails:
```
/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/ctarakajian/Development/projects/p5.js-web-editor/server/server.js: Using removed Babel 5 option: base.modules - Use the corresponding module transform plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules
    at Logger.error (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:220:20)
    at OptionManager.init (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.transformFileSync (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-core/lib/api/node.js:152:10)
    at compile (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-register/lib/node.js:118:20)
    at loader (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ctarakajian/Development/projects/p5.js-web-editor/node_modules/babel-register/lib/node.js:154:7)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by siddhant1** [comment]
Hm, let me investigate

**Comment by siddhant1** [comment]
@dhruvdatt can you help me here !

**Pull request closed without merging**
