### PR TITLE
Added script to download and save all generative-design project examples to p5-web-editor

### PR DESCRIPTION
**Pull request by joeyklee**
The script example-gg-latest.js fetches the relevant sketches from the [generative-design p5.js-code-package](https://github.com/generative-design/Code-Package-p5.js) and stores them into the p5.js editor.

#### Note:
- you'll need a github api key & secret. the request limit is 5000 per hour with the key and secret.
- you'll also need the generative design username and password for the p5js-web-editor. 

Thanks so much! 
🌈✨🎉
***

* [X] there are no linting errors -- `npm run lint`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master. If you're asked to make more changes make sure you rebase onto master then too!
* [X] pull request is descriptively named and links to an issue number, i.e. `Fixes #123`

### CODE REVIEW

**Comment by catarak** [comment]
looks great! send me the username and password, and let me know when you want me to run the script and/or put it on a cron job.

**Comment by joeyklee** [comment]
Thanks @catarak ! I will send you the deets in the next day or so and let you know when to run the 'ol thang / cron job sounds like a pretty great solution :) Thanks again! 🌈🎉🎉🍣

**Comment by shiffman** [comment]
This is awesome! Question . . .

I've been manually maintaining all my Nature of Code examples like so:

https://github.com/shiffman/NOC-S18/wiki/Web-Editor-Examples

However, I never remember to fix something there when I change something in the [code repo](https://github.com/shiffman/The-Nature-of-Code-Examples-p5.js/). Is this something I could adapt to help me with this?

**Comment by joeyklee** [comment]
hi @shiffman! 

I think @catarak would have to answer to the longer term types of integration and batch uploading, etc, but the script does take all the sketches from a github repo, deletes the old projects in the p5 editor database, and re-uploads them.

I guess the tricky situation in your case is that @catarak would have to run the upload script server side which isn't so sustainable. 

On the list of to-dos is to make it possible to batch upload. Super cool would be to have github integration so that changes to projects in a repo would be pushed to the p5 editor. Though I can't imagine this being such a small task, or?

**Comment by catarak** [comment]
i see this happening in a few stages:
1. folks make pull requests that include sketches that upload files to the editor. i run them on the server.
2. you can authenticate with the api with a token. you can write a script to batch upload sketches.
3. github integration??? i bet you can see a list of all your repos on github, would be cool to be able to see them and cherry pick the ones you want to upload to the web editor
4. have a way to denote example sketches? maybe they would be part of a "classroom" or a "class"?

**Comment by catarak** [comment]
also i'm not sure there's an open ticket for the API token authentication and batch uploading of sketches, if not i will make one now.

**Comment by shiffman** [comment]
I love the idea of an API for batch uploading and/or github integration. I don't think it's feasible for @catarak to have to manage a bunch of pull requests for scripts that upload files via the server. It's ok for the "core" examples that come with the editor, but otherwise it would become a mess very quickly!

I'll follow along in #541, I'm good with the workflow I have for now, thank you!

**Pull request merged**
